# This file was auto generated by Styx.
# Do not edit this file directly.

import dataclasses
import pathlib
import typing

from styxdefs import Execution, InputPathType, Metadata, Runner, StyxValidationError, OutputPathType, get_global_runner

IMCAT_METADATA = Metadata(
    id="imcat",
    name="imcat",
    package="afni",
)

Imcat = typing.TypedDict(
    "Imcat",
    {
        "@type": typing.NotRequired[typing.Literal["afni/imcat"]],
        "input_files": list[InputPathType],
        "scale_image": typing.NotRequired[InputPathType],
        "scale_pixels": typing.NotRequired[InputPathType],
        "scale_intensity": typing.NotRequired[bool],
        "gscale": typing.NotRequired[float],
        "rgb_out": typing.NotRequired[bool],
        "res_in": typing.NotRequired[list[float]],
        "respad_in": typing.NotRequired[list[float]],
        "pad_val": typing.NotRequired[float],
        "crop": typing.NotRequired[list[float]],
        "autocrop_ctol": typing.NotRequired[float],
        "autocrop_atol": typing.NotRequired[float],
        "autocrop": typing.NotRequired[bool],
        "zero_wrap": typing.NotRequired[bool],
        "white_wrap": typing.NotRequired[bool],
        "gray_wrap": typing.NotRequired[float],
        "image_wrap": typing.NotRequired[bool],
        "rand_wrap": typing.NotRequired[bool],
        "prefix": typing.NotRequired[str],
        "matrix": typing.NotRequired[list[float]],
        "nx": typing.NotRequired[float],
        "ny": typing.NotRequired[float],
        "matrix_from_scale": typing.NotRequired[bool],
        "gap": typing.NotRequired[float],
        "gap_col": typing.NotRequired[list[float]],
    },
)

@dataclasses.dataclass
class ImcatOutputs:
    """Output paths produced by the tool."""
    root: OutputPathType
    output_image_file: OutputPathType | None
    """Output image file"""

def imcat_params(
    input_files: list[InputPathType],
    scale_image: InputPathType | None = None,
    scale_pixels: InputPathType | None = None,
    scale_intensity: bool = False,
    gscale: float | None = None,
    rgb_out: bool = False,
    res_in: list[float] | None = None,
    respad_in: list[float] | None = None,
    pad_val: float | None = None,
    crop: list[float] | None = None,
    autocrop_ctol: float | None = None,
    autocrop_atol: float | None = None,
    autocrop: bool = False,
    zero_wrap: bool = False,
    white_wrap: bool = False,
    gray_wrap: float | None = None,
    image_wrap: bool = False,
    rand_wrap: bool = False,
    prefix: str | None = None,
    matrix: list[float] | None = None,
    nx: float | None = None,
    ny: float | None = None,
    matrix_from_scale: bool = False,
    gap: float | None = None,
    gap_col: list[float] | None = None,
) -> Imcat:
    """
    Build parameters.

    Args:
        input_files: Input image files
        scale_image: Multiply each image IM(i,j) in output image matrix IM by the\
            color or intensity of the pixel (i,j) in SCALE_IMG.
        scale_pixels: Multiply each pixel (i,j) in output image by the color or\
            intensity of the pixel (i,j) in SCALE_IMG. SCALE_IMG is automatically\
            resized to the resolution of the output image.
        scale_intensity: Instead of multiplying by the color of pixel (i,j), use\
            its intensity (average color).
        gscale: Apply FAC in addition to scaling of -scale_* options.
        rgb_out: Force output to be in RGB, even if input is bytes. This option is\
            turned on automatically in certain cases.
        res_in: Set resolution of all input images to RX by RY pixels. Default is\
            to make all input have the same resolution as the first image.
        respad_in: Like -res_in, but resample to the max while respecting the\
            aspect ratio, and then pad to achieve desired pixel count.
        pad_val: Set the padding value, should it be needed by -respad_in to VAL.\
            VAL is typecast to byte, default is 0, max is 255.
        crop: Crop images by L (Left), R (Right), T (Top), B (Bottom) pixels.\
            Cutting is performed after any resolution change, if any, is to be\
            done.
        autocrop_ctol: A line is eliminated if none of its R G B values differ by\
            more than CTOL% from those of the corner pixel.
        autocrop_atol: A line is eliminated if none of its R G B values differ by\
            more than ATOL% from those of line average.
        autocrop: This option is the same as using both of -autocrop_atol 20 and\
            -autocrop_ctol 20
        zero_wrap: If number of images is not enough to fill matrix solid black\
            images are used.
        white_wrap: If number of images is not enough to fill matrix solid white\
            images are used.
        gray_wrap: If number of images is not enough to fill matrix, solid gray\
            images are used. GRAY must be between 0 and 1.0.
        image_wrap: If number of images is not enough to fill matrix, images on\
            command line are reused (default).
        rand_wrap: When reusing images to fill matrix, randomize the order in\
            refill section only.
        prefix: Prefix the output files with string 'ppp'.
        matrix: Specify number of images in each row and column of IM at the same\
            time.
        nx: Number of images in each row.
        ny: Number of images in each column.
        matrix_from_scale: Set NX and NY to be the same as the SCALE_IMG's\
            dimensions. (needs -scale_image)
        gap: Put a line G pixels wide between images.
        gap_col: Set color of line to R G B values. Values range between 0 and 255.

    Returns:
        Parameter dictionary.
    """
    params: Imcat = {
        "@type": "afni/imcat",
        "input_files": input_files,
        "scale_intensity": scale_intensity,
        "rgb_out": rgb_out,
        "autocrop": autocrop,
        "zero_wrap": zero_wrap,
        "white_wrap": white_wrap,
        "image_wrap": image_wrap,
        "rand_wrap": rand_wrap,
        "matrix_from_scale": matrix_from_scale,
    }
    if scale_image is not None:
        params["scale_image"] = scale_image
    if scale_pixels is not None:
        params["scale_pixels"] = scale_pixels
    if gscale is not None:
        params["gscale"] = gscale
    if res_in is not None:
        params["res_in"] = res_in
    if respad_in is not None:
        params["respad_in"] = respad_in
    if pad_val is not None:
        params["pad_val"] = pad_val
    if crop is not None:
        params["crop"] = crop
    if autocrop_ctol is not None:
        params["autocrop_ctol"] = autocrop_ctol
    if autocrop_atol is not None:
        params["autocrop_atol"] = autocrop_atol
    if gray_wrap is not None:
        params["gray_wrap"] = gray_wrap
    if prefix is not None:
        params["prefix"] = prefix
    if matrix is not None:
        params["matrix"] = matrix
    if nx is not None:
        params["nx"] = nx
    if ny is not None:
        params["ny"] = ny
    if gap is not None:
        params["gap"] = gap
    if gap_col is not None:
        params["gap_col"] = gap_col
    return params

def imcat_validate(params: typing.Any) -> None:
    """Validate untrusted parameters. Raises StyxValidationError if `params` is not a valid Imcat."""
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("input_files", None) is None:
        raise StyxValidationError("`input_files` must not be None")
    if not isinstance(params["input_files"], list):
        raise StyxValidationError(f'`input_files` has the wrong type: Received `{type(params["input_files"])}` expected `list[InputPathType]`')
    for e in params["input_files"]:
        if not isinstance(e, (pathlib.Path, str)):
            raise StyxValidationError(f'`input_files` has the wrong type: Received `{type(e)}` expected `list[InputPathType]`')
    if params.get("scale_image", None) is not None:
        if not isinstance(params["scale_image"], (pathlib.Path, str)):
            raise StyxValidationError(f'`scale_image` has the wrong type: Received `{type(params["scale_image"])}` expected `InputPathType`')
    if params.get("scale_pixels", None) is not None:
        if not isinstance(params["scale_pixels"], (pathlib.Path, str)):
            raise StyxValidationError(f'`scale_pixels` has the wrong type: Received `{type(params["scale_pixels"])}` expected `InputPathType`')
    if params.get("scale_intensity", None) is not None:
        if not isinstance(params["scale_intensity"], bool):
            raise StyxValidationError(f'`scale_intensity` has the wrong type: Received `{type(params["scale_intensity"])}` expected `bool`')
    if params.get("gscale", None) is not None:
        if not isinstance(params["gscale"], (float, int)):
            raise StyxValidationError(f'`gscale` has the wrong type: Received `{type(params["gscale"])}` expected `float`')
    if params.get("rgb_out", None) is not None:
        if not isinstance(params["rgb_out"], bool):
            raise StyxValidationError(f'`rgb_out` has the wrong type: Received `{type(params["rgb_out"])}` expected `bool`')
    if params.get("res_in", None) is not None:
        if not isinstance(params["res_in"], list):
            raise StyxValidationError(f'`res_in` has the wrong type: Received `{type(params["res_in"])}` expected `list[float]`')
        if len(params["res_in"]) > 2:
            raise StyxValidationError("Parameter `res_in` must contain at most 2 elements")
        for e_2 in params["res_in"]:
            if not isinstance(e_2, (float, int)):
                raise StyxValidationError(f'`res_in` has the wrong type: Received `{type(e_2)}` expected `list[float]`')
    if params.get("respad_in", None) is not None:
        if not isinstance(params["respad_in"], list):
            raise StyxValidationError(f'`respad_in` has the wrong type: Received `{type(params["respad_in"])}` expected `list[float]`')
        if len(params["respad_in"]) > 2:
            raise StyxValidationError("Parameter `respad_in` must contain at most 2 elements")
        for e_3 in params["respad_in"]:
            if not isinstance(e_3, (float, int)):
                raise StyxValidationError(f'`respad_in` has the wrong type: Received `{type(e_3)}` expected `list[float]`')
    if params.get("pad_val", None) is not None:
        if not isinstance(params["pad_val"], (float, int)):
            raise StyxValidationError(f'`pad_val` has the wrong type: Received `{type(params["pad_val"])}` expected `float`')
        if not (0 <= params["pad_val"] <= 255):
            raise StyxValidationError("Parameter `pad_val` must be between 0 and 255 (inclusive)")
    if params.get("crop", None) is not None:
        if not isinstance(params["crop"], list):
            raise StyxValidationError(f'`crop` has the wrong type: Received `{type(params["crop"])}` expected `list[float]`')
        if len(params["crop"]) > 4:
            raise StyxValidationError("Parameter `crop` must contain at most 4 elements")
        for e_4 in params["crop"]:
            if not isinstance(e_4, (float, int)):
                raise StyxValidationError(f'`crop` has the wrong type: Received `{type(e_4)}` expected `list[float]`')
    if params.get("autocrop_ctol", None) is not None:
        if not isinstance(params["autocrop_ctol"], (float, int)):
            raise StyxValidationError(f'`autocrop_ctol` has the wrong type: Received `{type(params["autocrop_ctol"])}` expected `float`')
    if params.get("autocrop_atol", None) is not None:
        if not isinstance(params["autocrop_atol"], (float, int)):
            raise StyxValidationError(f'`autocrop_atol` has the wrong type: Received `{type(params["autocrop_atol"])}` expected `float`')
    if params.get("autocrop", None) is not None:
        if not isinstance(params["autocrop"], bool):
            raise StyxValidationError(f'`autocrop` has the wrong type: Received `{type(params["autocrop"])}` expected `bool`')
    if params.get("zero_wrap", None) is not None:
        if not isinstance(params["zero_wrap"], bool):
            raise StyxValidationError(f'`zero_wrap` has the wrong type: Received `{type(params["zero_wrap"])}` expected `bool`')
    if params.get("white_wrap", None) is not None:
        if not isinstance(params["white_wrap"], bool):
            raise StyxValidationError(f'`white_wrap` has the wrong type: Received `{type(params["white_wrap"])}` expected `bool`')
    if params.get("gray_wrap", None) is not None:
        if not isinstance(params["gray_wrap"], (float, int)):
            raise StyxValidationError(f'`gray_wrap` has the wrong type: Received `{type(params["gray_wrap"])}` expected `float`')
        if not (0 <= params["gray_wrap"] <= 1):
            raise StyxValidationError("Parameter `gray_wrap` must be between 0 and 1 (inclusive)")
    if params.get("image_wrap", None) is not None:
        if not isinstance(params["image_wrap"], bool):
            raise StyxValidationError(f'`image_wrap` has the wrong type: Received `{type(params["image_wrap"])}` expected `bool`')
    if params.get("rand_wrap", None) is not None:
        if not isinstance(params["rand_wrap"], bool):
            raise StyxValidationError(f'`rand_wrap` has the wrong type: Received `{type(params["rand_wrap"])}` expected `bool`')
    if params.get("prefix", None) is not None:
        if not isinstance(params["prefix"], str):
            raise StyxValidationError(f'`prefix` has the wrong type: Received `{type(params["prefix"])}` expected `str`')
    if params.get("matrix", None) is not None:
        if not isinstance(params["matrix"], list):
            raise StyxValidationError(f'`matrix` has the wrong type: Received `{type(params["matrix"])}` expected `list[float]`')
        if len(params["matrix"]) > 2:
            raise StyxValidationError("Parameter `matrix` must contain at most 2 elements")
        for e_5 in params["matrix"]:
            if not isinstance(e_5, (float, int)):
                raise StyxValidationError(f'`matrix` has the wrong type: Received `{type(e_5)}` expected `list[float]`')
    if params.get("nx", None) is not None:
        if not isinstance(params["nx"], (float, int)):
            raise StyxValidationError(f'`nx` has the wrong type: Received `{type(params["nx"])}` expected `float`')
    if params.get("ny", None) is not None:
        if not isinstance(params["ny"], (float, int)):
            raise StyxValidationError(f'`ny` has the wrong type: Received `{type(params["ny"])}` expected `float`')
    if params.get("matrix_from_scale", None) is not None:
        if not isinstance(params["matrix_from_scale"], bool):
            raise StyxValidationError(f'`matrix_from_scale` has the wrong type: Received `{type(params["matrix_from_scale"])}` expected `bool`')
    if params.get("gap", None) is not None:
        if not isinstance(params["gap"], (float, int)):
            raise StyxValidationError(f'`gap` has the wrong type: Received `{type(params["gap"])}` expected `float`')
    if params.get("gap_col", None) is not None:
        if not isinstance(params["gap_col"], list):
            raise StyxValidationError(f'`gap_col` has the wrong type: Received `{type(params["gap_col"])}` expected `list[float]`')
        if len(params["gap_col"]) > 3:
            raise StyxValidationError("Parameter `gap_col` must contain at most 3 elements")
        for e_6 in params["gap_col"]:
            if not isinstance(e_6, (float, int)):
                raise StyxValidationError(f'`gap_col` has the wrong type: Received `{type(e_6)}` expected `list[float]`')

def imcat_cargs(params: Imcat, execution: Execution) -> list[str]:
    """Build command-line arguments from parameters."""
    cargs: list[str] = []
    cargs.append("imcat")
    for item0 in params["input_files"]:
        cargs.append(execution.input_file(item0))
    v_0 = params.get("scale_image")
    if v_0 is not None:
        cargs.append("-scale_image")
        cargs.append(execution.input_file(v_0))
    v_1 = params.get("scale_pixels")
    if v_1 is not None:
        cargs.append("-scale_pixels")
        cargs.append(execution.input_file(v_1))
    if params.get("scale_intensity"):
        cargs.append("-scale_intensity")
    v_2 = params.get("gscale")
    if v_2 is not None:
        cargs.append("-gscale")
        cargs.append(str(v_2))
    if params.get("rgb_out"):
        cargs.append("-rgb_out")
    v_3 = params.get("res_in")
    if v_3 is not None:
        cargs.append("-res_in")
        for item1 in v_3:
            cargs.append(str(item1))
    v_4 = params.get("respad_in")
    if v_4 is not None:
        cargs.append("-respad_in")
        for item2 in v_4:
            cargs.append(str(item2))
    v_5 = params.get("pad_val")
    if v_5 is not None:
        cargs.append("-pad_val")
        cargs.append(str(v_5))
    v_6 = params.get("crop")
    if v_6 is not None:
        cargs.append("-crop")
        for item3 in v_6:
            cargs.append(str(item3))
    v_7 = params.get("autocrop_ctol")
    if v_7 is not None:
        cargs.append("-autocrop_ctol")
        cargs.append(str(v_7))
    v_8 = params.get("autocrop_atol")
    if v_8 is not None:
        cargs.append("-autocrop_atol")
        cargs.append(str(v_8))
    if params.get("autocrop"):
        cargs.append("-autocrop")
    if params.get("zero_wrap"):
        cargs.append("-zero_wrap")
    if params.get("white_wrap"):
        cargs.append("-white_wrap")
    v_9 = params.get("gray_wrap")
    if v_9 is not None:
        cargs.append("-gray_wrap")
        cargs.append(str(v_9))
    if params.get("image_wrap"):
        cargs.append("-image_wrap")
    if params.get("rand_wrap"):
        cargs.append("-rand_wrap")
    v_10 = params.get("prefix")
    if v_10 is not None:
        cargs.append("-prefix")
        cargs.append(v_10)
    v_11 = params.get("matrix")
    if v_11 is not None:
        cargs.append("-matrix")
        for item4 in v_11:
            cargs.append(str(item4))
    v_12 = params.get("nx")
    if v_12 is not None:
        cargs.append("-nx")
        cargs.append(str(v_12))
    v_13 = params.get("ny")
    if v_13 is not None:
        cargs.append("-ny")
        cargs.append(str(v_13))
    if params.get("matrix_from_scale"):
        cargs.append("-matrix_from_scale")
    v_14 = params.get("gap")
    if v_14 is not None:
        cargs.append("-gap")
        cargs.append(str(v_14))
    v_15 = params.get("gap_col")
    if v_15 is not None:
        cargs.append("-gap_col")
        for item5 in v_15:
            cargs.append(str(item5))
    return cargs

def imcat_outputs(params: Imcat, execution: Execution) -> ImcatOutputs:
    """Build the ImcatOutputs object for this tool."""
    output_image_file_v: OutputPathType | None = None
    root_v: OutputPathType = execution.output_file(".")
    __v0 = params.get("prefix")
    if __v0 is not None:
        output_image_file_v = execution.output_file(f'{(__v0 if __v0 is not None else "")}output_image.[EXT]')
    return ImcatOutputs(
        root=root_v,
        output_image_file=output_image_file_v,
    )

def imcat_execute(params: Imcat, runner: Runner | None = None) -> ImcatOutputs:
    """
    imcat

    Assembles a set of images into an image matrix (IM) montage of NX by NY images.

    Author: AFNI Developers

    URL: https://afni.nimh.nih.gov/

    Args:
        params: The parameters.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    imcat_validate(params)
    runner = runner if runner is not None else get_global_runner()
    execution = runner.start_execution(IMCAT_METADATA)
    execution.params(params)
    args = imcat_cargs(params, execution)
    out = imcat_outputs(params, execution)
    execution.run(args)
    return out

def imcat(
    input_files: list[InputPathType],
    scale_image: InputPathType | None = None,
    scale_pixels: InputPathType | None = None,
    scale_intensity: bool = False,
    gscale: float | None = None,
    rgb_out: bool = False,
    res_in: list[float] | None = None,
    respad_in: list[float] | None = None,
    pad_val: float | None = None,
    crop: list[float] | None = None,
    autocrop_ctol: float | None = None,
    autocrop_atol: float | None = None,
    autocrop: bool = False,
    zero_wrap: bool = False,
    white_wrap: bool = False,
    gray_wrap: float | None = None,
    image_wrap: bool = False,
    rand_wrap: bool = False,
    prefix: str | None = None,
    matrix: list[float] | None = None,
    nx: float | None = None,
    ny: float | None = None,
    matrix_from_scale: bool = False,
    gap: float | None = None,
    gap_col: list[float] | None = None,
    runner: Runner | None = None,
) -> ImcatOutputs:
    """
    imcat

    Assembles a set of images into an image matrix (IM) montage of NX by NY images.

    Author: AFNI Developers

    URL: https://afni.nimh.nih.gov/

    Args:
        input_files: Input image files
        scale_image: Multiply each image IM(i,j) in output image matrix IM by the\
            color or intensity of the pixel (i,j) in SCALE_IMG.
        scale_pixels: Multiply each pixel (i,j) in output image by the color or\
            intensity of the pixel (i,j) in SCALE_IMG. SCALE_IMG is automatically\
            resized to the resolution of the output image.
        scale_intensity: Instead of multiplying by the color of pixel (i,j), use\
            its intensity (average color).
        gscale: Apply FAC in addition to scaling of -scale_* options.
        rgb_out: Force output to be in RGB, even if input is bytes. This option is\
            turned on automatically in certain cases.
        res_in: Set resolution of all input images to RX by RY pixels. Default is\
            to make all input have the same resolution as the first image.
        respad_in: Like -res_in, but resample to the max while respecting the\
            aspect ratio, and then pad to achieve desired pixel count.
        pad_val: Set the padding value, should it be needed by -respad_in to VAL.\
            VAL is typecast to byte, default is 0, max is 255.
        crop: Crop images by L (Left), R (Right), T (Top), B (Bottom) pixels.\
            Cutting is performed after any resolution change, if any, is to be\
            done.
        autocrop_ctol: A line is eliminated if none of its R G B values differ by\
            more than CTOL% from those of the corner pixel.
        autocrop_atol: A line is eliminated if none of its R G B values differ by\
            more than ATOL% from those of line average.
        autocrop: This option is the same as using both of -autocrop_atol 20 and\
            -autocrop_ctol 20
        zero_wrap: If number of images is not enough to fill matrix solid black\
            images are used.
        white_wrap: If number of images is not enough to fill matrix solid white\
            images are used.
        gray_wrap: If number of images is not enough to fill matrix, solid gray\
            images are used. GRAY must be between 0 and 1.0.
        image_wrap: If number of images is not enough to fill matrix, images on\
            command line are reused (default).
        rand_wrap: When reusing images to fill matrix, randomize the order in\
            refill section only.
        prefix: Prefix the output files with string 'ppp'.
        matrix: Specify number of images in each row and column of IM at the same\
            time.
        nx: Number of images in each row.
        ny: Number of images in each column.
        matrix_from_scale: Set NX and NY to be the same as the SCALE_IMG's\
            dimensions. (needs -scale_image)
        gap: Put a line G pixels wide between images.
        gap_col: Set color of line to R G B values. Values range between 0 and 255.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    params = imcat_params(
        input_files=input_files,
        scale_image=scale_image,
        scale_pixels=scale_pixels,
        scale_intensity=scale_intensity,
        gscale=gscale,
        rgb_out=rgb_out,
        res_in=res_in,
        respad_in=respad_in,
        pad_val=pad_val,
        crop=crop,
        autocrop_ctol=autocrop_ctol,
        autocrop_atol=autocrop_atol,
        autocrop=autocrop,
        zero_wrap=zero_wrap,
        white_wrap=white_wrap,
        gray_wrap=gray_wrap,
        image_wrap=image_wrap,
        rand_wrap=rand_wrap,
        prefix=prefix,
        matrix=matrix,
        nx=nx,
        ny=ny,
        matrix_from_scale=matrix_from_scale,
        gap=gap,
        gap_col=gap_col,
    )
    return imcat_execute(params, runner)

__all__ = [
    "Imcat",
    "ImcatOutputs",
    "IMCAT_METADATA",
    "imcat_cargs",
    "imcat_outputs",
    "imcat_params",
    "imcat_execute",
    "imcat_validate",
    "imcat",
]