# This file was auto generated by Styx.
# Do not edit this file directly.

import dataclasses
import pathlib
import typing

from styxdefs import Execution, InputPathType, Metadata, Runner, StyxValidationError, OutputPathType, get_global_runner

SURF_FWHM_METADATA = Metadata(
    id="SurfFWHM",
    name="SurfFWHM",
    package="afni",
)

SurfFwhm = typing.TypedDict(
    "SurfFwhm",
    {
        "@type": typing.NotRequired[typing.Literal["afni/SurfFWHM"]],
        "input_file": InputPathType,
        "mask": typing.NotRequired[InputPathType],
        "surf_1": typing.NotRequired[str],
        "surf_sphere": typing.NotRequired[str],
        "clean": typing.NotRequired[bool],
        "detrend": typing.NotRequired[float],
        "detpoly": typing.NotRequired[float],
        "detprefix": typing.NotRequired[str],
        "prefix": typing.NotRequired[str],
        "vox_size": typing.NotRequired[float],
        "neighborhood": typing.NotRequired[float],
        "ok_warn": typing.NotRequired[bool],
        "examples": typing.NotRequired[bool],
        "slice": typing.NotRequired[bool],
    },
)

@dataclasses.dataclass
class SurfFwhmOutputs:
    """Output paths produced by the tool."""
    root: OutputPathType
    detrended_output: OutputPathType | None
    """Detrended dataset."""
    main_output: OutputPathType | None
    """Main output dataset."""
    histogram_output: OutputPathType | None
    """Histogram showing the distribution of local FWHM."""
    mask_output: OutputPathType | None
    """Mask output dataset."""

def surf_fwhm_params(
    input_file: InputPathType,
    mask: InputPathType | None = None,
    surf_1: str | None = None,
    surf_sphere: str | None = None,
    clean: bool = False,
    detrend: float | None = None,
    detpoly: float | None = None,
    detprefix: str | None = None,
    prefix: str | None = None,
    vox_size: float | None = None,
    neighborhood: float | None = None,
    ok_warn: bool = False,
    examples: bool = False,
    slice: bool = False,
) -> SurfFwhm:
    """
    Build parameters.

    Args:
        input_file: Dataset for which the FWHM is to be calculated.
        mask: Node mask so that only nodes in the mask are used to obtain\
            estimates.
        surf_1: Option for specifying the surface over which the input dataset is\
            defined.
        surf_sphere: Spherical version of -SURF_1 for Local FWHM estimates.
        clean: Strip text from output to simplify parsing.
        detrend: Detrend to order 'q'. If q is not given, the program picks\
            q=NT/30.
        detpoly: Detrend with polynomials of order p.
        detprefix: Save the detrended file into a dataset with prefix 'd'.
        prefix: Prefix of output data set.
        vox_size: Specify the nominal voxel size in mm.
        neighborhood: Neighborhood radius R for local FWHM estimates.
        ok_warn: Flag to set the mode to ok_warn.
        examples: Show command line examples and quit.
        slice: Use the contours from planar intersections to estimate gradients.\
            For testing and development purposes only.

    Returns:
        Parameter dictionary.
    """
    params: SurfFwhm = {
        "@type": "afni/SurfFWHM",
        "input_file": input_file,
        "clean": clean,
        "ok_warn": ok_warn,
        "examples": examples,
        "slice": slice,
    }
    if mask is not None:
        params["mask"] = mask
    if surf_1 is not None:
        params["surf_1"] = surf_1
    if surf_sphere is not None:
        params["surf_sphere"] = surf_sphere
    if detrend is not None:
        params["detrend"] = detrend
    if detpoly is not None:
        params["detpoly"] = detpoly
    if detprefix is not None:
        params["detprefix"] = detprefix
    if prefix is not None:
        params["prefix"] = prefix
    if vox_size is not None:
        params["vox_size"] = vox_size
    if neighborhood is not None:
        params["neighborhood"] = neighborhood
    return params

def surf_fwhm_validate(params: typing.Any) -> None:
    """Validate untrusted parameters. Raises StyxValidationError if `params` is not a valid SurfFwhm."""
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("input_file", None) is None:
        raise StyxValidationError("`input_file` must not be None")
    if not isinstance(params["input_file"], (pathlib.Path, str)):
        raise StyxValidationError(f'`input_file` has the wrong type: Received `{type(params["input_file"])}` expected `InputPathType`')
    if params.get("mask", None) is not None:
        if not isinstance(params["mask"], (pathlib.Path, str)):
            raise StyxValidationError(f'`mask` has the wrong type: Received `{type(params["mask"])}` expected `InputPathType`')
    if params.get("surf_1", None) is not None:
        if not isinstance(params["surf_1"], str):
            raise StyxValidationError(f'`surf_1` has the wrong type: Received `{type(params["surf_1"])}` expected `str`')
    if params.get("surf_sphere", None) is not None:
        if not isinstance(params["surf_sphere"], str):
            raise StyxValidationError(f'`surf_sphere` has the wrong type: Received `{type(params["surf_sphere"])}` expected `str`')
    if params.get("clean", None) is not None:
        if not isinstance(params["clean"], bool):
            raise StyxValidationError(f'`clean` has the wrong type: Received `{type(params["clean"])}` expected `bool`')
    if params.get("detrend", None) is not None:
        if not isinstance(params["detrend"], (float, int)):
            raise StyxValidationError(f'`detrend` has the wrong type: Received `{type(params["detrend"])}` expected `float`')
    if params.get("detpoly", None) is not None:
        if not isinstance(params["detpoly"], (float, int)):
            raise StyxValidationError(f'`detpoly` has the wrong type: Received `{type(params["detpoly"])}` expected `float`')
    if params.get("detprefix", None) is not None:
        if not isinstance(params["detprefix"], str):
            raise StyxValidationError(f'`detprefix` has the wrong type: Received `{type(params["detprefix"])}` expected `str`')
    if params.get("prefix", None) is not None:
        if not isinstance(params["prefix"], str):
            raise StyxValidationError(f'`prefix` has the wrong type: Received `{type(params["prefix"])}` expected `str`')
    if params.get("vox_size", None) is not None:
        if not isinstance(params["vox_size"], (float, int)):
            raise StyxValidationError(f'`vox_size` has the wrong type: Received `{type(params["vox_size"])}` expected `float`')
    if params.get("neighborhood", None) is not None:
        if not isinstance(params["neighborhood"], (float, int)):
            raise StyxValidationError(f'`neighborhood` has the wrong type: Received `{type(params["neighborhood"])}` expected `float`')
    if params.get("ok_warn", None) is not None:
        if not isinstance(params["ok_warn"], bool):
            raise StyxValidationError(f'`ok_warn` has the wrong type: Received `{type(params["ok_warn"])}` expected `bool`')
    if params.get("examples", None) is not None:
        if not isinstance(params["examples"], bool):
            raise StyxValidationError(f'`examples` has the wrong type: Received `{type(params["examples"])}` expected `bool`')
    if params.get("slice", None) is not None:
        if not isinstance(params["slice"], bool):
            raise StyxValidationError(f'`slice` has the wrong type: Received `{type(params["slice"])}` expected `bool`')

def surf_fwhm_cargs(params: SurfFwhm, execution: Execution) -> list[str]:
    """Build command-line arguments from parameters."""
    cargs: list[str] = []
    cargs.append("SurfFWHM")
    cargs.append(execution.input_file(params["input_file"]))
    v_0 = params.get("mask")
    if v_0 is not None:
        cargs.append("-MASK")
        cargs.append(execution.input_file(v_0))
    v_1 = params.get("surf_1")
    if v_1 is not None:
        cargs.append("-SURF_1")
        cargs.append(v_1)
    v_2 = params.get("surf_sphere")
    if v_2 is not None:
        cargs.append("-SURF_SPHERE")
        cargs.append(v_2)
    if params.get("clean"):
        cargs.append("-clean")
    v_3 = params.get("detrend")
    if v_3 is not None:
        cargs.append("-detrend")
        cargs.append(str(v_3))
    v_4 = params.get("detpoly")
    if v_4 is not None:
        cargs.append("-detpoly")
        cargs.append(str(v_4))
    v_5 = params.get("detprefix")
    if v_5 is not None:
        cargs.append("-detprefix")
        cargs.append(v_5)
    v_6 = params.get("prefix")
    if v_6 is not None:
        cargs.append("-prefix")
        cargs.append(v_6)
    v_7 = params.get("vox_size")
    if v_7 is not None:
        cargs.append("-vox_size")
        cargs.append(str(v_7))
    v_8 = params.get("neighborhood")
    if v_8 is not None:
        cargs.append("-hood")
        cargs.append(str(v_8))
    if params.get("ok_warn"):
        cargs.append("-ok_warn")
    if params.get("examples"):
        cargs.append("-examples")
    if params.get("slice"):
        cargs.append("-slice")
    return cargs

def surf_fwhm_outputs(params: SurfFwhm, execution: Execution) -> SurfFwhmOutputs:
    """Build the SurfFwhmOutputs object for this tool."""
    detrended_output_v: OutputPathType | None = None
    main_output_v: OutputPathType | None = None
    histogram_output_v: OutputPathType | None = None
    mask_output_v: OutputPathType | None = None
    root_v: OutputPathType = execution.output_file(".")
    __v0 = params.get("prefix")
    if __v0 is not None:
        detrended_output_v = execution.output_file(f'{(__v0 if __v0 is not None else "")}.1D.dset')
    __v1 = params.get("prefix")
    if __v1 is not None:
        main_output_v = execution.output_file(f'{(__v1 if __v1 is not None else "")}.nii.gz')
    __v2 = params.get("prefix")
    if __v2 is not None:
        histogram_output_v = execution.output_file(f'{(__v2 if __v2 is not None else "")}_histog.1D')
    __v3 = params.get("prefix")
    if __v3 is not None:
        mask_output_v = execution.output_file(f'{(__v3 if __v3 is not None else "")}_mask.nii.gz')
    return SurfFwhmOutputs(
        root=root_v,
        detrended_output=detrended_output_v,
        main_output=main_output_v,
        histogram_output=histogram_output_v,
        mask_output=mask_output_v,
    )

def surf_fwhm_execute(params: SurfFwhm, runner: Runner | None = None) -> SurfFwhmOutputs:
    """
    SurfFWHM

    A program for calculating local and global FWHM.

    Author: AFNI Developers

    URL: https://afni.nimh.nih.gov/

    Args:
        params: The parameters.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    surf_fwhm_validate(params)
    runner = runner if runner is not None else get_global_runner()
    execution = runner.start_execution(SURF_FWHM_METADATA)
    execution.params(params)
    args = surf_fwhm_cargs(params, execution)
    out = surf_fwhm_outputs(params, execution)
    execution.run(args)
    return out

def surf_fwhm(
    input_file: InputPathType,
    mask: InputPathType | None = None,
    surf_1: str | None = None,
    surf_sphere: str | None = None,
    clean: bool = False,
    detrend: float | None = None,
    detpoly: float | None = None,
    detprefix: str | None = None,
    prefix: str | None = None,
    vox_size: float | None = None,
    neighborhood: float | None = None,
    ok_warn: bool = False,
    examples: bool = False,
    slice: bool = False,
    runner: Runner | None = None,
) -> SurfFwhmOutputs:
    """
    SurfFWHM

    A program for calculating local and global FWHM.

    Author: AFNI Developers

    URL: https://afni.nimh.nih.gov/

    Args:
        input_file: Dataset for which the FWHM is to be calculated.
        mask: Node mask so that only nodes in the mask are used to obtain\
            estimates.
        surf_1: Option for specifying the surface over which the input dataset is\
            defined.
        surf_sphere: Spherical version of -SURF_1 for Local FWHM estimates.
        clean: Strip text from output to simplify parsing.
        detrend: Detrend to order 'q'. If q is not given, the program picks\
            q=NT/30.
        detpoly: Detrend with polynomials of order p.
        detprefix: Save the detrended file into a dataset with prefix 'd'.
        prefix: Prefix of output data set.
        vox_size: Specify the nominal voxel size in mm.
        neighborhood: Neighborhood radius R for local FWHM estimates.
        ok_warn: Flag to set the mode to ok_warn.
        examples: Show command line examples and quit.
        slice: Use the contours from planar intersections to estimate gradients.\
            For testing and development purposes only.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    params = surf_fwhm_params(
        input_file=input_file,
        mask=mask,
        surf_1=surf_1,
        surf_sphere=surf_sphere,
        clean=clean,
        detrend=detrend,
        detpoly=detpoly,
        detprefix=detprefix,
        prefix=prefix,
        vox_size=vox_size,
        neighborhood=neighborhood,
        ok_warn=ok_warn,
        examples=examples,
        slice=slice,
    )
    return surf_fwhm_execute(params, runner)

__all__ = [
    "SurfFwhm",
    "SurfFwhmOutputs",
    "SURF_FWHM_METADATA",
    "surf_fwhm_cargs",
    "surf_fwhm_outputs",
    "surf_fwhm_params",
    "surf_fwhm_execute",
    "surf_fwhm_validate",
    "surf_fwhm",
]