# This file was auto generated by Styx.
# Do not edit this file directly.

import dataclasses
import pathlib
import typing

from styxdefs import Execution, InputPathType, Metadata, Runner, StyxValidationError, OutputPathType, get_global_runner

V_3D_WARP_DRIVE_METADATA = Metadata(
    id="3dWarpDrive",
    name="3dWarpDrive",
    package="afni",
)

V3dWarpDrive = typing.TypedDict(
    "V3dWarpDrive",
    {
        "@type": typing.NotRequired[typing.Literal["afni/3dWarpDrive"]],
        "dataset": InputPathType,
        "base_dataset": InputPathType,
        "prefix": str,
        "shift_only": typing.NotRequired[bool],
        "shift_rotate": typing.NotRequired[bool],
        "shift_rotate_scale": typing.NotRequired[bool],
        "affine_general": typing.NotRequired[bool],
        "bilinear_general": typing.NotRequired[bool],
        "linear": typing.NotRequired[bool],
        "cubic": typing.NotRequired[bool],
        "NN": typing.NotRequired[bool],
        "quintic": typing.NotRequired[bool],
        "input_dataset": typing.NotRequired[InputPathType],
        "verbosity_flag": typing.NotRequired[bool],
        "summary_file": typing.NotRequired[str],
        "max_iterations": typing.NotRequired[int],
        "delta": typing.NotRequired[float],
        "weight": typing.NotRequired[str],
        "convergence_thresh": typing.NotRequired[float],
        "twopass": typing.NotRequired[bool],
        "final_mode": typing.NotRequired[str],
        "parfix": typing.NotRequired[list[str]],
        "oned_file": typing.NotRequired[InputPathType],
        "float_format": typing.NotRequired[bool],
        "coarserot_init": typing.NotRequired[bool],
        "oned_matrix_save": typing.NotRequired[InputPathType],
        "sdu_order": typing.NotRequired[bool],
        "sud_order": typing.NotRequired[bool],
        "dsu_order": typing.NotRequired[bool],
        "dus_order": typing.NotRequired[bool],
        "usd_order": typing.NotRequired[bool],
        "uds_order": typing.NotRequired[bool],
        "supper_s_matrix": typing.NotRequired[bool],
        "slower_s_matrix": typing.NotRequired[bool],
        "ashift": typing.NotRequired[bool],
        "bshift": typing.NotRequired[bool],
    },
)

@dataclasses.dataclass
class V3dWarpDriveOutputs:
    """Output paths produced by the tool."""
    root: OutputPathType
    output_dataset: OutputPathType
    """Warped dataset output"""
    output_summary: OutputPathType | None
    """Summary of calculations"""
    oned_output_file: OutputPathType | None
    """File with warping parameters"""
    matrix_output_file: OutputPathType | None
    """File with transformation matrices"""

def v_3d_warp_drive_params(
    dataset: InputPathType,
    base_dataset: InputPathType,
    prefix: str,
    shift_only: bool = False,
    shift_rotate: bool = False,
    shift_rotate_scale: bool = False,
    affine_general: bool = False,
    bilinear_general: bool = False,
    linear: bool = False,
    cubic: bool = False,
    NN: bool = False,
    quintic: bool = False,
    input_dataset: InputPathType | None = None,
    verbosity_flag: bool = False,
    summary_file: str | None = None,
    max_iterations: int | None = None,
    delta: float | None = None,
    weight: str | None = None,
    convergence_thresh: float | None = None,
    twopass: bool = False,
    final_mode: str | None = None,
    parfix: list[str] | None = None,
    oned_file: InputPathType | None = None,
    float_format: bool = False,
    coarserot_init: bool = False,
    oned_matrix_save: InputPathType | None = None,
    sdu_order: bool = False,
    sud_order: bool = False,
    dsu_order: bool = False,
    dus_order: bool = False,
    usd_order: bool = False,
    uds_order: bool = False,
    supper_s_matrix: bool = False,
    slower_s_matrix: bool = False,
    ashift: bool = False,
    bshift: bool = False,
) -> V3dWarpDrive:
    """
    Build parameters.

    Args:
        dataset: Input dataset
        base_dataset: Load dataset as the base to which the input dataset will be\
            matched. This is a mandatory option.
        prefix: Sets the prefix of the output dataset. If 'NULL', no output dataset\
            is written.
        shift_only: 3 parameters (shifts)
        shift_rotate: 6 parameters (shifts + angles)
        shift_rotate_scale: 9 parameters (shifts + angles + scale factors)
        affine_general: 12 parameters (3 shifts + 3x3 matrix)
        bilinear_general: 39 parameters (3 + 3x3 + 3x3x3). Not implemented and will\
            never be.
        linear: Linear interpolation method
        cubic: Cubic interpolation method
        NN: Nearest neighbor interpolation method [default]
        quintic: Quintic interpolation method
        input_dataset: Specify the input dataset anywhere in the command line\
            option list.
        verbosity_flag: Print out lots of information along the way.
        summary_file: Save summary of calculations into text file. If value is '-',\
            summary goes to stdout.
        max_iterations: Allow up to 'm' iterations for convergence.
        delta: Distance, in voxel size, used to compute image derivatives using\
            finite differences. [Default=1.0]
        weight: Set the weighting applied to each voxel proportional to the brick\
            specified here. [Default=computed by program from base]
        convergence_thresh: Set the convergence parameter to be RMS 't' voxels\
            movement between iterations. [Default=0.03]
        twopass: Do the parameter estimation in two passes, coarse-but-fast first,\
            then fine-but-slow second.
        final_mode: Set the final warp to be interpolated using 'mode'.
        parfix: Fix the n'th parameter of the warp model to the value 'v'. More\
            than one -parfix option can be used.
        oned_file: Write out the warping parameters to this file.
        float_format: Write output dataset in float format, even if input dataset\
            is short or byte.
        coarserot_init: Initialize shift+rotation parameters by a brute force\
            coarse search.
        oned_matrix_save: Save base-to-input transformation matrices in specified\
            file. If the file does not end in '.1D', the program will append\
            '.aff12.1D'.
        sdu_order: Set the order of the matrix multiplication for the affine\
            transformations (S=triangular shear, D=diagonal scaling matrix,\
            U=rotation matrix).
        sud_order: Set the order of the matrix multiplication for the affine\
            transformations (S=triangular shear, U=rotation matrix, D=diagonal\
            scaling matrix).
        dsu_order: Set the order of the matrix multiplication for the affine\
            transformations (D=diagonal scaling matrix, S=triangular shear,\
            U=rotation matrix).
        dus_order: Set the order of the matrix multiplication for the affine\
            transformations (D=diagonal scaling matrix, U=rotation matrix,\
            S=triangular shear).
        usd_order: Set the order of the matrix multiplication for the affine\
            transformations (U=rotation matrix, S=triangular shear, D=diagonal\
            scaling matrix).
        uds_order: Set the order of the matrix multiplication for the affine\
            transformations (U=rotation matrix, D=diagonal scaling matrix,\
            S=triangular shear).
        supper_s_matrix: Set the S matrix to be upper triangular.
        slower_s_matrix: Set the S matrix to be lower triangular.
        ashift: Apply the shift parameters after the matrix transformation.
        bshift: Apply the shift parameters before the matrix transformation.

    Returns:
        Parameter dictionary.
    """
    params: V3dWarpDrive = {
        "@type": "afni/3dWarpDrive",
        "dataset": dataset,
        "base_dataset": base_dataset,
        "prefix": prefix,
        "shift_only": shift_only,
        "shift_rotate": shift_rotate,
        "shift_rotate_scale": shift_rotate_scale,
        "affine_general": affine_general,
        "bilinear_general": bilinear_general,
        "linear": linear,
        "cubic": cubic,
        "NN": NN,
        "quintic": quintic,
        "verbosity_flag": verbosity_flag,
        "twopass": twopass,
        "float_format": float_format,
        "coarserot_init": coarserot_init,
        "sdu_order": sdu_order,
        "sud_order": sud_order,
        "dsu_order": dsu_order,
        "dus_order": dus_order,
        "usd_order": usd_order,
        "uds_order": uds_order,
        "supper_s_matrix": supper_s_matrix,
        "slower_s_matrix": slower_s_matrix,
        "ashift": ashift,
        "bshift": bshift,
    }
    if input_dataset is not None:
        params["input_dataset"] = input_dataset
    if summary_file is not None:
        params["summary_file"] = summary_file
    if max_iterations is not None:
        params["max_iterations"] = max_iterations
    if delta is not None:
        params["delta"] = delta
    if weight is not None:
        params["weight"] = weight
    if convergence_thresh is not None:
        params["convergence_thresh"] = convergence_thresh
    if final_mode is not None:
        params["final_mode"] = final_mode
    if parfix is not None:
        params["parfix"] = parfix
    if oned_file is not None:
        params["oned_file"] = oned_file
    if oned_matrix_save is not None:
        params["oned_matrix_save"] = oned_matrix_save
    return params

def v_3d_warp_drive_validate(params: typing.Any) -> None:
    """Validate untrusted parameters. Raises StyxValidationError if `params` is not a valid V3dWarpDrive."""
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("dataset", None) is None:
        raise StyxValidationError("`dataset` must not be None")
    if not isinstance(params["dataset"], (pathlib.Path, str)):
        raise StyxValidationError(f'`dataset` has the wrong type: Received `{type(params["dataset"])}` expected `InputPathType`')
    if params.get("base_dataset", None) is None:
        raise StyxValidationError("`base_dataset` must not be None")
    if not isinstance(params["base_dataset"], (pathlib.Path, str)):
        raise StyxValidationError(f'`base_dataset` has the wrong type: Received `{type(params["base_dataset"])}` expected `InputPathType`')
    if params.get("prefix", None) is None:
        raise StyxValidationError("`prefix` must not be None")
    if not isinstance(params["prefix"], str):
        raise StyxValidationError(f'`prefix` has the wrong type: Received `{type(params["prefix"])}` expected `str`')
    if params.get("shift_only", None) is not None:
        if not isinstance(params["shift_only"], bool):
            raise StyxValidationError(f'`shift_only` has the wrong type: Received `{type(params["shift_only"])}` expected `bool`')
    if params.get("shift_rotate", None) is not None:
        if not isinstance(params["shift_rotate"], bool):
            raise StyxValidationError(f'`shift_rotate` has the wrong type: Received `{type(params["shift_rotate"])}` expected `bool`')
    if params.get("shift_rotate_scale", None) is not None:
        if not isinstance(params["shift_rotate_scale"], bool):
            raise StyxValidationError(f'`shift_rotate_scale` has the wrong type: Received `{type(params["shift_rotate_scale"])}` expected `bool`')
    if params.get("affine_general", None) is not None:
        if not isinstance(params["affine_general"], bool):
            raise StyxValidationError(f'`affine_general` has the wrong type: Received `{type(params["affine_general"])}` expected `bool`')
    if params.get("bilinear_general", None) is not None:
        if not isinstance(params["bilinear_general"], bool):
            raise StyxValidationError(f'`bilinear_general` has the wrong type: Received `{type(params["bilinear_general"])}` expected `bool`')
    if params.get("linear", None) is not None:
        if not isinstance(params["linear"], bool):
            raise StyxValidationError(f'`linear` has the wrong type: Received `{type(params["linear"])}` expected `bool`')
    if params.get("cubic", None) is not None:
        if not isinstance(params["cubic"], bool):
            raise StyxValidationError(f'`cubic` has the wrong type: Received `{type(params["cubic"])}` expected `bool`')
    if params.get("NN", None) is not None:
        if not isinstance(params["NN"], bool):
            raise StyxValidationError(f'`NN` has the wrong type: Received `{type(params["NN"])}` expected `bool`')
    if params.get("quintic", None) is not None:
        if not isinstance(params["quintic"], bool):
            raise StyxValidationError(f'`quintic` has the wrong type: Received `{type(params["quintic"])}` expected `bool`')
    if params.get("input_dataset", None) is not None:
        if not isinstance(params["input_dataset"], (pathlib.Path, str)):
            raise StyxValidationError(f'`input_dataset` has the wrong type: Received `{type(params["input_dataset"])}` expected `InputPathType`')
    if params.get("verbosity_flag", None) is not None:
        if not isinstance(params["verbosity_flag"], bool):
            raise StyxValidationError(f'`verbosity_flag` has the wrong type: Received `{type(params["verbosity_flag"])}` expected `bool`')
    if params.get("summary_file", None) is not None:
        if not isinstance(params["summary_file"], str):
            raise StyxValidationError(f'`summary_file` has the wrong type: Received `{type(params["summary_file"])}` expected `str`')
    if params.get("max_iterations", None) is not None:
        if not isinstance(params["max_iterations"], int):
            raise StyxValidationError(f'`max_iterations` has the wrong type: Received `{type(params["max_iterations"])}` expected `int`')
    if params.get("delta", None) is not None:
        if not isinstance(params["delta"], (float, int)):
            raise StyxValidationError(f'`delta` has the wrong type: Received `{type(params["delta"])}` expected `float`')
    if params.get("weight", None) is not None:
        if not isinstance(params["weight"], str):
            raise StyxValidationError(f'`weight` has the wrong type: Received `{type(params["weight"])}` expected `str`')
    if params.get("convergence_thresh", None) is not None:
        if not isinstance(params["convergence_thresh"], (float, int)):
            raise StyxValidationError(f'`convergence_thresh` has the wrong type: Received `{type(params["convergence_thresh"])}` expected `float`')
    if params.get("twopass", None) is not None:
        if not isinstance(params["twopass"], bool):
            raise StyxValidationError(f'`twopass` has the wrong type: Received `{type(params["twopass"])}` expected `bool`')
    if params.get("final_mode", None) is not None:
        if not isinstance(params["final_mode"], str):
            raise StyxValidationError(f'`final_mode` has the wrong type: Received `{type(params["final_mode"])}` expected `str`')
    if params.get("parfix", None) is not None:
        if not isinstance(params["parfix"], list):
            raise StyxValidationError(f'`parfix` has the wrong type: Received `{type(params["parfix"])}` expected `list[str]`')
        for e in params["parfix"]:
            if not isinstance(e, str):
                raise StyxValidationError(f'`parfix` has the wrong type: Received `{type(e)}` expected `list[str]`')
    if params.get("oned_file", None) is not None:
        if not isinstance(params["oned_file"], (pathlib.Path, str)):
            raise StyxValidationError(f'`oned_file` has the wrong type: Received `{type(params["oned_file"])}` expected `InputPathType`')
    if params.get("float_format", None) is not None:
        if not isinstance(params["float_format"], bool):
            raise StyxValidationError(f'`float_format` has the wrong type: Received `{type(params["float_format"])}` expected `bool`')
    if params.get("coarserot_init", None) is not None:
        if not isinstance(params["coarserot_init"], bool):
            raise StyxValidationError(f'`coarserot_init` has the wrong type: Received `{type(params["coarserot_init"])}` expected `bool`')
    if params.get("oned_matrix_save", None) is not None:
        if not isinstance(params["oned_matrix_save"], (pathlib.Path, str)):
            raise StyxValidationError(f'`oned_matrix_save` has the wrong type: Received `{type(params["oned_matrix_save"])}` expected `InputPathType`')
    if params.get("sdu_order", None) is not None:
        if not isinstance(params["sdu_order"], bool):
            raise StyxValidationError(f'`sdu_order` has the wrong type: Received `{type(params["sdu_order"])}` expected `bool`')
    if params.get("sud_order", None) is not None:
        if not isinstance(params["sud_order"], bool):
            raise StyxValidationError(f'`sud_order` has the wrong type: Received `{type(params["sud_order"])}` expected `bool`')
    if params.get("dsu_order", None) is not None:
        if not isinstance(params["dsu_order"], bool):
            raise StyxValidationError(f'`dsu_order` has the wrong type: Received `{type(params["dsu_order"])}` expected `bool`')
    if params.get("dus_order", None) is not None:
        if not isinstance(params["dus_order"], bool):
            raise StyxValidationError(f'`dus_order` has the wrong type: Received `{type(params["dus_order"])}` expected `bool`')
    if params.get("usd_order", None) is not None:
        if not isinstance(params["usd_order"], bool):
            raise StyxValidationError(f'`usd_order` has the wrong type: Received `{type(params["usd_order"])}` expected `bool`')
    if params.get("uds_order", None) is not None:
        if not isinstance(params["uds_order"], bool):
            raise StyxValidationError(f'`uds_order` has the wrong type: Received `{type(params["uds_order"])}` expected `bool`')
    if params.get("supper_s_matrix", None) is not None:
        if not isinstance(params["supper_s_matrix"], bool):
            raise StyxValidationError(f'`supper_s_matrix` has the wrong type: Received `{type(params["supper_s_matrix"])}` expected `bool`')
    if params.get("slower_s_matrix", None) is not None:
        if not isinstance(params["slower_s_matrix"], bool):
            raise StyxValidationError(f'`slower_s_matrix` has the wrong type: Received `{type(params["slower_s_matrix"])}` expected `bool`')
    if params.get("ashift", None) is not None:
        if not isinstance(params["ashift"], bool):
            raise StyxValidationError(f'`ashift` has the wrong type: Received `{type(params["ashift"])}` expected `bool`')
    if params.get("bshift", None) is not None:
        if not isinstance(params["bshift"], bool):
            raise StyxValidationError(f'`bshift` has the wrong type: Received `{type(params["bshift"])}` expected `bool`')

def v_3d_warp_drive_cargs(params: V3dWarpDrive, execution: Execution) -> list[str]:
    """Build command-line arguments from parameters."""
    cargs: list[str] = []
    cargs.append("3dWarpDrive")
    cargs.append(execution.input_file(params["dataset"]))
    cargs.append("-base")
    cargs.append(execution.input_file(params["base_dataset"]))
    cargs.append("-prefix")
    cargs.append(params["prefix"])
    if params.get("shift_only"):
        cargs.append("-shift_only")
    if params.get("shift_rotate"):
        cargs.append("-shift_rotate")
    if params.get("shift_rotate_scale"):
        cargs.append("-shift_rotate_scale")
    if params.get("affine_general"):
        cargs.append("-affine_general")
    if params.get("bilinear_general"):
        cargs.append("-bilinear_general")
    if params.get("linear"):
        cargs.append("-linear")
    if params.get("cubic"):
        cargs.append("-cubic")
    if params.get("NN"):
        cargs.append("-NN")
    if params.get("quintic"):
        cargs.append("-quintic")
    v_0 = params.get("input_dataset")
    if v_0 is not None:
        cargs.append("-input")
        cargs.append(execution.input_file(v_0))
    if params.get("verbosity_flag"):
        cargs.append("-verb")
    v_1 = params.get("summary_file")
    if v_1 is not None:
        cargs.append("-summ")
        cargs.append(v_1)
    v_2 = params.get("max_iterations")
    if v_2 is not None:
        cargs.append("-maxite")
        cargs.append(str(v_2))
    v_3 = params.get("delta")
    if v_3 is not None:
        cargs.append("-delta")
        cargs.append(str(v_3))
    v_4 = params.get("weight")
    if v_4 is not None:
        cargs.append("-weight")
        cargs.append(v_4)
    v_5 = params.get("convergence_thresh")
    if v_5 is not None:
        cargs.append("-thresh")
        cargs.append(str(v_5))
    if params.get("twopass"):
        cargs.append("-twopass")
    v_6 = params.get("final_mode")
    if v_6 is not None:
        cargs.append("-final")
        cargs.append(v_6)
    v_7 = params.get("parfix")
    if v_7 is not None:
        cargs.append("-parfix")
        for item0 in v_7:
            cargs.append(item0)
    v_8 = params.get("oned_file")
    if v_8 is not None:
        cargs.append("-1Dfile")
        cargs.append(execution.input_file(v_8))
    if params.get("float_format"):
        cargs.append("-float")
    if params.get("coarserot_init"):
        cargs.append("-coarserot")
    v_9 = params.get("oned_matrix_save")
    if v_9 is not None:
        cargs.append("-1Dmatrix_save")
        cargs.append(execution.input_file(v_9))
    if params.get("sdu_order"):
        cargs.append("-SDU")
    if params.get("sud_order"):
        cargs.append("-SUD")
    if params.get("dsu_order"):
        cargs.append("-DSU")
    if params.get("dus_order"):
        cargs.append("-DUS")
    if params.get("usd_order"):
        cargs.append("-USD")
    if params.get("uds_order"):
        cargs.append("-UDS")
    if params.get("supper_s_matrix"):
        cargs.append("-Supper")
    if params.get("slower_s_matrix"):
        cargs.append("-Slower")
    if params.get("ashift"):
        cargs.append("-ashift")
    if params.get("bshift"):
        cargs.append("-bshift")
    return cargs

def v_3d_warp_drive_outputs(params: V3dWarpDrive, execution: Execution) -> V3dWarpDriveOutputs:
    """Build the V3dWarpDriveOutputs object for this tool."""
    output_summary_v: OutputPathType | None = None
    oned_output_file_v: OutputPathType | None = None
    matrix_output_file_v: OutputPathType | None = None
    root_v: OutputPathType = execution.output_file(".")
    output_dataset_v: OutputPathType = execution.output_file(f'{params["prefix"]}+orig')
    __v0 = params.get("summary_file")
    if __v0 is not None:
        output_summary_v = execution.output_file((__v0 if __v0 is not None else ""))
    __v1 = params.get("oned_file")
    if __v1 is not None:
        oned_output_file_v = execution.output_file((__v1 if __v1 is not None else ""))
    __v2 = params.get("oned_matrix_save")
    if __v2 is not None:
        matrix_output_file_v = execution.output_file((__v2 if __v2 is not None else ""))
    return V3dWarpDriveOutputs(
        root=root_v,
        output_dataset=output_dataset_v,
        output_summary=output_summary_v,
        oned_output_file=oned_output_file_v,
        matrix_output_file=matrix_output_file_v,
    )

def v_3d_warp_drive_execute(params: V3dWarpDrive, runner: Runner | None = None) -> V3dWarpDriveOutputs:
    """
    3dWarpDrive

    Warp a dataset to match another one (the base) using an affine transformation.

    Author: AFNI Developers

    URL: https://afni.nimh.nih.gov/

    Args:
        params: The parameters.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    v_3d_warp_drive_validate(params)
    runner = runner if runner is not None else get_global_runner()
    execution = runner.start_execution(V_3D_WARP_DRIVE_METADATA)
    execution.params(params)
    args = v_3d_warp_drive_cargs(params, execution)
    out = v_3d_warp_drive_outputs(params, execution)
    execution.run(args)
    return out

def v_3d_warp_drive(
    dataset: InputPathType,
    base_dataset: InputPathType,
    prefix: str,
    shift_only: bool = False,
    shift_rotate: bool = False,
    shift_rotate_scale: bool = False,
    affine_general: bool = False,
    bilinear_general: bool = False,
    linear: bool = False,
    cubic: bool = False,
    NN: bool = False,
    quintic: bool = False,
    input_dataset: InputPathType | None = None,
    verbosity_flag: bool = False,
    summary_file: str | None = None,
    max_iterations: int | None = None,
    delta: float | None = None,
    weight: str | None = None,
    convergence_thresh: float | None = None,
    twopass: bool = False,
    final_mode: str | None = None,
    parfix: list[str] | None = None,
    oned_file: InputPathType | None = None,
    float_format: bool = False,
    coarserot_init: bool = False,
    oned_matrix_save: InputPathType | None = None,
    sdu_order: bool = False,
    sud_order: bool = False,
    dsu_order: bool = False,
    dus_order: bool = False,
    usd_order: bool = False,
    uds_order: bool = False,
    supper_s_matrix: bool = False,
    slower_s_matrix: bool = False,
    ashift: bool = False,
    bshift: bool = False,
    runner: Runner | None = None,
) -> V3dWarpDriveOutputs:
    """
    3dWarpDrive

    Warp a dataset to match another one (the base) using an affine transformation.

    Author: AFNI Developers

    URL: https://afni.nimh.nih.gov/

    Args:
        dataset: Input dataset
        base_dataset: Load dataset as the base to which the input dataset will be\
            matched. This is a mandatory option.
        prefix: Sets the prefix of the output dataset. If 'NULL', no output dataset\
            is written.
        shift_only: 3 parameters (shifts)
        shift_rotate: 6 parameters (shifts + angles)
        shift_rotate_scale: 9 parameters (shifts + angles + scale factors)
        affine_general: 12 parameters (3 shifts + 3x3 matrix)
        bilinear_general: 39 parameters (3 + 3x3 + 3x3x3). Not implemented and will\
            never be.
        linear: Linear interpolation method
        cubic: Cubic interpolation method
        NN: Nearest neighbor interpolation method [default]
        quintic: Quintic interpolation method
        input_dataset: Specify the input dataset anywhere in the command line\
            option list.
        verbosity_flag: Print out lots of information along the way.
        summary_file: Save summary of calculations into text file. If value is '-',\
            summary goes to stdout.
        max_iterations: Allow up to 'm' iterations for convergence.
        delta: Distance, in voxel size, used to compute image derivatives using\
            finite differences. [Default=1.0]
        weight: Set the weighting applied to each voxel proportional to the brick\
            specified here. [Default=computed by program from base]
        convergence_thresh: Set the convergence parameter to be RMS 't' voxels\
            movement between iterations. [Default=0.03]
        twopass: Do the parameter estimation in two passes, coarse-but-fast first,\
            then fine-but-slow second.
        final_mode: Set the final warp to be interpolated using 'mode'.
        parfix: Fix the n'th parameter of the warp model to the value 'v'. More\
            than one -parfix option can be used.
        oned_file: Write out the warping parameters to this file.
        float_format: Write output dataset in float format, even if input dataset\
            is short or byte.
        coarserot_init: Initialize shift+rotation parameters by a brute force\
            coarse search.
        oned_matrix_save: Save base-to-input transformation matrices in specified\
            file. If the file does not end in '.1D', the program will append\
            '.aff12.1D'.
        sdu_order: Set the order of the matrix multiplication for the affine\
            transformations (S=triangular shear, D=diagonal scaling matrix,\
            U=rotation matrix).
        sud_order: Set the order of the matrix multiplication for the affine\
            transformations (S=triangular shear, U=rotation matrix, D=diagonal\
            scaling matrix).
        dsu_order: Set the order of the matrix multiplication for the affine\
            transformations (D=diagonal scaling matrix, S=triangular shear,\
            U=rotation matrix).
        dus_order: Set the order of the matrix multiplication for the affine\
            transformations (D=diagonal scaling matrix, U=rotation matrix,\
            S=triangular shear).
        usd_order: Set the order of the matrix multiplication for the affine\
            transformations (U=rotation matrix, S=triangular shear, D=diagonal\
            scaling matrix).
        uds_order: Set the order of the matrix multiplication for the affine\
            transformations (U=rotation matrix, D=diagonal scaling matrix,\
            S=triangular shear).
        supper_s_matrix: Set the S matrix to be upper triangular.
        slower_s_matrix: Set the S matrix to be lower triangular.
        ashift: Apply the shift parameters after the matrix transformation.
        bshift: Apply the shift parameters before the matrix transformation.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    params = v_3d_warp_drive_params(
        dataset=dataset,
        base_dataset=base_dataset,
        prefix=prefix,
        shift_only=shift_only,
        shift_rotate=shift_rotate,
        shift_rotate_scale=shift_rotate_scale,
        affine_general=affine_general,
        bilinear_general=bilinear_general,
        linear=linear,
        cubic=cubic,
        NN=NN,
        quintic=quintic,
        input_dataset=input_dataset,
        verbosity_flag=verbosity_flag,
        summary_file=summary_file,
        max_iterations=max_iterations,
        delta=delta,
        weight=weight,
        convergence_thresh=convergence_thresh,
        twopass=twopass,
        final_mode=final_mode,
        parfix=parfix,
        oned_file=oned_file,
        float_format=float_format,
        coarserot_init=coarserot_init,
        oned_matrix_save=oned_matrix_save,
        sdu_order=sdu_order,
        sud_order=sud_order,
        dsu_order=dsu_order,
        dus_order=dus_order,
        usd_order=usd_order,
        uds_order=uds_order,
        supper_s_matrix=supper_s_matrix,
        slower_s_matrix=slower_s_matrix,
        ashift=ashift,
        bshift=bshift,
    )
    return v_3d_warp_drive_execute(params, runner)

__all__ = [
    "V3dWarpDrive",
    "V3dWarpDriveOutputs",
    "V_3D_WARP_DRIVE_METADATA",
    "v_3d_warp_drive_cargs",
    "v_3d_warp_drive_outputs",
    "v_3d_warp_drive_params",
    "v_3d_warp_drive_execute",
    "v_3d_warp_drive_validate",
    "v_3d_warp_drive",
]