# This file was auto generated by Styx.
# Do not edit this file directly.

import dataclasses
import pathlib
import typing

from styxdefs import Execution, InputPathType, Metadata, Runner, StyxValidationError, OutputPathType, get_global_runner

V_3D_X_CLUST_SIM_METADATA = Metadata(
    id="3dXClustSim",
    name="3dXClustSim",
    package="afni",
)

V3dXClustSim = typing.TypedDict(
    "V3dXClustSim",
    {
        "@type": typing.NotRequired[typing.Literal["afni/3dXClustSim"]],
        "inset": InputPathType,
        "insdat": typing.NotRequired[InputPathType],
        "nn": typing.NotRequired[float],
        "sid": typing.NotRequired[float],
        "hpow": typing.NotRequired[list[float]],
        "ncase": typing.NotRequired[list[str]],
        "pthr": typing.NotRequired[list[float]],
        "fpr": typing.NotRequired[float],
        "multiFPR": typing.NotRequired[bool],
        "minclust": typing.NotRequired[float],
        "local": typing.NotRequired[bool],
        "global": typing.NotRequired[bool],
        "nolocal": typing.NotRequired[bool],
        "noglobal": typing.NotRequired[bool],
        "splitfrac": typing.NotRequired[float],
        "prefix": typing.NotRequired[str],
        "verbose": typing.NotRequired[bool],
        "quiet": typing.NotRequired[bool],
    },
)

@dataclasses.dataclass
class V3dXClustSimOutputs:
    """Output paths produced by the tool."""
    root: OutputPathType

def v_3d_x_clust_sim_params(
    inset: InputPathType,
    insdat: InputPathType | None = None,
    nn: float | None = None,
    sid: float | None = None,
    hpow: list[float] | None = None,
    ncase: list[str] | None = None,
    pthr: list[float] | None = None,
    fpr: float | None = None,
    multiFPR: bool = False,
    minclust: float | None = None,
    local: bool = False,
    global_: bool = False,
    nolocal: bool = False,
    noglobal: bool = False,
    splitfrac: float | None = None,
    prefix: str | None = None,
    verbose: bool = False,
    quiet: bool = False,
) -> V3dXClustSim:
    """
    Build parameters.

    Args:
        inset: Mask sdata file (from 3dtoXdataset or 3dttest++)
        insdat: Data files in the '.sdat' format.
        nn: Neighborhood connectivity (1, 2, or 3). Default is 2.
        sid: Sidedness: 1 (one-sided) or 2 (two-sided). Default is 2.
        hpow: H power values (can be a subset of 0, 1, 2). Default is 2.
        ncase: Number of cases with labels. Default is 1 A.
        pthr: List of p-value thresholds. Default is 0.0100 0.0056 0.0031 0.0018\
            0.0010.
        fpr: Set global FPR goal to an integer ff between 2 and 9. Default is 5.
        multiFPR: Compute results for multiple FPR goals (2%, 3%, ... 9%).
        minclust: Minimum cluster size in voxels. Default is 5.
        local: Do voxel-wise (local) ETAC computations.
        global_: Do volume-wise (global) ETAC computations.
        nolocal: Do not perform voxel-wise ETAC computations.
        noglobal: Do not perform volume-wise ETAC computations.
        splitfrac: Fraction to split simulations into pieces (0.2 < F < 0.8).
        prefix: Output filename prefix.
        verbose: Be more verbose.
        quiet: Silent mode.

    Returns:
        Parameter dictionary.
    """
    params: V3dXClustSim = {
        "@type": "afni/3dXClustSim",
        "inset": inset,
        "multiFPR": multiFPR,
        "local": local,
        "global": global_,
        "nolocal": nolocal,
        "noglobal": noglobal,
        "verbose": verbose,
        "quiet": quiet,
    }
    if insdat is not None:
        params["insdat"] = insdat
    if nn is not None:
        params["nn"] = nn
    if sid is not None:
        params["sid"] = sid
    if hpow is not None:
        params["hpow"] = hpow
    if ncase is not None:
        params["ncase"] = ncase
    if pthr is not None:
        params["pthr"] = pthr
    if fpr is not None:
        params["fpr"] = fpr
    if minclust is not None:
        params["minclust"] = minclust
    if splitfrac is not None:
        params["splitfrac"] = splitfrac
    if prefix is not None:
        params["prefix"] = prefix
    return params

def v_3d_x_clust_sim_validate(params: typing.Any) -> None:
    """Validate untrusted parameters. Raises StyxValidationError if `params` is not a valid V3dXClustSim."""
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("inset", None) is None:
        raise StyxValidationError("`inset` must not be None")
    if not isinstance(params["inset"], (pathlib.Path, str)):
        raise StyxValidationError(f'`inset` has the wrong type: Received `{type(params["inset"])}` expected `InputPathType`')
    if params.get("insdat", None) is not None:
        if not isinstance(params["insdat"], (pathlib.Path, str)):
            raise StyxValidationError(f'`insdat` has the wrong type: Received `{type(params["insdat"])}` expected `InputPathType`')
    if params.get("nn", None) is not None:
        if not isinstance(params["nn"], (float, int)):
            raise StyxValidationError(f'`nn` has the wrong type: Received `{type(params["nn"])}` expected `float`')
    if params.get("sid", None) is not None:
        if not isinstance(params["sid"], (float, int)):
            raise StyxValidationError(f'`sid` has the wrong type: Received `{type(params["sid"])}` expected `float`')
    if params.get("hpow", None) is not None:
        if not isinstance(params["hpow"], list):
            raise StyxValidationError(f'`hpow` has the wrong type: Received `{type(params["hpow"])}` expected `list[float]`')
        for e in params["hpow"]:
            if not isinstance(e, (float, int)):
                raise StyxValidationError(f'`hpow` has the wrong type: Received `{type(e)}` expected `list[float]`')
    if params.get("ncase", None) is not None:
        if not isinstance(params["ncase"], list):
            raise StyxValidationError(f'`ncase` has the wrong type: Received `{type(params["ncase"])}` expected `list[str]`')
        for e_2 in params["ncase"]:
            if not isinstance(e_2, str):
                raise StyxValidationError(f'`ncase` has the wrong type: Received `{type(e_2)}` expected `list[str]`')
    if params.get("pthr", None) is not None:
        if not isinstance(params["pthr"], list):
            raise StyxValidationError(f'`pthr` has the wrong type: Received `{type(params["pthr"])}` expected `list[float]`')
        for e_3 in params["pthr"]:
            if not isinstance(e_3, (float, int)):
                raise StyxValidationError(f'`pthr` has the wrong type: Received `{type(e_3)}` expected `list[float]`')
    if params.get("fpr", None) is not None:
        if not isinstance(params["fpr"], (float, int)):
            raise StyxValidationError(f'`fpr` has the wrong type: Received `{type(params["fpr"])}` expected `float`')
        if not (2 <= params["fpr"] <= 9):
            raise StyxValidationError("Parameter `fpr` must be between 2 and 9 (inclusive)")
    if params.get("multiFPR", None) is not None:
        if not isinstance(params["multiFPR"], bool):
            raise StyxValidationError(f'`multiFPR` has the wrong type: Received `{type(params["multiFPR"])}` expected `bool`')
    if params.get("minclust", None) is not None:
        if not isinstance(params["minclust"], (float, int)):
            raise StyxValidationError(f'`minclust` has the wrong type: Received `{type(params["minclust"])}` expected `float`')
    if params.get("local", None) is not None:
        if not isinstance(params["local"], bool):
            raise StyxValidationError(f'`local` has the wrong type: Received `{type(params["local"])}` expected `bool`')
    if params.get("global", None) is not None:
        if not isinstance(params["global"], bool):
            raise StyxValidationError(f'`global` has the wrong type: Received `{type(params["global"])}` expected `bool`')
    if params.get("nolocal", None) is not None:
        if not isinstance(params["nolocal"], bool):
            raise StyxValidationError(f'`nolocal` has the wrong type: Received `{type(params["nolocal"])}` expected `bool`')
    if params.get("noglobal", None) is not None:
        if not isinstance(params["noglobal"], bool):
            raise StyxValidationError(f'`noglobal` has the wrong type: Received `{type(params["noglobal"])}` expected `bool`')
    if params.get("splitfrac", None) is not None:
        if not isinstance(params["splitfrac"], (float, int)):
            raise StyxValidationError(f'`splitfrac` has the wrong type: Received `{type(params["splitfrac"])}` expected `float`')
        if not (0.2 <= params["splitfrac"] <= 0.8):
            raise StyxValidationError("Parameter `splitfrac` must be between 0.2 and 0.8 (inclusive)")
    if params.get("prefix", None) is not None:
        if not isinstance(params["prefix"], str):
            raise StyxValidationError(f'`prefix` has the wrong type: Received `{type(params["prefix"])}` expected `str`')
    if params.get("verbose", None) is not None:
        if not isinstance(params["verbose"], bool):
            raise StyxValidationError(f'`verbose` has the wrong type: Received `{type(params["verbose"])}` expected `bool`')
    if params.get("quiet", None) is not None:
        if not isinstance(params["quiet"], bool):
            raise StyxValidationError(f'`quiet` has the wrong type: Received `{type(params["quiet"])}` expected `bool`')

def v_3d_x_clust_sim_cargs(params: V3dXClustSim, execution: Execution) -> list[str]:
    """Build command-line arguments from parameters."""
    cargs: list[str] = []
    cargs.append("3dXClustSim")
    cargs.append(execution.input_file(params["inset"]))
    v_0 = params.get("insdat")
    if v_0 is not None:
        cargs.append(execution.input_file(v_0))
    v_1 = params.get("nn")
    if v_1 is not None:
        cargs.append("-NN")
        cargs.append(str(v_1))
    v_2 = params.get("sid")
    if v_2 is not None:
        cargs.append("-sid")
        cargs.append(str(v_2))
    v_3 = params.get("hpow")
    if v_3 is not None:
        cargs.append("-hpow")
        for item0 in v_3:
            cargs.append(str(item0))
    v_4 = params.get("ncase")
    if v_4 is not None:
        cargs.append("-ncase")
        for item1 in v_4:
            cargs.append(item1)
    v_5 = params.get("pthr")
    if v_5 is not None:
        cargs.append("-pthr")
        for item2 in v_5:
            cargs.append(str(item2))
    v_6 = params.get("fpr")
    if v_6 is not None:
        cargs.append("-FPR")
        cargs.append(str(v_6))
    if params.get("multiFPR"):
        cargs.append("-multiFPR")
    v_7 = params.get("minclust")
    if v_7 is not None:
        cargs.append("-minclust")
        cargs.append(str(v_7))
    if params.get("local"):
        cargs.append("-local")
    if params.get("global"):
        cargs.append("-global")
    if params.get("nolocal"):
        cargs.append("-nolocal")
    if params.get("noglobal"):
        cargs.append("-noglobal")
    v_8 = params.get("splitfrac")
    if v_8 is not None:
        cargs.append("-splitfrac")
        cargs.append(str(v_8))
    v_9 = params.get("prefix")
    if v_9 is not None:
        cargs.append("-prefix")
        cargs.append(v_9)
    if params.get("verbose"):
        cargs.append("-verb")
    if params.get("quiet"):
        cargs.append("-quiet")
    return cargs

def v_3d_x_clust_sim_outputs(params: V3dXClustSim, execution: Execution) -> V3dXClustSimOutputs:
    """Build the V3dXClustSimOutputs object for this tool."""
    root_v: OutputPathType = execution.output_file(".")
    return V3dXClustSimOutputs(
        root=root_v,
    )

def v_3d_x_clust_sim_execute(params: V3dXClustSim, runner: Runner | None = None) -> V3dXClustSimOutputs:
    """
    3dXClustSim

    ETAC processing tool to find cluster figure of merit (FOM) thresholds.

    Author: AFNI Developers

    URL: https://afni.nimh.nih.gov/

    Args:
        params: The parameters.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    v_3d_x_clust_sim_validate(params)
    runner = runner if runner is not None else get_global_runner()
    execution = runner.start_execution(V_3D_X_CLUST_SIM_METADATA)
    execution.params(params)
    args = v_3d_x_clust_sim_cargs(params, execution)
    out = v_3d_x_clust_sim_outputs(params, execution)
    execution.run(args)
    return out

def v_3d_x_clust_sim(
    inset: InputPathType,
    insdat: InputPathType | None = None,
    nn: float | None = None,
    sid: float | None = None,
    hpow: list[float] | None = None,
    ncase: list[str] | None = None,
    pthr: list[float] | None = None,
    fpr: float | None = None,
    multiFPR: bool = False,
    minclust: float | None = None,
    local: bool = False,
    global_: bool = False,
    nolocal: bool = False,
    noglobal: bool = False,
    splitfrac: float | None = None,
    prefix: str | None = None,
    verbose: bool = False,
    quiet: bool = False,
    runner: Runner | None = None,
) -> V3dXClustSimOutputs:
    """
    3dXClustSim

    ETAC processing tool to find cluster figure of merit (FOM) thresholds.

    Author: AFNI Developers

    URL: https://afni.nimh.nih.gov/

    Args:
        inset: Mask sdata file (from 3dtoXdataset or 3dttest++)
        insdat: Data files in the '.sdat' format.
        nn: Neighborhood connectivity (1, 2, or 3). Default is 2.
        sid: Sidedness: 1 (one-sided) or 2 (two-sided). Default is 2.
        hpow: H power values (can be a subset of 0, 1, 2). Default is 2.
        ncase: Number of cases with labels. Default is 1 A.
        pthr: List of p-value thresholds. Default is 0.0100 0.0056 0.0031 0.0018\
            0.0010.
        fpr: Set global FPR goal to an integer ff between 2 and 9. Default is 5.
        multiFPR: Compute results for multiple FPR goals (2%, 3%, ... 9%).
        minclust: Minimum cluster size in voxels. Default is 5.
        local: Do voxel-wise (local) ETAC computations.
        global_: Do volume-wise (global) ETAC computations.
        nolocal: Do not perform voxel-wise ETAC computations.
        noglobal: Do not perform volume-wise ETAC computations.
        splitfrac: Fraction to split simulations into pieces (0.2 < F < 0.8).
        prefix: Output filename prefix.
        verbose: Be more verbose.
        quiet: Silent mode.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    params = v_3d_x_clust_sim_params(
        inset=inset,
        insdat=insdat,
        nn=nn,
        sid=sid,
        hpow=hpow,
        ncase=ncase,
        pthr=pthr,
        fpr=fpr,
        multiFPR=multiFPR,
        minclust=minclust,
        local=local,
        global_=global_,
        nolocal=nolocal,
        noglobal=noglobal,
        splitfrac=splitfrac,
        prefix=prefix,
        verbose=verbose,
        quiet=quiet,
    )
    return v_3d_x_clust_sim_execute(params, runner)

__all__ = [
    "V3dXClustSim",
    "V3dXClustSimOutputs",
    "V_3D_X_CLUST_SIM_METADATA",
    "v_3d_x_clust_sim_cargs",
    "v_3d_x_clust_sim_outputs",
    "v_3d_x_clust_sim_params",
    "v_3d_x_clust_sim_execute",
    "v_3d_x_clust_sim_validate",
    "v_3d_x_clust_sim",
]