[project]
name = "niwrap_greedy"
version = "0.9.4"
description = "Greedy is a tool for fast deformable registration of 2D and 3D medical images. Developed at the Penn Image Computing and Science Lab (PICSL), it was designed for really fast CPU-based deformable image registration in applications where many images must be registered in parallel, such as multi-atlas segmentation. Greedy borrows concepts from Symmetric Normalization (SyN) in ANTs but uses a non-symmetric approach and highly optimized metric computation code for additional speed."
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "Paul A. Yushkevich" }]
requires-python = ">=3.10"
dependencies = [
  "styxdefs>=0.7.0,<0.8.0",
]

[tool.setuptools]
packages = ["greedy"]
package-dir = { "greedy" = "." }

[tool.setuptools.package-data]
"greedy" = ["py.typed"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
