# This file was auto generated by Styx.
# Do not edit this file directly.

import typing
import pathlib
from styxdefs import *

AFNI_CHECK_OMP_METADATA = Metadata(
    id="902e7955e7e9298e8850ef2d18d6e0b1a5e24ec2.boutiques",
    name="afni_check_omp",
    package="afni",
    container_image_tag="afni/afni_make_build:AFNI_24.2.06",
)


_AfniCheckOmpParamsDictNoTag = typing.TypedDict('_AfniCheckOmpParamsDictNoTag', {
    "iterations": typing.NotRequired[float | None],
})
AfniCheckOmpParamsDictTagged = typing.TypedDict('AfniCheckOmpParamsDictTagged', {
    "@type": typing.Literal["afni/afni_check_omp"],
    "iterations": typing.NotRequired[float | None],
})
AfniCheckOmpParamsDict = _AfniCheckOmpParamsDictNoTag | AfniCheckOmpParamsDictTagged


class AfniCheckOmpOutputs(typing.NamedTuple):
    """
    Output object returned when calling `AfniCheckOmpParamsDict(...)`.
    """
    root: OutputPathType
    """Output root folder. This is the root folder for all outputs."""


def afni_check_omp_params(
    iterations: float | None = None,
) -> AfniCheckOmpParamsDictTagged:
    """
    Build parameters.
    
    Args:
        iterations: Number of iterations to run.
    Returns:
        Parameter dictionary
    """
    params = {
        "@type": "afni/afni_check_omp",
    }
    if iterations is not None:
        params["iterations"] = iterations
    return params


def afni_check_omp_validate(
    params: typing.Any,
) -> None:
    """
    Validate parameters. Throws an error if `params` is not a valid
    `AfniCheckOmpParamsDict` object.
    
    Args:
        params: The parameters object to validate.
    """
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("iterations", None) is not None:
        if not isinstance(params["iterations"], (float, int)):
            raise StyxValidationError(f'`iterations` has the wrong type: Received `{type(params.get("iterations", None))}` expected `float | None`')


def afni_check_omp_cargs(
    params: AfniCheckOmpParamsDict,
    execution: Execution,
) -> list[str]:
    """
    Build command-line arguments from parameters.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Command-line arguments.
    """
    cargs = []
    cargs.append("afni_check_omp")
    if params.get("iterations", None) is not None:
        cargs.append(str(params.get("iterations", None)))
    return cargs


def afni_check_omp_outputs(
    params: AfniCheckOmpParamsDict,
    execution: Execution,
) -> AfniCheckOmpOutputs:
    """
    Build outputs object containing output file paths and possibly stdout/stderr.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Outputs object.
    """
    ret = AfniCheckOmpOutputs(
        root=execution.output_file("."),
    )
    return ret


def afni_check_omp_execute(
    params: AfniCheckOmpParamsDict,
    runner: Runner | None = None,
) -> AfniCheckOmpOutputs:
    """
    afni_check_omp
    
    Tool to check the OpenMP multi-threading environment for AFNI.
    
    Author: AFNI Developers
    
    URL: https://afni.nimh.nih.gov/
    
    Args:
        params: The parameters.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `AfniCheckOmpOutputs`).
    """
    afni_check_omp_validate(params)
    runner = runner or get_global_runner()
    execution = runner.start_execution(AFNI_CHECK_OMP_METADATA)
    params = execution.params(params)
    cargs = afni_check_omp_cargs(params, execution)
    ret = afni_check_omp_outputs(params, execution)
    execution.run(cargs)
    return ret


def afni_check_omp(
    iterations: float | None = None,
    runner: Runner | None = None,
) -> AfniCheckOmpOutputs:
    """
    afni_check_omp
    
    Tool to check the OpenMP multi-threading environment for AFNI.
    
    Author: AFNI Developers
    
    URL: https://afni.nimh.nih.gov/
    
    Args:
        iterations: Number of iterations to run.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `AfniCheckOmpOutputs`).
    """
    params = afni_check_omp_params(
        iterations=iterations,
    )
    return afni_check_omp_execute(params, runner)


__all__ = [
    "AFNI_CHECK_OMP_METADATA",
    "AfniCheckOmpOutputs",
    "AfniCheckOmpParamsDict",
    "AfniCheckOmpParamsDictTagged",
    "afni_check_omp",
    "afni_check_omp_execute",
    "afni_check_omp_params",
]
