# This file was auto generated by Styx.
# Do not edit this file directly.

import typing
import pathlib
from styxdefs import *

V_3DNEWID_METADATA = Metadata(
    id="d9631a81a6ce88bab00129e99a4fffcedf738735.boutiques",
    name="3dnewid",
    package="afni",
    container_image_tag="afni/afni_make_build:AFNI_24.2.06",
)


_V3dnewidParamsDictNoTag = typing.TypedDict('_V3dnewidParamsDictNoTag', {
    "datasets": list[InputPathType],
    "fun": typing.NotRequired[float | None],
    "fun11": bool,
    "int": bool,
    "hash": typing.NotRequired[str | None],
    "MD5": typing.NotRequired[str | None],
})
V3dnewidParamsDictTagged = typing.TypedDict('V3dnewidParamsDictTagged', {
    "@type": typing.Literal["afni/3dnewid"],
    "datasets": list[InputPathType],
    "fun": typing.NotRequired[float | None],
    "fun11": bool,
    "int": bool,
    "hash": typing.NotRequired[str | None],
    "MD5": typing.NotRequired[str | None],
})
V3dnewidParamsDict = _V3dnewidParamsDictNoTag | V3dnewidParamsDictTagged


class V3dnewidOutputs(typing.NamedTuple):
    """
    Output object returned when calling `V3dnewidParamsDict(...)`.
    """
    root: OutputPathType
    """Output root folder. This is the root folder for all outputs."""


def v_3dnewid_params(
    datasets: list[InputPathType],
    fun: float | None = None,
    fun11: bool = False,
    int_: bool = False,
    hash_: str | None = None,
    md5: str | None = None,
) -> V3dnewidParamsDictTagged:
    """
    Build parameters.
    
    Args:
        datasets: Input datasets to assign new ID codes.
        fun: Generate n randomly generated ID codes. If n is not present, 1 ID\
            code is printed.
        fun11: Generate an 11 character ID code for use in scripting.
        int_: Generate a random positive integer between 1 million and 1\
            billion.
        hash_: Generate a unique hash code of the provided string. The same\
            string produces the same hash code.
        md5: Generate the MD5 hash of the provided string. Output should be the\
            same as the -hash output without the prefix and without the + and /\
            char substitutions.
    Returns:
        Parameter dictionary
    """
    params = {
        "@type": "afni/3dnewid",
        "datasets": datasets,
        "fun11": fun11,
        "int": int_,
    }
    if fun is not None:
        params["fun"] = fun
    if hash_ is not None:
        params["hash"] = hash_
    if md5 is not None:
        params["MD5"] = md5
    return params


def v_3dnewid_validate(
    params: typing.Any,
) -> None:
    """
    Validate parameters. Throws an error if `params` is not a valid
    `V3dnewidParamsDict` object.
    
    Args:
        params: The parameters object to validate.
    """
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("datasets", None) is None:
        raise StyxValidationError("`datasets` must not be None")
    if not isinstance(params["datasets"], list):
        raise StyxValidationError(f'`datasets` has the wrong type: Received `{type(params.get("datasets", None))}` expected `list[InputPathType]`')
    for e in params["datasets"]:
        if not isinstance(e, (pathlib.Path, str)):
            raise StyxValidationError(f'`datasets` has the wrong type: Received `{type(params.get("datasets", None))}` expected `list[InputPathType]`')
    if params.get("fun", None) is not None:
        if not isinstance(params["fun"], (float, int)):
            raise StyxValidationError(f'`fun` has the wrong type: Received `{type(params.get("fun", None))}` expected `float | None`')
    if params.get("fun11", False) is None:
        raise StyxValidationError("`fun11` must not be None")
    if not isinstance(params["fun11"], bool):
        raise StyxValidationError(f'`fun11` has the wrong type: Received `{type(params.get("fun11", False))}` expected `bool`')
    if params.get("int", False) is None:
        raise StyxValidationError("`int` must not be None")
    if not isinstance(params["int"], bool):
        raise StyxValidationError(f'`int` has the wrong type: Received `{type(params.get("int", False))}` expected `bool`')
    if params.get("hash", None) is not None:
        if not isinstance(params["hash"], str):
            raise StyxValidationError(f'`hash` has the wrong type: Received `{type(params.get("hash", None))}` expected `str | None`')
    if params.get("MD5", None) is not None:
        if not isinstance(params["MD5"], str):
            raise StyxValidationError(f'`MD5` has the wrong type: Received `{type(params.get("MD5", None))}` expected `str | None`')


def v_3dnewid_cargs(
    params: V3dnewidParamsDict,
    execution: Execution,
) -> list[str]:
    """
    Build command-line arguments from parameters.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Command-line arguments.
    """
    cargs = []
    cargs.append("3dnewid")
    cargs.extend([execution.input_file(f) for f in params.get("datasets", None)])
    if params.get("fun", None) is not None:
        cargs.extend([
            "-fun",
            str(params.get("fun", None))
        ])
    if params.get("fun11", False):
        cargs.append("-fun11")
    if params.get("int", False):
        cargs.append("-int")
    if params.get("hash", None) is not None:
        cargs.extend([
            "-hash",
            params.get("hash", None)
        ])
    if params.get("MD5", None) is not None:
        cargs.extend([
            "-MD5",
            params.get("MD5", None)
        ])
    return cargs


def v_3dnewid_outputs(
    params: V3dnewidParamsDict,
    execution: Execution,
) -> V3dnewidOutputs:
    """
    Build outputs object containing output file paths and possibly stdout/stderr.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Outputs object.
    """
    ret = V3dnewidOutputs(
        root=execution.output_file("."),
    )
    return ret


def v_3dnewid_execute(
    params: V3dnewidParamsDict,
    runner: Runner | None = None,
) -> V3dnewidOutputs:
    """
    3dnewid
    
    Assigns a new ID code to a dataset, ensuring internal ID codes remain
    unique.
    
    Author: AFNI Developers
    
    URL: https://afni.nimh.nih.gov/
    
    Args:
        params: The parameters.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `V3dnewidOutputs`).
    """
    v_3dnewid_validate(params)
    runner = runner or get_global_runner()
    execution = runner.start_execution(V_3DNEWID_METADATA)
    params = execution.params(params)
    cargs = v_3dnewid_cargs(params, execution)
    ret = v_3dnewid_outputs(params, execution)
    execution.run(cargs)
    return ret


def v_3dnewid(
    datasets: list[InputPathType],
    fun: float | None = None,
    fun11: bool = False,
    int_: bool = False,
    hash_: str | None = None,
    md5: str | None = None,
    runner: Runner | None = None,
) -> V3dnewidOutputs:
    """
    3dnewid
    
    Assigns a new ID code to a dataset, ensuring internal ID codes remain
    unique.
    
    Author: AFNI Developers
    
    URL: https://afni.nimh.nih.gov/
    
    Args:
        datasets: Input datasets to assign new ID codes.
        fun: Generate n randomly generated ID codes. If n is not present, 1 ID\
            code is printed.
        fun11: Generate an 11 character ID code for use in scripting.
        int_: Generate a random positive integer between 1 million and 1\
            billion.
        hash_: Generate a unique hash code of the provided string. The same\
            string produces the same hash code.
        md5: Generate the MD5 hash of the provided string. Output should be the\
            same as the -hash output without the prefix and without the + and /\
            char substitutions.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `V3dnewidOutputs`).
    """
    params = v_3dnewid_params(
        datasets=datasets,
        fun=fun,
        fun11=fun11,
        int_=int_,
        hash_=hash_,
        md5=md5,
    )
    return v_3dnewid_execute(params, runner)


__all__ = [
    "V3dnewidOutputs",
    "V3dnewidParamsDict",
    "V3dnewidParamsDictTagged",
    "V_3DNEWID_METADATA",
    "v_3dnewid",
    "v_3dnewid_execute",
    "v_3dnewid_params",
]
