# This file was auto generated by Styx.
# Do not edit this file directly.

import typing
import pathlib
from styxdefs import *

V__DEBLANK_FILE_NAMES_METADATA = Metadata(
    id="a4ade0381653186c414b4d6513135f328146083b.boutiques",
    name="@DeblankFileNames",
    package="afni",
    container_image_tag="afni/afni_make_build:AFNI_24.2.06",
)


_VDeblankFileNamesParamsDictNoTag = typing.TypedDict('_VDeblankFileNamesParamsDictNoTag', {
    "move": bool,
    "nobrac": bool,
    "demo_set": bool,
    "echo": bool,
    "help": bool,
    "files": typing.NotRequired[list[InputPathType] | None],
})
VDeblankFileNamesParamsDictTagged = typing.TypedDict('VDeblankFileNamesParamsDictTagged', {
    "@type": typing.Literal["afni/@DeblankFileNames"],
    "move": bool,
    "nobrac": bool,
    "demo_set": bool,
    "echo": bool,
    "help": bool,
    "files": typing.NotRequired[list[InputPathType] | None],
})
VDeblankFileNamesParamsDict = _VDeblankFileNamesParamsDictNoTag | VDeblankFileNamesParamsDictTagged


class VDeblankFileNamesOutputs(typing.NamedTuple):
    """
    Output object returned when calling `VDeblankFileNamesParamsDict(...)`.
    """
    root: OutputPathType
    """Output root folder. This is the root folder for all outputs."""


def v__deblank_file_names_params(
    move: bool = False,
    nobrac: bool = False,
    demo_set: bool = False,
    echo: bool = False,
    help_: bool = False,
    files: list[InputPathType] | None = None,
) -> VDeblankFileNamesParamsDictTagged:
    """
    Build parameters.
    
    Args:
        move: Actually rename the files (opposite of -dry_run).
        nobrac: Do not replace () and [] in filenames, just spaces.
        demo_set: Create a toy directory with bad names for testing.
        echo: Turn on script echo.
        help_: Display help message.
        files: Specify files to fix as opposed to letting it fix all the names\
            in the current directory.
    Returns:
        Parameter dictionary
    """
    params = {
        "@type": "afni/@DeblankFileNames",
        "move": move,
        "nobrac": nobrac,
        "demo_set": demo_set,
        "echo": echo,
        "help": help_,
    }
    if files is not None:
        params["files"] = files
    return params


def v__deblank_file_names_validate(
    params: typing.Any,
) -> None:
    """
    Validate parameters. Throws an error if `params` is not a valid
    `VDeblankFileNamesParamsDict` object.
    
    Args:
        params: The parameters object to validate.
    """
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("move", False) is None:
        raise StyxValidationError("`move` must not be None")
    if not isinstance(params["move"], bool):
        raise StyxValidationError(f'`move` has the wrong type: Received `{type(params.get("move", False))}` expected `bool`')
    if params.get("nobrac", False) is None:
        raise StyxValidationError("`nobrac` must not be None")
    if not isinstance(params["nobrac"], bool):
        raise StyxValidationError(f'`nobrac` has the wrong type: Received `{type(params.get("nobrac", False))}` expected `bool`')
    if params.get("demo_set", False) is None:
        raise StyxValidationError("`demo_set` must not be None")
    if not isinstance(params["demo_set"], bool):
        raise StyxValidationError(f'`demo_set` has the wrong type: Received `{type(params.get("demo_set", False))}` expected `bool`')
    if params.get("echo", False) is None:
        raise StyxValidationError("`echo` must not be None")
    if not isinstance(params["echo"], bool):
        raise StyxValidationError(f'`echo` has the wrong type: Received `{type(params.get("echo", False))}` expected `bool`')
    if params.get("help", False) is None:
        raise StyxValidationError("`help` must not be None")
    if not isinstance(params["help"], bool):
        raise StyxValidationError(f'`help` has the wrong type: Received `{type(params.get("help", False))}` expected `bool`')
    if params.get("files", None) is not None:
        if not isinstance(params["files"], list):
            raise StyxValidationError(f'`files` has the wrong type: Received `{type(params.get("files", None))}` expected `list[InputPathType] | None`')
        for e in params["files"]:
            if not isinstance(e, (pathlib.Path, str)):
                raise StyxValidationError(f'`files` has the wrong type: Received `{type(params.get("files", None))}` expected `list[InputPathType] | None`')


def v__deblank_file_names_cargs(
    params: VDeblankFileNamesParamsDict,
    execution: Execution,
) -> list[str]:
    """
    Build command-line arguments from parameters.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Command-line arguments.
    """
    cargs = []
    cargs.append("@DeblankFileNames")
    if params.get("move", False):
        cargs.append("-move")
    if params.get("nobrac", False):
        cargs.append("-nobrac")
    if params.get("demo_set", False):
        cargs.append("-demo_set")
    if params.get("echo", False):
        cargs.append("-echo")
    if params.get("help", False):
        cargs.append("-help")
    if params.get("files", None) is not None:
        cargs.extend([execution.input_file(f) for f in params.get("files", None)])
    return cargs


def v__deblank_file_names_outputs(
    params: VDeblankFileNamesParamsDict,
    execution: Execution,
) -> VDeblankFileNamesOutputs:
    """
    Build outputs object containing output file paths and possibly stdout/stderr.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Outputs object.
    """
    ret = VDeblankFileNamesOutputs(
        root=execution.output_file("."),
    )
    return ret


def v__deblank_file_names_execute(
    params: VDeblankFileNamesParamsDict,
    runner: Runner | None = None,
) -> VDeblankFileNamesOutputs:
    """
    @DeblankFileNames
    
    A script to remove blanks and other annoying characters ([], ()) from
    filenames.
    
    Author: AFNI Developers
    
    URL: https://afni.nimh.nih.gov/
    
    Args:
        params: The parameters.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `VDeblankFileNamesOutputs`).
    """
    v__deblank_file_names_validate(params)
    runner = runner or get_global_runner()
    execution = runner.start_execution(V__DEBLANK_FILE_NAMES_METADATA)
    params = execution.params(params)
    cargs = v__deblank_file_names_cargs(params, execution)
    ret = v__deblank_file_names_outputs(params, execution)
    execution.run(cargs)
    return ret


def v__deblank_file_names(
    move: bool = False,
    nobrac: bool = False,
    demo_set: bool = False,
    echo: bool = False,
    help_: bool = False,
    files: list[InputPathType] | None = None,
    runner: Runner | None = None,
) -> VDeblankFileNamesOutputs:
    """
    @DeblankFileNames
    
    A script to remove blanks and other annoying characters ([], ()) from
    filenames.
    
    Author: AFNI Developers
    
    URL: https://afni.nimh.nih.gov/
    
    Args:
        move: Actually rename the files (opposite of -dry_run).
        nobrac: Do not replace () and [] in filenames, just spaces.
        demo_set: Create a toy directory with bad names for testing.
        echo: Turn on script echo.
        help_: Display help message.
        files: Specify files to fix as opposed to letting it fix all the names\
            in the current directory.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `VDeblankFileNamesOutputs`).
    """
    params = v__deblank_file_names_params(
        move=move,
        nobrac=nobrac,
        demo_set=demo_set,
        echo=echo,
        help_=help_,
        files=files,
    )
    return v__deblank_file_names_execute(params, runner)


__all__ = [
    "VDeblankFileNamesOutputs",
    "VDeblankFileNamesParamsDict",
    "VDeblankFileNamesParamsDictTagged",
    "V__DEBLANK_FILE_NAMES_METADATA",
    "v__deblank_file_names",
    "v__deblank_file_names_execute",
    "v__deblank_file_names_params",
]
