[project]
name = "niwrap_workbench"
version = "1.0.0"
description = "Connectome Workbench is an open-source visualization and discovery tool developed for the Human Connectome Project (HCP) at Washington University in St. Louis. It includes wb_view, a GUI-based visualization platform for exploring brain imaging data on cortical surfaces and volumes, and wb_command, a command-line program for performing algorithmic tasks using volume, surface, and grayordinate (CIFTI) data. wb_command is essential for running HCP minimal processing pipelines."
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "Daniel S. Marcus" }, { name = "John Harwell" }, { name = "Timothy S. Coalson" }, { name = "Matthew F. Glasser" }, { name = "David C. Van Essen" }]
requires-python = ">=3.10"
dependencies = [
  "styxdefs>=0.7.0,<0.8.0",
]

[tool.setuptools]
packages = ["workbench"]
package-dir = { "workbench" = "." }

[tool.setuptools.package-data]
"workbench" = ["py.typed"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
