# This file was auto generated by Styx.
# Do not edit this file directly.

import typing
import pathlib
from styxdefs import *

LONGMC_METADATA = Metadata(
    id="8b8d473dc021d846b6f6add4166697d771e2be94.boutiques",
    name="longmc",
    package="freesurfer",
    container_image_tag="freesurfer/freesurfer:7.4.1",
)


_LongmcParamsDictNoTag = typing.TypedDict('_LongmcParamsDictNoTag', {
    "cross_tp_name": str,
    "base_name": str,
    "conform_to_hires": bool,
    "no_conform_to_hires": bool,
    "subjects_dir": str,
    "subject_name": typing.NotRequired[str | None],
    "no_force_update": bool,
})
LongmcParamsDictTagged = typing.TypedDict('LongmcParamsDictTagged', {
    "@type": typing.Literal["freesurfer/longmc"],
    "cross_tp_name": str,
    "base_name": str,
    "conform_to_hires": bool,
    "no_conform_to_hires": bool,
    "subjects_dir": str,
    "subject_name": typing.NotRequired[str | None],
    "no_force_update": bool,
})
LongmcParamsDict = _LongmcParamsDictNoTag | LongmcParamsDictTagged


class LongmcOutputs(typing.NamedTuple):
    """
    Output object returned when calling `LongmcParamsDict(...)`.
    """
    root: OutputPathType
    """Output root folder. This is the root folder for all outputs."""


def longmc_params(
    cross_tp_name: str,
    base_name: str,
    subjects_dir: str,
    conform_to_hires: bool = False,
    no_conform_to_hires: bool = False,
    subject_name: str | None = None,
    no_force_update: bool = False,
) -> LongmcParamsDictTagged:
    """
    Build parameters.
    
    Args:
        cross_tp_name: Cross time point name for the longitudinal analysis.
        base_name: Base name for the longitudinal analysis.
        subjects_dir: Set the SUBJECTS_DIR directory.
        conform_to_hires: Option to conform input to high-resolution.
        no_conform_to_hires: Option to not conform input to high-resolution.
        subject_name: Subject name override, must be declared after -long.
        no_force_update: Do not force update.
    Returns:
        Parameter dictionary
    """
    params = {
        "@type": "freesurfer/longmc",
        "cross_tp_name": cross_tp_name,
        "base_name": base_name,
        "conform_to_hires": conform_to_hires,
        "no_conform_to_hires": no_conform_to_hires,
        "subjects_dir": subjects_dir,
        "no_force_update": no_force_update,
    }
    if subject_name is not None:
        params["subject_name"] = subject_name
    return params


def longmc_validate(
    params: typing.Any,
) -> None:
    """
    Validate parameters. Throws an error if `params` is not a valid
    `LongmcParamsDict` object.
    
    Args:
        params: The parameters object to validate.
    """
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("cross_tp_name", None) is None:
        raise StyxValidationError("`cross_tp_name` must not be None")
    if not isinstance(params["cross_tp_name"], str):
        raise StyxValidationError(f'`cross_tp_name` has the wrong type: Received `{type(params.get("cross_tp_name", None))}` expected `str`')
    if params.get("base_name", None) is None:
        raise StyxValidationError("`base_name` must not be None")
    if not isinstance(params["base_name"], str):
        raise StyxValidationError(f'`base_name` has the wrong type: Received `{type(params.get("base_name", None))}` expected `str`')
    if params.get("conform_to_hires", False) is None:
        raise StyxValidationError("`conform_to_hires` must not be None")
    if not isinstance(params["conform_to_hires"], bool):
        raise StyxValidationError(f'`conform_to_hires` has the wrong type: Received `{type(params.get("conform_to_hires", False))}` expected `bool`')
    if params.get("no_conform_to_hires", False) is None:
        raise StyxValidationError("`no_conform_to_hires` must not be None")
    if not isinstance(params["no_conform_to_hires"], bool):
        raise StyxValidationError(f'`no_conform_to_hires` has the wrong type: Received `{type(params.get("no_conform_to_hires", False))}` expected `bool`')
    if params.get("subjects_dir", None) is None:
        raise StyxValidationError("`subjects_dir` must not be None")
    if not isinstance(params["subjects_dir"], str):
        raise StyxValidationError(f'`subjects_dir` has the wrong type: Received `{type(params.get("subjects_dir", None))}` expected `str`')
    if params.get("subject_name", None) is not None:
        if not isinstance(params["subject_name"], str):
            raise StyxValidationError(f'`subject_name` has the wrong type: Received `{type(params.get("subject_name", None))}` expected `str | None`')
    if params.get("no_force_update", False) is None:
        raise StyxValidationError("`no_force_update` must not be None")
    if not isinstance(params["no_force_update"], bool):
        raise StyxValidationError(f'`no_force_update` has the wrong type: Received `{type(params.get("no_force_update", False))}` expected `bool`')


def longmc_cargs(
    params: LongmcParamsDict,
    execution: Execution,
) -> list[str]:
    """
    Build command-line arguments from parameters.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Command-line arguments.
    """
    cargs = []
    cargs.append("longmc")
    cargs.extend([
        "-long",
        params.get("cross_tp_name", None)
    ])
    cargs.append(params.get("base_name", None))
    if params.get("conform_to_hires", False):
        cargs.append("-conf2hires")
    if params.get("no_conform_to_hires", False):
        cargs.append("-no-conf2hires")
    cargs.extend([
        "-sd",
        params.get("subjects_dir", None)
    ])
    if params.get("subject_name", None) is not None:
        cargs.extend([
            "-s",
            params.get("subject_name", None)
        ])
    if params.get("no_force_update", False):
        cargs.append("-no-force-update")
    return cargs


def longmc_outputs(
    params: LongmcParamsDict,
    execution: Execution,
) -> LongmcOutputs:
    """
    Build outputs object containing output file paths and possibly stdout/stderr.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Outputs object.
    """
    ret = LongmcOutputs(
        root=execution.output_file("."),
    )
    return ret


def longmc_execute(
    params: LongmcParamsDict,
    runner: Runner | None = None,
) -> LongmcOutputs:
    """
    longmc
    
    Perform motion correction for the longitudinal recon-all stream when
    creating the longitudinal timepoint of a subject.
    
    Author: FreeSurfer Developers
    
    URL: https://github.com/freesurfer/freesurfer
    
    Args:
        params: The parameters.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `LongmcOutputs`).
    """
    longmc_validate(params)
    runner = runner or get_global_runner()
    execution = runner.start_execution(LONGMC_METADATA)
    params = execution.params(params)
    cargs = longmc_cargs(params, execution)
    ret = longmc_outputs(params, execution)
    execution.run(cargs)
    return ret


def longmc(
    cross_tp_name: str,
    base_name: str,
    subjects_dir: str,
    conform_to_hires: bool = False,
    no_conform_to_hires: bool = False,
    subject_name: str | None = None,
    no_force_update: bool = False,
    runner: Runner | None = None,
) -> LongmcOutputs:
    """
    longmc
    
    Perform motion correction for the longitudinal recon-all stream when
    creating the longitudinal timepoint of a subject.
    
    Author: FreeSurfer Developers
    
    URL: https://github.com/freesurfer/freesurfer
    
    Args:
        cross_tp_name: Cross time point name for the longitudinal analysis.
        base_name: Base name for the longitudinal analysis.
        subjects_dir: Set the SUBJECTS_DIR directory.
        conform_to_hires: Option to conform input to high-resolution.
        no_conform_to_hires: Option to not conform input to high-resolution.
        subject_name: Subject name override, must be declared after -long.
        no_force_update: Do not force update.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `LongmcOutputs`).
    """
    params = longmc_params(
        cross_tp_name=cross_tp_name,
        base_name=base_name,
        conform_to_hires=conform_to_hires,
        no_conform_to_hires=no_conform_to_hires,
        subjects_dir=subjects_dir,
        subject_name=subject_name,
        no_force_update=no_force_update,
    )
    return longmc_execute(params, runner)


__all__ = [
    "LONGMC_METADATA",
    "LongmcOutputs",
    "LongmcParamsDict",
    "LongmcParamsDictTagged",
    "longmc",
    "longmc_execute",
    "longmc_params",
]
