# This file was auto generated by Styx.
# Do not edit this file directly.

import typing
import pathlib
from styxdefs import *

MRI_APARC2WMSEG_METADATA = Metadata(
    id="7619486b848b6254295a0d9c8f5041b0df2c66f4.boutiques",
    name="mri_aparc2wmseg",
    package="freesurfer",
    container_image_tag="freesurfer/freesurfer:7.4.1",
)


_MriAparc2wmsegParamsDictNoTag = typing.TypedDict('_MriAparc2wmsegParamsDictNoTag', {
    "subject": str,
    "wmseg_file": str,
    "help": bool,
    "version": bool,
})
MriAparc2wmsegParamsDictTagged = typing.TypedDict('MriAparc2wmsegParamsDictTagged', {
    "@type": typing.Literal["freesurfer/mri_aparc2wmseg"],
    "subject": str,
    "wmseg_file": str,
    "help": bool,
    "version": bool,
})
MriAparc2wmsegParamsDict = _MriAparc2wmsegParamsDictNoTag | MriAparc2wmsegParamsDictTagged


class MriAparc2wmsegOutputs(typing.NamedTuple):
    """
    Output object returned when calling `MriAparc2wmsegParamsDict(...)`.
    """
    root: OutputPathType
    """Output root folder. This is the root folder for all outputs."""


def mri_aparc2wmseg_params(
    subject: str,
    wmseg_file: str,
    help_: bool = False,
    version: bool = False,
) -> MriAparc2wmsegParamsDictTagged:
    """
    Build parameters.
    
    Args:
        subject: The subject identifier used in FreeSurfer.
        wmseg_file: File to store the output white matter segmentation.
        help_: Print out information on how to use this program.
        version: Print out version and exit.
    Returns:
        Parameter dictionary
    """
    params = {
        "@type": "freesurfer/mri_aparc2wmseg",
        "subject": subject,
        "wmseg_file": wmseg_file,
        "help": help_,
        "version": version,
    }
    return params


def mri_aparc2wmseg_validate(
    params: typing.Any,
) -> None:
    """
    Validate parameters. Throws an error if `params` is not a valid
    `MriAparc2wmsegParamsDict` object.
    
    Args:
        params: The parameters object to validate.
    """
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("subject", None) is None:
        raise StyxValidationError("`subject` must not be None")
    if not isinstance(params["subject"], str):
        raise StyxValidationError(f'`subject` has the wrong type: Received `{type(params.get("subject", None))}` expected `str`')
    if params.get("wmseg_file", None) is None:
        raise StyxValidationError("`wmseg_file` must not be None")
    if not isinstance(params["wmseg_file"], str):
        raise StyxValidationError(f'`wmseg_file` has the wrong type: Received `{type(params.get("wmseg_file", None))}` expected `str`')
    if params.get("help", False) is None:
        raise StyxValidationError("`help` must not be None")
    if not isinstance(params["help"], bool):
        raise StyxValidationError(f'`help` has the wrong type: Received `{type(params.get("help", False))}` expected `bool`')
    if params.get("version", False) is None:
        raise StyxValidationError("`version` must not be None")
    if not isinstance(params["version"], bool):
        raise StyxValidationError(f'`version` has the wrong type: Received `{type(params.get("version", False))}` expected `bool`')


def mri_aparc2wmseg_cargs(
    params: MriAparc2wmsegParamsDict,
    execution: Execution,
) -> list[str]:
    """
    Build command-line arguments from parameters.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Command-line arguments.
    """
    cargs = []
    cargs.append("mri_aparc2wmseg")
    cargs.extend([
        "--s",
        params.get("subject", None)
    ])
    cargs.extend([
        "--wmseg",
        params.get("wmseg_file", None)
    ])
    if params.get("help", False):
        cargs.append("--help")
    if params.get("version", False):
        cargs.append("--version")
    return cargs


def mri_aparc2wmseg_outputs(
    params: MriAparc2wmsegParamsDict,
    execution: Execution,
) -> MriAparc2wmsegOutputs:
    """
    Build outputs object containing output file paths and possibly stdout/stderr.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Outputs object.
    """
    ret = MriAparc2wmsegOutputs(
        root=execution.output_file("."),
    )
    return ret


def mri_aparc2wmseg_execute(
    params: MriAparc2wmsegParamsDict,
    runner: Runner | None = None,
) -> MriAparc2wmsegOutputs:
    """
    mri_aparc2wmseg
    
    A tool to convert aparc+aseg.mgz annotations into a white matter
    segmentation file.
    
    Author: FreeSurfer Developers
    
    URL: https://github.com/freesurfer/freesurfer
    
    Args:
        params: The parameters.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `MriAparc2wmsegOutputs`).
    """
    mri_aparc2wmseg_validate(params)
    runner = runner or get_global_runner()
    execution = runner.start_execution(MRI_APARC2WMSEG_METADATA)
    params = execution.params(params)
    cargs = mri_aparc2wmseg_cargs(params, execution)
    ret = mri_aparc2wmseg_outputs(params, execution)
    execution.run(cargs)
    return ret


def mri_aparc2wmseg(
    subject: str,
    wmseg_file: str,
    help_: bool = False,
    version: bool = False,
    runner: Runner | None = None,
) -> MriAparc2wmsegOutputs:
    """
    mri_aparc2wmseg
    
    A tool to convert aparc+aseg.mgz annotations into a white matter
    segmentation file.
    
    Author: FreeSurfer Developers
    
    URL: https://github.com/freesurfer/freesurfer
    
    Args:
        subject: The subject identifier used in FreeSurfer.
        wmseg_file: File to store the output white matter segmentation.
        help_: Print out information on how to use this program.
        version: Print out version and exit.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `MriAparc2wmsegOutputs`).
    """
    params = mri_aparc2wmseg_params(
        subject=subject,
        wmseg_file=wmseg_file,
        help_=help_,
        version=version,
    )
    return mri_aparc2wmseg_execute(params, runner)


__all__ = [
    "MRI_APARC2WMSEG_METADATA",
    "MriAparc2wmsegOutputs",
    "MriAparc2wmsegParamsDict",
    "MriAparc2wmsegParamsDictTagged",
    "mri_aparc2wmseg",
    "mri_aparc2wmseg_execute",
    "mri_aparc2wmseg_params",
]
