# This file was auto generated by Styx.
# Do not edit this file directly.

import typing
import pathlib
from styxdefs import *

MRI_ROBUST_TEMPLATE_METADATA = Metadata(
    id="879b2b379c54ce744a435c993b95da04800bb0ba.boutiques",
    name="mri_robust_template",
    package="freesurfer",
    container_image_tag="freesurfer/freesurfer:7.4.1",
)


_MriRobustTemplateParamsDictNoTag = typing.TypedDict('_MriRobustTemplateParamsDictNoTag', {
    "mov_files": list[InputPathType],
    "template_file": str,
    "sat_value": typing.NotRequired[float | None],
    "satit_flag": bool,
    "lta_files": typing.NotRequired[list[str] | None],
    "mapmov_files": typing.NotRequired[list[str] | None],
    "mapmovhdr_files": typing.NotRequired[list[str] | None],
    "weights_files": typing.NotRequired[list[str] | None],
    "oneminusw_flag": bool,
    "average_type": typing.NotRequired[int | None],
    "inittp": typing.NotRequired[int | None],
    "fixtp_flag": bool,
    "iscale_flag": bool,
    "iscaleonly_flag": bool,
    "iscalein_files": typing.NotRequired[list[str] | None],
    "iscaleout_files": typing.NotRequired[list[str] | None],
    "transonly_flag": bool,
    "affine_flag": bool,
    "ixforms_files": typing.NotRequired[list[str] | None],
    "masks_files": typing.NotRequired[list[str] | None],
    "vox2vox_flag": bool,
    "leastsquares_flag": bool,
    "noit_flag": bool,
    "maxit": typing.NotRequired[int | None],
    "highit": typing.NotRequired[int | None],
    "epsit": typing.NotRequired[float | None],
    "pairmaxit": typing.NotRequired[int | None],
    "pairepsit": typing.NotRequired[float | None],
    "subsample": typing.NotRequired[int | None],
    "nomulti_flag": bool,
    "floattype_flag": bool,
    "finalnearest_flag": bool,
    "doubleprec_flag": bool,
    "cras_flag": bool,
    "res_thresh": typing.NotRequired[float | None],
    "frobnorm_thresh": typing.NotRequired[float | None],
    "debug_flag": bool,
})
MriRobustTemplateParamsDictTagged = typing.TypedDict('MriRobustTemplateParamsDictTagged', {
    "@type": typing.Literal["freesurfer/mri_robust_template"],
    "mov_files": list[InputPathType],
    "template_file": str,
    "sat_value": typing.NotRequired[float | None],
    "satit_flag": bool,
    "lta_files": typing.NotRequired[list[str] | None],
    "mapmov_files": typing.NotRequired[list[str] | None],
    "mapmovhdr_files": typing.NotRequired[list[str] | None],
    "weights_files": typing.NotRequired[list[str] | None],
    "oneminusw_flag": bool,
    "average_type": typing.NotRequired[int | None],
    "inittp": typing.NotRequired[int | None],
    "fixtp_flag": bool,
    "iscale_flag": bool,
    "iscaleonly_flag": bool,
    "iscalein_files": typing.NotRequired[list[str] | None],
    "iscaleout_files": typing.NotRequired[list[str] | None],
    "transonly_flag": bool,
    "affine_flag": bool,
    "ixforms_files": typing.NotRequired[list[str] | None],
    "masks_files": typing.NotRequired[list[str] | None],
    "vox2vox_flag": bool,
    "leastsquares_flag": bool,
    "noit_flag": bool,
    "maxit": typing.NotRequired[int | None],
    "highit": typing.NotRequired[int | None],
    "epsit": typing.NotRequired[float | None],
    "pairmaxit": typing.NotRequired[int | None],
    "pairepsit": typing.NotRequired[float | None],
    "subsample": typing.NotRequired[int | None],
    "nomulti_flag": bool,
    "floattype_flag": bool,
    "finalnearest_flag": bool,
    "doubleprec_flag": bool,
    "cras_flag": bool,
    "res_thresh": typing.NotRequired[float | None],
    "frobnorm_thresh": typing.NotRequired[float | None],
    "debug_flag": bool,
})
MriRobustTemplateParamsDict = _MriRobustTemplateParamsDictNoTag | MriRobustTemplateParamsDictTagged


class MriRobustTemplateOutputs(typing.NamedTuple):
    """
    Output object returned when calling `MriRobustTemplateParamsDict(...)`.
    """
    root: OutputPathType
    """Output root folder. This is the root folder for all outputs."""
    output_template: OutputPathType
    """Output template volume (final mean/median image)."""
    output_lta_transform: OutputPathType
    """Output transform file."""
    output_mapped_image: OutputPathType
    """Output mapped and resampled image."""
    output_weights_map: OutputPathType
    """Output weights map (outliers)."""


def mri_robust_template_params(
    mov_files: list[InputPathType],
    template_file: str,
    sat_value: float | None = None,
    satit_flag: bool = False,
    lta_files: list[str] | None = None,
    mapmov_files: list[str] | None = None,
    mapmovhdr_files: list[str] | None = None,
    weights_files: list[str] | None = None,
    oneminusw_flag: bool = False,
    average_type: int | None = None,
    inittp: int | None = None,
    fixtp_flag: bool = False,
    iscale_flag: bool = False,
    iscaleonly_flag: bool = False,
    iscalein_files: list[str] | None = None,
    iscaleout_files: list[str] | None = None,
    transonly_flag: bool = False,
    affine_flag: bool = False,
    ixforms_files: list[str] | None = None,
    masks_files: list[str] | None = None,
    vox2vox_flag: bool = False,
    leastsquares_flag: bool = False,
    noit_flag: bool = False,
    maxit: int | None = None,
    highit: int | None = None,
    epsit: float | None = None,
    pairmaxit: int | None = None,
    pairepsit: float | None = None,
    subsample: int | None = None,
    nomulti_flag: bool = False,
    floattype_flag: bool = False,
    finalnearest_flag: bool = False,
    doubleprec_flag: bool = False,
    cras_flag: bool = False,
    res_thresh: float | None = None,
    frobnorm_thresh: float | None = None,
    debug_flag: bool = False,
) -> MriRobustTemplateParamsDictTagged:
    """
    Build parameters.
    
    Args:
        mov_files: Input movable volumes to be aligned to common mean/median\
            template.
        template_file: Output template volume (final mean/median image).
        sat_value: Set outlier sensitivity manually. Higher values mean less\
            sensitivity.
        satit_flag: Auto-detect good sensitivity (recommended for head or full\
            brain scans).
        lta_files: Output transforms to template (for each input).
        mapmov_files: Output images: map and resample each input to template.
        mapmovhdr_files: Output images: header-adjusted movables (no\
            resampling).
        weights_files: Output weights (outliers) in target space.
        oneminusw_flag: Weights (outlier) map will be inverted (0=outlier), as\
            in earlier versions.
        average_type: Construct template from: 0 Mean, 1 Median (default).
        inittp: Use TP# for spatial init (default random), 0: no init.
        fixtp_flag: Map everything to init TP# (init TP is not resampled).
        iscale_flag: Allow also intensity scaling (default off).
        iscaleonly_flag: Only perform iscale (no transformation, default off).
        iscalein_files: Use initial intensity scales.
        iscaleout_files: Output final intensity scales (will activate\
            --iscale).
        transonly_flag: Find 3 parameter translation only.
        affine_flag: Find 12 parameter affine transform.
        ixforms_files: Use initial transforms (lta) on source ('id'=identity).
        masks_files: Input masks applied to movables.
        vox2vox_flag: Output VOX2VOX lta file (default is RAS2RAS).
        leastsquares_flag: Use least squares instead of robust M-estimator (for\
            testing only).
        noit_flag: Do not iterate, just create first template.
        maxit: Iterate max # times (if #tp>2 default 6, else 5 for 2tp reg.).
        highit: Iterate max # times on highest resolution (default 5).
        epsit: Stop iterations when all transform updates fall below the\
            specified value.
        pairmaxit: Iterate max # times (default 5) for individual pairwise\
            registrations.
        pairepsit: Stop individual pairwise registration iterations when\
            transform updates fall below the specified value.
        subsample: Subsample if dimension > specified value on all axes\
            (default no subsampling).
        nomulti_flag: Do not use multi-resolution (only highest resolution).
        floattype_flag: Convert images to float internally (default: keep input\
            type).
        finalnearest_flag: Use nearest neighbor in final interpolation when\
            creating average.
        doubleprec_flag: Use double precision instead of float internally\
            (large memory usage).
        cras_flag: Center template at average CRAS, instead of average\
            barycenter.
        res_thresh: Volume resolution threshold (default is 0.01 mm).
        frobnorm_thresh: Matrix frobenius norm threshold (default is 0.0001).
        debug_flag: Show debug output (default no debug output).
    Returns:
        Parameter dictionary
    """
    params = {
        "@type": "freesurfer/mri_robust_template",
        "mov_files": mov_files,
        "template_file": template_file,
        "satit_flag": satit_flag,
        "oneminusw_flag": oneminusw_flag,
        "fixtp_flag": fixtp_flag,
        "iscale_flag": iscale_flag,
        "iscaleonly_flag": iscaleonly_flag,
        "transonly_flag": transonly_flag,
        "affine_flag": affine_flag,
        "vox2vox_flag": vox2vox_flag,
        "leastsquares_flag": leastsquares_flag,
        "noit_flag": noit_flag,
        "nomulti_flag": nomulti_flag,
        "floattype_flag": floattype_flag,
        "finalnearest_flag": finalnearest_flag,
        "doubleprec_flag": doubleprec_flag,
        "cras_flag": cras_flag,
        "debug_flag": debug_flag,
    }
    if sat_value is not None:
        params["sat_value"] = sat_value
    if lta_files is not None:
        params["lta_files"] = lta_files
    if mapmov_files is not None:
        params["mapmov_files"] = mapmov_files
    if mapmovhdr_files is not None:
        params["mapmovhdr_files"] = mapmovhdr_files
    if weights_files is not None:
        params["weights_files"] = weights_files
    if average_type is not None:
        params["average_type"] = average_type
    if inittp is not None:
        params["inittp"] = inittp
    if iscalein_files is not None:
        params["iscalein_files"] = iscalein_files
    if iscaleout_files is not None:
        params["iscaleout_files"] = iscaleout_files
    if ixforms_files is not None:
        params["ixforms_files"] = ixforms_files
    if masks_files is not None:
        params["masks_files"] = masks_files
    if maxit is not None:
        params["maxit"] = maxit
    if highit is not None:
        params["highit"] = highit
    if epsit is not None:
        params["epsit"] = epsit
    if pairmaxit is not None:
        params["pairmaxit"] = pairmaxit
    if pairepsit is not None:
        params["pairepsit"] = pairepsit
    if subsample is not None:
        params["subsample"] = subsample
    if res_thresh is not None:
        params["res_thresh"] = res_thresh
    if frobnorm_thresh is not None:
        params["frobnorm_thresh"] = frobnorm_thresh
    return params


def mri_robust_template_validate(
    params: typing.Any,
) -> None:
    """
    Validate parameters. Throws an error if `params` is not a valid
    `MriRobustTemplateParamsDict` object.
    
    Args:
        params: The parameters object to validate.
    """
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("mov_files", None) is None:
        raise StyxValidationError("`mov_files` must not be None")
    if not isinstance(params["mov_files"], list):
        raise StyxValidationError(f'`mov_files` has the wrong type: Received `{type(params.get("mov_files", None))}` expected `list[InputPathType]`')
    for e in params["mov_files"]:
        if not isinstance(e, (pathlib.Path, str)):
            raise StyxValidationError(f'`mov_files` has the wrong type: Received `{type(params.get("mov_files", None))}` expected `list[InputPathType]`')
    if params.get("template_file", None) is None:
        raise StyxValidationError("`template_file` must not be None")
    if not isinstance(params["template_file"], str):
        raise StyxValidationError(f'`template_file` has the wrong type: Received `{type(params.get("template_file", None))}` expected `str`')
    if params.get("sat_value", None) is not None:
        if not isinstance(params["sat_value"], (float, int)):
            raise StyxValidationError(f'`sat_value` has the wrong type: Received `{type(params.get("sat_value", None))}` expected `float | None`')
    if params.get("satit_flag", False) is None:
        raise StyxValidationError("`satit_flag` must not be None")
    if not isinstance(params["satit_flag"], bool):
        raise StyxValidationError(f'`satit_flag` has the wrong type: Received `{type(params.get("satit_flag", False))}` expected `bool`')
    if params.get("lta_files", None) is not None:
        if not isinstance(params["lta_files"], list):
            raise StyxValidationError(f'`lta_files` has the wrong type: Received `{type(params.get("lta_files", None))}` expected `list[str] | None`')
        for e in params["lta_files"]:
            if not isinstance(e, str):
                raise StyxValidationError(f'`lta_files` has the wrong type: Received `{type(params.get("lta_files", None))}` expected `list[str] | None`')
    if params.get("mapmov_files", None) is not None:
        if not isinstance(params["mapmov_files"], list):
            raise StyxValidationError(f'`mapmov_files` has the wrong type: Received `{type(params.get("mapmov_files", None))}` expected `list[str] | None`')
        for e in params["mapmov_files"]:
            if not isinstance(e, str):
                raise StyxValidationError(f'`mapmov_files` has the wrong type: Received `{type(params.get("mapmov_files", None))}` expected `list[str] | None`')
    if params.get("mapmovhdr_files", None) is not None:
        if not isinstance(params["mapmovhdr_files"], list):
            raise StyxValidationError(f'`mapmovhdr_files` has the wrong type: Received `{type(params.get("mapmovhdr_files", None))}` expected `list[str] | None`')
        for e in params["mapmovhdr_files"]:
            if not isinstance(e, str):
                raise StyxValidationError(f'`mapmovhdr_files` has the wrong type: Received `{type(params.get("mapmovhdr_files", None))}` expected `list[str] | None`')
    if params.get("weights_files", None) is not None:
        if not isinstance(params["weights_files"], list):
            raise StyxValidationError(f'`weights_files` has the wrong type: Received `{type(params.get("weights_files", None))}` expected `list[str] | None`')
        for e in params["weights_files"]:
            if not isinstance(e, str):
                raise StyxValidationError(f'`weights_files` has the wrong type: Received `{type(params.get("weights_files", None))}` expected `list[str] | None`')
    if params.get("oneminusw_flag", False) is None:
        raise StyxValidationError("`oneminusw_flag` must not be None")
    if not isinstance(params["oneminusw_flag"], bool):
        raise StyxValidationError(f'`oneminusw_flag` has the wrong type: Received `{type(params.get("oneminusw_flag", False))}` expected `bool`')
    if params.get("average_type", None) is not None:
        if not isinstance(params["average_type"], int):
            raise StyxValidationError(f'`average_type` has the wrong type: Received `{type(params.get("average_type", None))}` expected `int | None`')
    if params.get("inittp", None) is not None:
        if not isinstance(params["inittp"], int):
            raise StyxValidationError(f'`inittp` has the wrong type: Received `{type(params.get("inittp", None))}` expected `int | None`')
    if params.get("fixtp_flag", False) is None:
        raise StyxValidationError("`fixtp_flag` must not be None")
    if not isinstance(params["fixtp_flag"], bool):
        raise StyxValidationError(f'`fixtp_flag` has the wrong type: Received `{type(params.get("fixtp_flag", False))}` expected `bool`')
    if params.get("iscale_flag", False) is None:
        raise StyxValidationError("`iscale_flag` must not be None")
    if not isinstance(params["iscale_flag"], bool):
        raise StyxValidationError(f'`iscale_flag` has the wrong type: Received `{type(params.get("iscale_flag", False))}` expected `bool`')
    if params.get("iscaleonly_flag", False) is None:
        raise StyxValidationError("`iscaleonly_flag` must not be None")
    if not isinstance(params["iscaleonly_flag"], bool):
        raise StyxValidationError(f'`iscaleonly_flag` has the wrong type: Received `{type(params.get("iscaleonly_flag", False))}` expected `bool`')
    if params.get("iscalein_files", None) is not None:
        if not isinstance(params["iscalein_files"], list):
            raise StyxValidationError(f'`iscalein_files` has the wrong type: Received `{type(params.get("iscalein_files", None))}` expected `list[str] | None`')
        for e in params["iscalein_files"]:
            if not isinstance(e, str):
                raise StyxValidationError(f'`iscalein_files` has the wrong type: Received `{type(params.get("iscalein_files", None))}` expected `list[str] | None`')
    if params.get("iscaleout_files", None) is not None:
        if not isinstance(params["iscaleout_files"], list):
            raise StyxValidationError(f'`iscaleout_files` has the wrong type: Received `{type(params.get("iscaleout_files", None))}` expected `list[str] | None`')
        for e in params["iscaleout_files"]:
            if not isinstance(e, str):
                raise StyxValidationError(f'`iscaleout_files` has the wrong type: Received `{type(params.get("iscaleout_files", None))}` expected `list[str] | None`')
    if params.get("transonly_flag", False) is None:
        raise StyxValidationError("`transonly_flag` must not be None")
    if not isinstance(params["transonly_flag"], bool):
        raise StyxValidationError(f'`transonly_flag` has the wrong type: Received `{type(params.get("transonly_flag", False))}` expected `bool`')
    if params.get("affine_flag", False) is None:
        raise StyxValidationError("`affine_flag` must not be None")
    if not isinstance(params["affine_flag"], bool):
        raise StyxValidationError(f'`affine_flag` has the wrong type: Received `{type(params.get("affine_flag", False))}` expected `bool`')
    if params.get("ixforms_files", None) is not None:
        if not isinstance(params["ixforms_files"], list):
            raise StyxValidationError(f'`ixforms_files` has the wrong type: Received `{type(params.get("ixforms_files", None))}` expected `list[str] | None`')
        for e in params["ixforms_files"]:
            if not isinstance(e, str):
                raise StyxValidationError(f'`ixforms_files` has the wrong type: Received `{type(params.get("ixforms_files", None))}` expected `list[str] | None`')
    if params.get("masks_files", None) is not None:
        if not isinstance(params["masks_files"], list):
            raise StyxValidationError(f'`masks_files` has the wrong type: Received `{type(params.get("masks_files", None))}` expected `list[str] | None`')
        for e in params["masks_files"]:
            if not isinstance(e, str):
                raise StyxValidationError(f'`masks_files` has the wrong type: Received `{type(params.get("masks_files", None))}` expected `list[str] | None`')
    if params.get("vox2vox_flag", False) is None:
        raise StyxValidationError("`vox2vox_flag` must not be None")
    if not isinstance(params["vox2vox_flag"], bool):
        raise StyxValidationError(f'`vox2vox_flag` has the wrong type: Received `{type(params.get("vox2vox_flag", False))}` expected `bool`')
    if params.get("leastsquares_flag", False) is None:
        raise StyxValidationError("`leastsquares_flag` must not be None")
    if not isinstance(params["leastsquares_flag"], bool):
        raise StyxValidationError(f'`leastsquares_flag` has the wrong type: Received `{type(params.get("leastsquares_flag", False))}` expected `bool`')
    if params.get("noit_flag", False) is None:
        raise StyxValidationError("`noit_flag` must not be None")
    if not isinstance(params["noit_flag"], bool):
        raise StyxValidationError(f'`noit_flag` has the wrong type: Received `{type(params.get("noit_flag", False))}` expected `bool`')
    if params.get("maxit", None) is not None:
        if not isinstance(params["maxit"], int):
            raise StyxValidationError(f'`maxit` has the wrong type: Received `{type(params.get("maxit", None))}` expected `int | None`')
    if params.get("highit", None) is not None:
        if not isinstance(params["highit"], int):
            raise StyxValidationError(f'`highit` has the wrong type: Received `{type(params.get("highit", None))}` expected `int | None`')
    if params.get("epsit", None) is not None:
        if not isinstance(params["epsit"], (float, int)):
            raise StyxValidationError(f'`epsit` has the wrong type: Received `{type(params.get("epsit", None))}` expected `float | None`')
    if params.get("pairmaxit", None) is not None:
        if not isinstance(params["pairmaxit"], int):
            raise StyxValidationError(f'`pairmaxit` has the wrong type: Received `{type(params.get("pairmaxit", None))}` expected `int | None`')
    if params.get("pairepsit", None) is not None:
        if not isinstance(params["pairepsit"], (float, int)):
            raise StyxValidationError(f'`pairepsit` has the wrong type: Received `{type(params.get("pairepsit", None))}` expected `float | None`')
    if params.get("subsample", None) is not None:
        if not isinstance(params["subsample"], int):
            raise StyxValidationError(f'`subsample` has the wrong type: Received `{type(params.get("subsample", None))}` expected `int | None`')
    if params.get("nomulti_flag", False) is None:
        raise StyxValidationError("`nomulti_flag` must not be None")
    if not isinstance(params["nomulti_flag"], bool):
        raise StyxValidationError(f'`nomulti_flag` has the wrong type: Received `{type(params.get("nomulti_flag", False))}` expected `bool`')
    if params.get("floattype_flag", False) is None:
        raise StyxValidationError("`floattype_flag` must not be None")
    if not isinstance(params["floattype_flag"], bool):
        raise StyxValidationError(f'`floattype_flag` has the wrong type: Received `{type(params.get("floattype_flag", False))}` expected `bool`')
    if params.get("finalnearest_flag", False) is None:
        raise StyxValidationError("`finalnearest_flag` must not be None")
    if not isinstance(params["finalnearest_flag"], bool):
        raise StyxValidationError(f'`finalnearest_flag` has the wrong type: Received `{type(params.get("finalnearest_flag", False))}` expected `bool`')
    if params.get("doubleprec_flag", False) is None:
        raise StyxValidationError("`doubleprec_flag` must not be None")
    if not isinstance(params["doubleprec_flag"], bool):
        raise StyxValidationError(f'`doubleprec_flag` has the wrong type: Received `{type(params.get("doubleprec_flag", False))}` expected `bool`')
    if params.get("cras_flag", False) is None:
        raise StyxValidationError("`cras_flag` must not be None")
    if not isinstance(params["cras_flag"], bool):
        raise StyxValidationError(f'`cras_flag` has the wrong type: Received `{type(params.get("cras_flag", False))}` expected `bool`')
    if params.get("res_thresh", None) is not None:
        if not isinstance(params["res_thresh"], (float, int)):
            raise StyxValidationError(f'`res_thresh` has the wrong type: Received `{type(params.get("res_thresh", None))}` expected `float | None`')
    if params.get("frobnorm_thresh", None) is not None:
        if not isinstance(params["frobnorm_thresh"], (float, int)):
            raise StyxValidationError(f'`frobnorm_thresh` has the wrong type: Received `{type(params.get("frobnorm_thresh", None))}` expected `float | None`')
    if params.get("debug_flag", False) is None:
        raise StyxValidationError("`debug_flag` must not be None")
    if not isinstance(params["debug_flag"], bool):
        raise StyxValidationError(f'`debug_flag` has the wrong type: Received `{type(params.get("debug_flag", False))}` expected `bool`')


def mri_robust_template_cargs(
    params: MriRobustTemplateParamsDict,
    execution: Execution,
) -> list[str]:
    """
    Build command-line arguments from parameters.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Command-line arguments.
    """
    cargs = []
    cargs.append("mri_robust_template")
    cargs.extend([
        "-mov",
        *[execution.input_file(f) for f in params.get("mov_files", None)]
    ])
    cargs.extend([
        "-template",
        params.get("template_file", None)
    ])
    if params.get("sat_value", None) is not None:
        cargs.extend([
            "--sat",
            str(params.get("sat_value", None))
        ])
    if params.get("satit_flag", False):
        cargs.append("--satit")
    if params.get("lta_files", None) is not None:
        cargs.extend([
            "--lta",
            *params.get("lta_files", None)
        ])
    if params.get("mapmov_files", None) is not None:
        cargs.extend([
            "--mapmov",
            *params.get("mapmov_files", None)
        ])
    if params.get("mapmovhdr_files", None) is not None:
        cargs.extend([
            "--mapmovhdr",
            *params.get("mapmovhdr_files", None)
        ])
    if params.get("weights_files", None) is not None:
        cargs.extend([
            "--weights",
            *params.get("weights_files", None)
        ])
    if params.get("oneminusw_flag", False):
        cargs.append("--oneminusw")
    if params.get("average_type", None) is not None:
        cargs.extend([
            "--average",
            str(params.get("average_type", None))
        ])
    if params.get("inittp", None) is not None:
        cargs.extend([
            "--inittp",
            str(params.get("inittp", None))
        ])
    if params.get("fixtp_flag", False):
        cargs.append("--fixtp")
    if params.get("iscale_flag", False):
        cargs.append("--iscale")
    if params.get("iscaleonly_flag", False):
        cargs.append("--iscaleonly")
    if params.get("iscalein_files", None) is not None:
        cargs.extend([
            "--iscalein",
            *params.get("iscalein_files", None)
        ])
    if params.get("iscaleout_files", None) is not None:
        cargs.extend([
            "--iscaleout",
            *params.get("iscaleout_files", None)
        ])
    if params.get("transonly_flag", False):
        cargs.append("--transonly")
    if params.get("affine_flag", False):
        cargs.append("--affine")
    if params.get("ixforms_files", None) is not None:
        cargs.extend([
            "--ixforms",
            *params.get("ixforms_files", None)
        ])
    if params.get("masks_files", None) is not None:
        cargs.extend([
            "--masks",
            *params.get("masks_files", None)
        ])
    if params.get("vox2vox_flag", False):
        cargs.append("--vox2vox")
    if params.get("leastsquares_flag", False):
        cargs.append("--leastsquares")
    if params.get("noit_flag", False):
        cargs.append("--noit")
    if params.get("maxit", None) is not None:
        cargs.extend([
            "--maxit",
            str(params.get("maxit", None))
        ])
    if params.get("highit", None) is not None:
        cargs.extend([
            "--highit",
            str(params.get("highit", None))
        ])
    if params.get("epsit", None) is not None:
        cargs.extend([
            "--epsit",
            str(params.get("epsit", None))
        ])
    if params.get("pairmaxit", None) is not None:
        cargs.extend([
            "--pairmaxit",
            str(params.get("pairmaxit", None))
        ])
    if params.get("pairepsit", None) is not None:
        cargs.extend([
            "--pairepsit",
            str(params.get("pairepsit", None))
        ])
    if params.get("subsample", None) is not None:
        cargs.extend([
            "--subsample",
            str(params.get("subsample", None))
        ])
    if params.get("nomulti_flag", False):
        cargs.append("--nomulti")
    if params.get("floattype_flag", False):
        cargs.append("--floattype")
    if params.get("finalnearest_flag", False):
        cargs.append("--finalnearest")
    if params.get("doubleprec_flag", False):
        cargs.append("--doubleprec")
    if params.get("cras_flag", False):
        cargs.append("--cras")
    if params.get("res_thresh", None) is not None:
        cargs.extend([
            "--res-thresh",
            str(params.get("res_thresh", None))
        ])
    if params.get("frobnorm_thresh", None) is not None:
        cargs.extend([
            "--frobnorm-thresh",
            str(params.get("frobnorm_thresh", None))
        ])
    if params.get("debug_flag", False):
        cargs.append("--debug")
    return cargs


def mri_robust_template_outputs(
    params: MriRobustTemplateParamsDict,
    execution: Execution,
) -> MriRobustTemplateOutputs:
    """
    Build outputs object containing output file paths and possibly stdout/stderr.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Outputs object.
    """
    ret = MriRobustTemplateOutputs(
        root=execution.output_file("."),
        output_template=execution.output_file(params.get("template_file", None)),
        output_lta_transform=execution.output_file("[TMP_NAME].lta"),
        output_mapped_image=execution.output_file("[TMP_NAME]_to_template.mgz"),
        output_weights_map=execution.output_file("[TMP_NAME]_weights.mgz"),
    )
    return ret


def mri_robust_template_execute(
    params: MriRobustTemplateParamsDict,
    runner: Runner | None = None,
) -> MriRobustTemplateOutputs:
    """
    mri_robust_template
    
    Constructs an unbiased robust template for longitudinal volumes using an
    iterative method.
    
    Author: FreeSurfer Developers
    
    URL: https://github.com/freesurfer/freesurfer
    
    Args:
        params: The parameters.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `MriRobustTemplateOutputs`).
    """
    mri_robust_template_validate(params)
    runner = runner or get_global_runner()
    execution = runner.start_execution(MRI_ROBUST_TEMPLATE_METADATA)
    params = execution.params(params)
    cargs = mri_robust_template_cargs(params, execution)
    ret = mri_robust_template_outputs(params, execution)
    execution.run(cargs)
    return ret


def mri_robust_template(
    mov_files: list[InputPathType],
    template_file: str,
    sat_value: float | None = None,
    satit_flag: bool = False,
    lta_files: list[str] | None = None,
    mapmov_files: list[str] | None = None,
    mapmovhdr_files: list[str] | None = None,
    weights_files: list[str] | None = None,
    oneminusw_flag: bool = False,
    average_type: int | None = None,
    inittp: int | None = None,
    fixtp_flag: bool = False,
    iscale_flag: bool = False,
    iscaleonly_flag: bool = False,
    iscalein_files: list[str] | None = None,
    iscaleout_files: list[str] | None = None,
    transonly_flag: bool = False,
    affine_flag: bool = False,
    ixforms_files: list[str] | None = None,
    masks_files: list[str] | None = None,
    vox2vox_flag: bool = False,
    leastsquares_flag: bool = False,
    noit_flag: bool = False,
    maxit: int | None = None,
    highit: int | None = None,
    epsit: float | None = None,
    pairmaxit: int | None = None,
    pairepsit: float | None = None,
    subsample: int | None = None,
    nomulti_flag: bool = False,
    floattype_flag: bool = False,
    finalnearest_flag: bool = False,
    doubleprec_flag: bool = False,
    cras_flag: bool = False,
    res_thresh: float | None = None,
    frobnorm_thresh: float | None = None,
    debug_flag: bool = False,
    runner: Runner | None = None,
) -> MriRobustTemplateOutputs:
    """
    mri_robust_template
    
    Constructs an unbiased robust template for longitudinal volumes using an
    iterative method.
    
    Author: FreeSurfer Developers
    
    URL: https://github.com/freesurfer/freesurfer
    
    Args:
        mov_files: Input movable volumes to be aligned to common mean/median\
            template.
        template_file: Output template volume (final mean/median image).
        sat_value: Set outlier sensitivity manually. Higher values mean less\
            sensitivity.
        satit_flag: Auto-detect good sensitivity (recommended for head or full\
            brain scans).
        lta_files: Output transforms to template (for each input).
        mapmov_files: Output images: map and resample each input to template.
        mapmovhdr_files: Output images: header-adjusted movables (no\
            resampling).
        weights_files: Output weights (outliers) in target space.
        oneminusw_flag: Weights (outlier) map will be inverted (0=outlier), as\
            in earlier versions.
        average_type: Construct template from: 0 Mean, 1 Median (default).
        inittp: Use TP# for spatial init (default random), 0: no init.
        fixtp_flag: Map everything to init TP# (init TP is not resampled).
        iscale_flag: Allow also intensity scaling (default off).
        iscaleonly_flag: Only perform iscale (no transformation, default off).
        iscalein_files: Use initial intensity scales.
        iscaleout_files: Output final intensity scales (will activate\
            --iscale).
        transonly_flag: Find 3 parameter translation only.
        affine_flag: Find 12 parameter affine transform.
        ixforms_files: Use initial transforms (lta) on source ('id'=identity).
        masks_files: Input masks applied to movables.
        vox2vox_flag: Output VOX2VOX lta file (default is RAS2RAS).
        leastsquares_flag: Use least squares instead of robust M-estimator (for\
            testing only).
        noit_flag: Do not iterate, just create first template.
        maxit: Iterate max # times (if #tp>2 default 6, else 5 for 2tp reg.).
        highit: Iterate max # times on highest resolution (default 5).
        epsit: Stop iterations when all transform updates fall below the\
            specified value.
        pairmaxit: Iterate max # times (default 5) for individual pairwise\
            registrations.
        pairepsit: Stop individual pairwise registration iterations when\
            transform updates fall below the specified value.
        subsample: Subsample if dimension > specified value on all axes\
            (default no subsampling).
        nomulti_flag: Do not use multi-resolution (only highest resolution).
        floattype_flag: Convert images to float internally (default: keep input\
            type).
        finalnearest_flag: Use nearest neighbor in final interpolation when\
            creating average.
        doubleprec_flag: Use double precision instead of float internally\
            (large memory usage).
        cras_flag: Center template at average CRAS, instead of average\
            barycenter.
        res_thresh: Volume resolution threshold (default is 0.01 mm).
        frobnorm_thresh: Matrix frobenius norm threshold (default is 0.0001).
        debug_flag: Show debug output (default no debug output).
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `MriRobustTemplateOutputs`).
    """
    params = mri_robust_template_params(
        mov_files=mov_files,
        template_file=template_file,
        sat_value=sat_value,
        satit_flag=satit_flag,
        lta_files=lta_files,
        mapmov_files=mapmov_files,
        mapmovhdr_files=mapmovhdr_files,
        weights_files=weights_files,
        oneminusw_flag=oneminusw_flag,
        average_type=average_type,
        inittp=inittp,
        fixtp_flag=fixtp_flag,
        iscale_flag=iscale_flag,
        iscaleonly_flag=iscaleonly_flag,
        iscalein_files=iscalein_files,
        iscaleout_files=iscaleout_files,
        transonly_flag=transonly_flag,
        affine_flag=affine_flag,
        ixforms_files=ixforms_files,
        masks_files=masks_files,
        vox2vox_flag=vox2vox_flag,
        leastsquares_flag=leastsquares_flag,
        noit_flag=noit_flag,
        maxit=maxit,
        highit=highit,
        epsit=epsit,
        pairmaxit=pairmaxit,
        pairepsit=pairepsit,
        subsample=subsample,
        nomulti_flag=nomulti_flag,
        floattype_flag=floattype_flag,
        finalnearest_flag=finalnearest_flag,
        doubleprec_flag=doubleprec_flag,
        cras_flag=cras_flag,
        res_thresh=res_thresh,
        frobnorm_thresh=frobnorm_thresh,
        debug_flag=debug_flag,
    )
    return mri_robust_template_execute(params, runner)


__all__ = [
    "MRI_ROBUST_TEMPLATE_METADATA",
    "MriRobustTemplateOutputs",
    "MriRobustTemplateParamsDict",
    "MriRobustTemplateParamsDictTagged",
    "mri_robust_template",
    "mri_robust_template_execute",
    "mri_robust_template_params",
]
