# This file was auto generated by Styx.
# Do not edit this file directly.

import typing
import pathlib
from styxdefs import *

MRI_SEGMENT_METADATA = Metadata(
    id="71d44240bef9b0488533218e873572a129852167.boutiques",
    name="mri_segment",
    package="freesurfer",
    container_image_tag="freesurfer/freesurfer:7.4.1",
)


_MriSegmentParamsDictNoTag = typing.TypedDict('_MriSegmentParamsDictNoTag', {
    "in_vol": InputPathType,
    "out_vol": str,
    "no1d_remove": typing.NotRequired[float | None],
    "slope": typing.NotRequired[float | None],
    "pslope": typing.NotRequired[float | None],
    "nslope": typing.NotRequired[float | None],
    "debug_voxel": typing.NotRequired[list[float] | None],
    "auto": bool,
    "noauto": bool,
    "log": bool,
    "keep": bool,
    "gray_hi": typing.NotRequired[float | None],
    "wm_low": typing.NotRequired[float | None],
    "wm_low_factor": typing.NotRequired[float | None],
    "wm_hi": typing.NotRequired[float | None],
    "nseg": typing.NotRequired[float | None],
    "thicken": bool,
    "fillbg": bool,
    "fillv": bool,
    "blur_sigma": typing.NotRequired[float | None],
    "iterations": typing.NotRequired[float | None],
    "thin_strand_limit": typing.NotRequired[float | None],
    "verbose": bool,
    "threshold": typing.NotRequired[float | None],
    "extract_options": typing.NotRequired[InputPathType | None],
    "wsize": typing.NotRequired[float | None],
    "wsizemm": typing.NotRequired[float | None],
    "polvw_size": typing.NotRequired[float | None],
    "polv_len": typing.NotRequired[float | None],
    "datfile": typing.NotRequired[InputPathType | None],
    "segmentation": typing.NotRequired[str | None],
    "diagno": typing.NotRequired[float | None],
    "diag_write": bool,
    "diag_verbose": bool,
})
MriSegmentParamsDictTagged = typing.TypedDict('MriSegmentParamsDictTagged', {
    "@type": typing.Literal["freesurfer/mri_segment"],
    "in_vol": InputPathType,
    "out_vol": str,
    "no1d_remove": typing.NotRequired[float | None],
    "slope": typing.NotRequired[float | None],
    "pslope": typing.NotRequired[float | None],
    "nslope": typing.NotRequired[float | None],
    "debug_voxel": typing.NotRequired[list[float] | None],
    "auto": bool,
    "noauto": bool,
    "log": bool,
    "keep": bool,
    "gray_hi": typing.NotRequired[float | None],
    "wm_low": typing.NotRequired[float | None],
    "wm_low_factor": typing.NotRequired[float | None],
    "wm_hi": typing.NotRequired[float | None],
    "nseg": typing.NotRequired[float | None],
    "thicken": bool,
    "fillbg": bool,
    "fillv": bool,
    "blur_sigma": typing.NotRequired[float | None],
    "iterations": typing.NotRequired[float | None],
    "thin_strand_limit": typing.NotRequired[float | None],
    "verbose": bool,
    "threshold": typing.NotRequired[float | None],
    "extract_options": typing.NotRequired[InputPathType | None],
    "wsize": typing.NotRequired[float | None],
    "wsizemm": typing.NotRequired[float | None],
    "polvw_size": typing.NotRequired[float | None],
    "polv_len": typing.NotRequired[float | None],
    "datfile": typing.NotRequired[InputPathType | None],
    "segmentation": typing.NotRequired[str | None],
    "diagno": typing.NotRequired[float | None],
    "diag_write": bool,
    "diag_verbose": bool,
})
MriSegmentParamsDict = _MriSegmentParamsDictNoTag | MriSegmentParamsDictTagged


class MriSegmentOutputs(typing.NamedTuple):
    """
    Output object returned when calling `MriSegmentParamsDict(...)`.
    """
    root: OutputPathType
    """Output root folder. This is the root folder for all outputs."""
    output_volume: OutputPathType
    """Segmented white matter output volume"""
    log_file: OutputPathType
    """Log file from segmentation process"""


def mri_segment_params(
    in_vol: InputPathType,
    out_vol: str,
    no1d_remove: float | None = None,
    slope: float | None = None,
    pslope: float | None = None,
    nslope: float | None = None,
    debug_voxel: list[float] | None = None,
    auto: bool = False,
    noauto: bool = False,
    log: bool = False,
    keep: bool = False,
    gray_hi: float | None = None,
    wm_low: float | None = None,
    wm_low_factor: float | None = None,
    wm_hi: float | None = None,
    nseg: float | None = None,
    thicken: bool = False,
    fillbg: bool = False,
    fillv: bool = False,
    blur_sigma: float | None = None,
    iterations: float | None = None,
    thin_strand_limit: float | None = None,
    verbose: bool = False,
    threshold: float | None = None,
    extract_options: InputPathType | None = None,
    wsize: float | None = None,
    wsizemm: float | None = None,
    polvw_size: float | None = None,
    polv_len: float | None = None,
    datfile: InputPathType | None = None,
    segmentation: str | None = None,
    diagno: float | None = None,
    diag_write: bool = False,
    diag_verbose: bool = False,
) -> MriSegmentParamsDictTagged:
    """
    Build parameters.
    
    Args:
        in_vol: Input volume to be segmented.
        out_vol: Output volume after segmentation.
        no1d_remove: Don't run code that removes 1D strands from segmentation.
        slope: Set the curvature slope (both n and p).
        pslope: Set the curvature pslope (default=1.0).
        nslope: Set the curvature nslope (default=1.0).
        debug_voxel: Set voxel for debugging.
        auto: Automatically detect class statistics (default).
        noauto: Don't automatically detect class statistics.
        log: Log to ./segment.dat.
        keep: Keep wm edits, maintains all values of 1 and 255.
        gray_hi: Set the gray matter high limit (default=100.000).
        wm_low: Set the white matter low limit (default=80.000).
        wm_low_factor: wm_low = f*gray_mean + (1-f)*white_mean;.
        wm_hi: Set the white matter high limit (default=125.000).
        nseg: Thicken the n largest thin strands (default=20).
        thicken: Toggle thickening step (default=ON).
        fillbg: Toggle filling of the basal ganglia (default=OFF).
        fillv: Toggle filling of the ventricles (default=OFF).
        blur_sigma: Set blur sigma (default=0.25).
        iterations: Set # iterations of border classification (default=1).
        thin_strand_limit: Set limit to thin strands in mm (default=4).
        verbose: Verbose.
        threshold: Set % threshold (default=0.80).
        extract_options: Extract options from filename.
        wsize: Set wsize (default=11 voxels).
        wsizemm: Set wsize based on mm instead of voxels.
        polvw_size: Set wsize for plane of least variance (default=5).
        polv_len: Set length for plane of least variance (default=3).
        datfile: Set datfile (default is segment.dat).
        segmentation: Use segmentation to set thresholds.
        diagno: Set diagnostic number.
        diag_write: Set diagnostic write.
        diag_verbose: Set diagnostic verbose.
    Returns:
        Parameter dictionary
    """
    params = {
        "@type": "freesurfer/mri_segment",
        "in_vol": in_vol,
        "out_vol": out_vol,
        "auto": auto,
        "noauto": noauto,
        "log": log,
        "keep": keep,
        "thicken": thicken,
        "fillbg": fillbg,
        "fillv": fillv,
        "verbose": verbose,
        "diag_write": diag_write,
        "diag_verbose": diag_verbose,
    }
    if no1d_remove is not None:
        params["no1d_remove"] = no1d_remove
    if slope is not None:
        params["slope"] = slope
    if pslope is not None:
        params["pslope"] = pslope
    if nslope is not None:
        params["nslope"] = nslope
    if debug_voxel is not None:
        params["debug_voxel"] = debug_voxel
    if gray_hi is not None:
        params["gray_hi"] = gray_hi
    if wm_low is not None:
        params["wm_low"] = wm_low
    if wm_low_factor is not None:
        params["wm_low_factor"] = wm_low_factor
    if wm_hi is not None:
        params["wm_hi"] = wm_hi
    if nseg is not None:
        params["nseg"] = nseg
    if blur_sigma is not None:
        params["blur_sigma"] = blur_sigma
    if iterations is not None:
        params["iterations"] = iterations
    if thin_strand_limit is not None:
        params["thin_strand_limit"] = thin_strand_limit
    if threshold is not None:
        params["threshold"] = threshold
    if extract_options is not None:
        params["extract_options"] = extract_options
    if wsize is not None:
        params["wsize"] = wsize
    if wsizemm is not None:
        params["wsizemm"] = wsizemm
    if polvw_size is not None:
        params["polvw_size"] = polvw_size
    if polv_len is not None:
        params["polv_len"] = polv_len
    if datfile is not None:
        params["datfile"] = datfile
    if segmentation is not None:
        params["segmentation"] = segmentation
    if diagno is not None:
        params["diagno"] = diagno
    return params


def mri_segment_validate(
    params: typing.Any,
) -> None:
    """
    Validate parameters. Throws an error if `params` is not a valid
    `MriSegmentParamsDict` object.
    
    Args:
        params: The parameters object to validate.
    """
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("in_vol", None) is None:
        raise StyxValidationError("`in_vol` must not be None")
    if not isinstance(params["in_vol"], (pathlib.Path, str)):
        raise StyxValidationError(f'`in_vol` has the wrong type: Received `{type(params.get("in_vol", None))}` expected `InputPathType`')
    if params.get("out_vol", None) is None:
        raise StyxValidationError("`out_vol` must not be None")
    if not isinstance(params["out_vol"], str):
        raise StyxValidationError(f'`out_vol` has the wrong type: Received `{type(params.get("out_vol", None))}` expected `str`')
    if params.get("no1d_remove", None) is not None:
        if not isinstance(params["no1d_remove"], (float, int)):
            raise StyxValidationError(f'`no1d_remove` has the wrong type: Received `{type(params.get("no1d_remove", None))}` expected `float | None`')
    if params.get("slope", None) is not None:
        if not isinstance(params["slope"], (float, int)):
            raise StyxValidationError(f'`slope` has the wrong type: Received `{type(params.get("slope", None))}` expected `float | None`')
    if params.get("pslope", None) is not None:
        if not isinstance(params["pslope"], (float, int)):
            raise StyxValidationError(f'`pslope` has the wrong type: Received `{type(params.get("pslope", None))}` expected `float | None`')
    if params.get("nslope", None) is not None:
        if not isinstance(params["nslope"], (float, int)):
            raise StyxValidationError(f'`nslope` has the wrong type: Received `{type(params.get("nslope", None))}` expected `float | None`')
    if params.get("debug_voxel", None) is not None:
        if not isinstance(params["debug_voxel"], list):
            raise StyxValidationError(f'`debug_voxel` has the wrong type: Received `{type(params.get("debug_voxel", None))}` expected `list[float] | None`')
        if len(params["debug_voxel"]) != 3:
            raise StyxValidationError("Parameter `debug_voxel` must contain exactly 3 elements")
        for e in params["debug_voxel"]:
            if not isinstance(e, (float, int)):
                raise StyxValidationError(f'`debug_voxel` has the wrong type: Received `{type(params.get("debug_voxel", None))}` expected `list[float] | None`')
    if params.get("auto", False) is None:
        raise StyxValidationError("`auto` must not be None")
    if not isinstance(params["auto"], bool):
        raise StyxValidationError(f'`auto` has the wrong type: Received `{type(params.get("auto", False))}` expected `bool`')
    if params.get("noauto", False) is None:
        raise StyxValidationError("`noauto` must not be None")
    if not isinstance(params["noauto"], bool):
        raise StyxValidationError(f'`noauto` has the wrong type: Received `{type(params.get("noauto", False))}` expected `bool`')
    if params.get("log", False) is None:
        raise StyxValidationError("`log` must not be None")
    if not isinstance(params["log"], bool):
        raise StyxValidationError(f'`log` has the wrong type: Received `{type(params.get("log", False))}` expected `bool`')
    if params.get("keep", False) is None:
        raise StyxValidationError("`keep` must not be None")
    if not isinstance(params["keep"], bool):
        raise StyxValidationError(f'`keep` has the wrong type: Received `{type(params.get("keep", False))}` expected `bool`')
    if params.get("gray_hi", None) is not None:
        if not isinstance(params["gray_hi"], (float, int)):
            raise StyxValidationError(f'`gray_hi` has the wrong type: Received `{type(params.get("gray_hi", None))}` expected `float | None`')
    if params.get("wm_low", None) is not None:
        if not isinstance(params["wm_low"], (float, int)):
            raise StyxValidationError(f'`wm_low` has the wrong type: Received `{type(params.get("wm_low", None))}` expected `float | None`')
    if params.get("wm_low_factor", None) is not None:
        if not isinstance(params["wm_low_factor"], (float, int)):
            raise StyxValidationError(f'`wm_low_factor` has the wrong type: Received `{type(params.get("wm_low_factor", None))}` expected `float | None`')
    if params.get("wm_hi", None) is not None:
        if not isinstance(params["wm_hi"], (float, int)):
            raise StyxValidationError(f'`wm_hi` has the wrong type: Received `{type(params.get("wm_hi", None))}` expected `float | None`')
    if params.get("nseg", None) is not None:
        if not isinstance(params["nseg"], (float, int)):
            raise StyxValidationError(f'`nseg` has the wrong type: Received `{type(params.get("nseg", None))}` expected `float | None`')
    if params.get("thicken", False) is None:
        raise StyxValidationError("`thicken` must not be None")
    if not isinstance(params["thicken"], bool):
        raise StyxValidationError(f'`thicken` has the wrong type: Received `{type(params.get("thicken", False))}` expected `bool`')
    if params.get("fillbg", False) is None:
        raise StyxValidationError("`fillbg` must not be None")
    if not isinstance(params["fillbg"], bool):
        raise StyxValidationError(f'`fillbg` has the wrong type: Received `{type(params.get("fillbg", False))}` expected `bool`')
    if params.get("fillv", False) is None:
        raise StyxValidationError("`fillv` must not be None")
    if not isinstance(params["fillv"], bool):
        raise StyxValidationError(f'`fillv` has the wrong type: Received `{type(params.get("fillv", False))}` expected `bool`')
    if params.get("blur_sigma", None) is not None:
        if not isinstance(params["blur_sigma"], (float, int)):
            raise StyxValidationError(f'`blur_sigma` has the wrong type: Received `{type(params.get("blur_sigma", None))}` expected `float | None`')
    if params.get("iterations", None) is not None:
        if not isinstance(params["iterations"], (float, int)):
            raise StyxValidationError(f'`iterations` has the wrong type: Received `{type(params.get("iterations", None))}` expected `float | None`')
    if params.get("thin_strand_limit", None) is not None:
        if not isinstance(params["thin_strand_limit"], (float, int)):
            raise StyxValidationError(f'`thin_strand_limit` has the wrong type: Received `{type(params.get("thin_strand_limit", None))}` expected `float | None`')
    if params.get("verbose", False) is None:
        raise StyxValidationError("`verbose` must not be None")
    if not isinstance(params["verbose"], bool):
        raise StyxValidationError(f'`verbose` has the wrong type: Received `{type(params.get("verbose", False))}` expected `bool`')
    if params.get("threshold", None) is not None:
        if not isinstance(params["threshold"], (float, int)):
            raise StyxValidationError(f'`threshold` has the wrong type: Received `{type(params.get("threshold", None))}` expected `float | None`')
    if params.get("extract_options", None) is not None:
        if not isinstance(params["extract_options"], (pathlib.Path, str)):
            raise StyxValidationError(f'`extract_options` has the wrong type: Received `{type(params.get("extract_options", None))}` expected `InputPathType | None`')
    if params.get("wsize", None) is not None:
        if not isinstance(params["wsize"], (float, int)):
            raise StyxValidationError(f'`wsize` has the wrong type: Received `{type(params.get("wsize", None))}` expected `float | None`')
    if params.get("wsizemm", None) is not None:
        if not isinstance(params["wsizemm"], (float, int)):
            raise StyxValidationError(f'`wsizemm` has the wrong type: Received `{type(params.get("wsizemm", None))}` expected `float | None`')
    if params.get("polvw_size", None) is not None:
        if not isinstance(params["polvw_size"], (float, int)):
            raise StyxValidationError(f'`polvw_size` has the wrong type: Received `{type(params.get("polvw_size", None))}` expected `float | None`')
    if params.get("polv_len", None) is not None:
        if not isinstance(params["polv_len"], (float, int)):
            raise StyxValidationError(f'`polv_len` has the wrong type: Received `{type(params.get("polv_len", None))}` expected `float | None`')
    if params.get("datfile", None) is not None:
        if not isinstance(params["datfile"], (pathlib.Path, str)):
            raise StyxValidationError(f'`datfile` has the wrong type: Received `{type(params.get("datfile", None))}` expected `InputPathType | None`')
    if params.get("segmentation", None) is not None:
        if not isinstance(params["segmentation"], str):
            raise StyxValidationError(f'`segmentation` has the wrong type: Received `{type(params.get("segmentation", None))}` expected `str | None`')
    if params.get("diagno", None) is not None:
        if not isinstance(params["diagno"], (float, int)):
            raise StyxValidationError(f'`diagno` has the wrong type: Received `{type(params.get("diagno", None))}` expected `float | None`')
    if params.get("diag_write", False) is None:
        raise StyxValidationError("`diag_write` must not be None")
    if not isinstance(params["diag_write"], bool):
        raise StyxValidationError(f'`diag_write` has the wrong type: Received `{type(params.get("diag_write", False))}` expected `bool`')
    if params.get("diag_verbose", False) is None:
        raise StyxValidationError("`diag_verbose` must not be None")
    if not isinstance(params["diag_verbose"], bool):
        raise StyxValidationError(f'`diag_verbose` has the wrong type: Received `{type(params.get("diag_verbose", False))}` expected `bool`')


def mri_segment_cargs(
    params: MriSegmentParamsDict,
    execution: Execution,
) -> list[str]:
    """
    Build command-line arguments from parameters.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Command-line arguments.
    """
    cargs = []
    cargs.append("mri_segment")
    cargs.append(execution.input_file(params.get("in_vol", None)))
    cargs.append(params.get("out_vol", None))
    if params.get("no1d_remove", None) is not None:
        cargs.extend([
            "-no1d_remove",
            str(params.get("no1d_remove", None))
        ])
    if params.get("slope", None) is not None:
        cargs.extend([
            "-slope",
            str(params.get("slope", None))
        ])
    if params.get("pslope", None) is not None:
        cargs.extend([
            "-pslope",
            str(params.get("pslope", None))
        ])
    if params.get("nslope", None) is not None:
        cargs.extend([
            "-nslope",
            str(params.get("nslope", None))
        ])
    if params.get("debug_voxel", None) is not None:
        cargs.extend([
            "-debug_voxel",
            *map(str, params.get("debug_voxel", None))
        ])
    if params.get("auto", False):
        cargs.append("-auto")
    if params.get("noauto", False):
        cargs.append("-noauto")
    if params.get("log", False):
        cargs.append("-log")
    if params.get("keep", False):
        cargs.append("-keep")
    if params.get("gray_hi", None) is not None:
        cargs.extend([
            "-ghi",
            str(params.get("gray_hi", None))
        ])
    if params.get("wm_low", None) is not None:
        cargs.extend([
            "-wlo",
            str(params.get("wm_low", None))
        ])
    if params.get("wm_low_factor", None) is not None:
        cargs.extend([
            "-wm_low_factor",
            str(params.get("wm_low_factor", None))
        ])
    if params.get("wm_hi", None) is not None:
        cargs.extend([
            "-whi",
            str(params.get("wm_hi", None))
        ])
    if params.get("nseg", None) is not None:
        cargs.extend([
            "-nseg",
            str(params.get("nseg", None))
        ])
    if params.get("thicken", False):
        cargs.append("-thicken")
    if params.get("fillbg", False):
        cargs.append("-fillbg")
    if params.get("fillv", False):
        cargs.append("-fillv")
    if params.get("blur_sigma", None) is not None:
        cargs.extend([
            "-b",
            str(params.get("blur_sigma", None))
        ])
    if params.get("iterations", None) is not None:
        cargs.extend([
            "-n",
            str(params.get("iterations", None))
        ])
    if params.get("thin_strand_limit", None) is not None:
        cargs.extend([
            "-t",
            str(params.get("thin_strand_limit", None))
        ])
    if params.get("verbose", False):
        cargs.append("-v")
    if params.get("threshold", None) is not None:
        cargs.extend([
            "-p",
            str(params.get("threshold", None))
        ])
    if params.get("extract_options", None) is not None:
        cargs.extend([
            "-x",
            execution.input_file(params.get("extract_options", None))
        ])
    if params.get("wsize", None) is not None:
        cargs.extend([
            "-w",
            str(params.get("wsize", None))
        ])
    if params.get("wsizemm", None) is not None:
        cargs.extend([
            "-wsizemm",
            str(params.get("wsizemm", None))
        ])
    if params.get("polvw_size", None) is not None:
        cargs.extend([
            "-polvwsize",
            str(params.get("polvw_size", None))
        ])
    if params.get("polv_len", None) is not None:
        cargs.extend([
            "-polvlen",
            str(params.get("polv_len", None))
        ])
    if params.get("datfile", None) is not None:
        cargs.extend([
            "-dat",
            execution.input_file(params.get("datfile", None))
        ])
    if params.get("segmentation", None) is not None:
        cargs.extend([
            "-seg",
            params.get("segmentation", None)
        ])
    if params.get("diagno", None) is not None:
        cargs.extend([
            "-diagno",
            str(params.get("diagno", None))
        ])
    if params.get("diag_write", False):
        cargs.append("-diag-write")
    if params.get("diag_verbose", False):
        cargs.append("-diag-verbose")
    return cargs


def mri_segment_outputs(
    params: MriSegmentParamsDict,
    execution: Execution,
) -> MriSegmentOutputs:
    """
    Build outputs object containing output file paths and possibly stdout/stderr.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Outputs object.
    """
    ret = MriSegmentOutputs(
        root=execution.output_file("."),
        output_volume=execution.output_file(params.get("out_vol", None)),
        log_file=execution.output_file("./segment.dat"),
    )
    return ret


def mri_segment_execute(
    params: MriSegmentParamsDict,
    runner: Runner | None = None,
) -> MriSegmentOutputs:
    """
    mri_segment
    
    Segments white matter from the input volume.
    
    Author: FreeSurfer Developers
    
    URL: https://github.com/freesurfer/freesurfer
    
    Args:
        params: The parameters.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `MriSegmentOutputs`).
    """
    mri_segment_validate(params)
    runner = runner or get_global_runner()
    execution = runner.start_execution(MRI_SEGMENT_METADATA)
    params = execution.params(params)
    cargs = mri_segment_cargs(params, execution)
    ret = mri_segment_outputs(params, execution)
    execution.run(cargs)
    return ret


def mri_segment(
    in_vol: InputPathType,
    out_vol: str,
    no1d_remove: float | None = None,
    slope: float | None = None,
    pslope: float | None = None,
    nslope: float | None = None,
    debug_voxel: list[float] | None = None,
    auto: bool = False,
    noauto: bool = False,
    log: bool = False,
    keep: bool = False,
    gray_hi: float | None = None,
    wm_low: float | None = None,
    wm_low_factor: float | None = None,
    wm_hi: float | None = None,
    nseg: float | None = None,
    thicken: bool = False,
    fillbg: bool = False,
    fillv: bool = False,
    blur_sigma: float | None = None,
    iterations: float | None = None,
    thin_strand_limit: float | None = None,
    verbose: bool = False,
    threshold: float | None = None,
    extract_options: InputPathType | None = None,
    wsize: float | None = None,
    wsizemm: float | None = None,
    polvw_size: float | None = None,
    polv_len: float | None = None,
    datfile: InputPathType | None = None,
    segmentation: str | None = None,
    diagno: float | None = None,
    diag_write: bool = False,
    diag_verbose: bool = False,
    runner: Runner | None = None,
) -> MriSegmentOutputs:
    """
    mri_segment
    
    Segments white matter from the input volume.
    
    Author: FreeSurfer Developers
    
    URL: https://github.com/freesurfer/freesurfer
    
    Args:
        in_vol: Input volume to be segmented.
        out_vol: Output volume after segmentation.
        no1d_remove: Don't run code that removes 1D strands from segmentation.
        slope: Set the curvature slope (both n and p).
        pslope: Set the curvature pslope (default=1.0).
        nslope: Set the curvature nslope (default=1.0).
        debug_voxel: Set voxel for debugging.
        auto: Automatically detect class statistics (default).
        noauto: Don't automatically detect class statistics.
        log: Log to ./segment.dat.
        keep: Keep wm edits, maintains all values of 1 and 255.
        gray_hi: Set the gray matter high limit (default=100.000).
        wm_low: Set the white matter low limit (default=80.000).
        wm_low_factor: wm_low = f*gray_mean + (1-f)*white_mean;.
        wm_hi: Set the white matter high limit (default=125.000).
        nseg: Thicken the n largest thin strands (default=20).
        thicken: Toggle thickening step (default=ON).
        fillbg: Toggle filling of the basal ganglia (default=OFF).
        fillv: Toggle filling of the ventricles (default=OFF).
        blur_sigma: Set blur sigma (default=0.25).
        iterations: Set # iterations of border classification (default=1).
        thin_strand_limit: Set limit to thin strands in mm (default=4).
        verbose: Verbose.
        threshold: Set % threshold (default=0.80).
        extract_options: Extract options from filename.
        wsize: Set wsize (default=11 voxels).
        wsizemm: Set wsize based on mm instead of voxels.
        polvw_size: Set wsize for plane of least variance (default=5).
        polv_len: Set length for plane of least variance (default=3).
        datfile: Set datfile (default is segment.dat).
        segmentation: Use segmentation to set thresholds.
        diagno: Set diagnostic number.
        diag_write: Set diagnostic write.
        diag_verbose: Set diagnostic verbose.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `MriSegmentOutputs`).
    """
    params = mri_segment_params(
        in_vol=in_vol,
        out_vol=out_vol,
        no1d_remove=no1d_remove,
        slope=slope,
        pslope=pslope,
        nslope=nslope,
        debug_voxel=debug_voxel,
        auto=auto,
        noauto=noauto,
        log=log,
        keep=keep,
        gray_hi=gray_hi,
        wm_low=wm_low,
        wm_low_factor=wm_low_factor,
        wm_hi=wm_hi,
        nseg=nseg,
        thicken=thicken,
        fillbg=fillbg,
        fillv=fillv,
        blur_sigma=blur_sigma,
        iterations=iterations,
        thin_strand_limit=thin_strand_limit,
        verbose=verbose,
        threshold=threshold,
        extract_options=extract_options,
        wsize=wsize,
        wsizemm=wsizemm,
        polvw_size=polvw_size,
        polv_len=polv_len,
        datfile=datfile,
        segmentation=segmentation,
        diagno=diagno,
        diag_write=diag_write,
        diag_verbose=diag_verbose,
    )
    return mri_segment_execute(params, runner)


__all__ = [
    "MRI_SEGMENT_METADATA",
    "MriSegmentOutputs",
    "MriSegmentParamsDict",
    "MriSegmentParamsDictTagged",
    "mri_segment",
    "mri_segment_execute",
    "mri_segment_params",
]
