# This file was auto generated by Styx.
# Do not edit this file directly.

import dataclasses
import pathlib
import typing

from styxdefs import Execution, InputPathType, Metadata, Runner, StyxValidationError, OutputPathType, get_global_runner

BUILD_DESIKAN_KILLIANY_GCS_CSH_METADATA = Metadata(
    id="build_desikan_killiany_gcs.csh",
    name="build_desikan_killiany_gcs.csh",
    package="freesurfer",
)

BuildDesikanKillianyGcsCsh = typing.TypedDict(
    "BuildDesikanKillianyGcsCsh",
    {
        "@type": typing.NotRequired[typing.Literal["freesurfer/build_desikan_killiany_gcs.csh"]],
        "hemi": str,
    },
)

@dataclasses.dataclass
class BuildDesikanKillianyGcsCshOutputs:
    """Output paths produced by the tool."""
    root: OutputPathType

def build_desikan_killiany_gcs_csh_params(
    hemi: str,
) -> BuildDesikanKillianyGcsCsh:
    """
    Build parameters.

    Args:
        hemi: Hemisphere designation for the operation. Should be 'rh' for right\
            hemisphere or 'lh' for left hemisphere.

    Returns:
        Parameter dictionary.
    """
    params: BuildDesikanKillianyGcsCsh = {
        "@type": "freesurfer/build_desikan_killiany_gcs.csh",
        "hemi": hemi,
    }
    return params

def build_desikan_killiany_gcs_csh_validate(params: typing.Any) -> None:
    """Validate untrusted parameters. Raises StyxValidationError if `params` is not a valid BuildDesikanKillianyGcsCsh."""
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("hemi", None) is None:
        raise StyxValidationError("`hemi` must not be None")
    if not isinstance(params["hemi"], str):
        raise StyxValidationError(f'`hemi` has the wrong type: Received `{type(params["hemi"])}` expected `str`')

def build_desikan_killiany_gcs_csh_cargs(params: BuildDesikanKillianyGcsCsh, execution: Execution) -> list[str]:
    """Build command-line arguments from parameters."""
    cargs: list[str] = []
    cargs.append("build_desikan_killiany_gcs.csh")
    cargs.append(params["hemi"])
    return cargs

def build_desikan_killiany_gcs_csh_outputs(params: BuildDesikanKillianyGcsCsh, execution: Execution) -> BuildDesikanKillianyGcsCshOutputs:
    """Build the BuildDesikanKillianyGcsCshOutputs object for this tool."""
    root_v: OutputPathType = execution.output_file(".")
    return BuildDesikanKillianyGcsCshOutputs(
        root=root_v,
    )

def build_desikan_killiany_gcs_csh_execute(params: BuildDesikanKillianyGcsCsh, runner: Runner | None = None) -> BuildDesikanKillianyGcsCshOutputs:
    """
    build_desikan_killiany_gcs.csh

    Tool to build Desikan-Killiany cortical parcellation in FreeSurfer.

    Author: FreeSurfer Developers

    URL: https://github.com/freesurfer/freesurfer

    Args:
        params: The parameters.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    build_desikan_killiany_gcs_csh_validate(params)
    runner = runner if runner is not None else get_global_runner()
    execution = runner.start_execution(BUILD_DESIKAN_KILLIANY_GCS_CSH_METADATA)
    execution.params(params)
    args = build_desikan_killiany_gcs_csh_cargs(params, execution)
    out = build_desikan_killiany_gcs_csh_outputs(params, execution)
    execution.run(args)
    return out

def build_desikan_killiany_gcs_csh(
    hemi: str,
    runner: Runner | None = None,
) -> BuildDesikanKillianyGcsCshOutputs:
    """
    build_desikan_killiany_gcs.csh

    Tool to build Desikan-Killiany cortical parcellation in FreeSurfer.

    Author: FreeSurfer Developers

    URL: https://github.com/freesurfer/freesurfer

    Args:
        hemi: Hemisphere designation for the operation. Should be 'rh' for right\
            hemisphere or 'lh' for left hemisphere.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    params = build_desikan_killiany_gcs_csh_params(
        hemi=hemi,
    )
    return build_desikan_killiany_gcs_csh_execute(params, runner)

__all__ = [
    "BuildDesikanKillianyGcsCsh",
    "BuildDesikanKillianyGcsCshOutputs",
    "BUILD_DESIKAN_KILLIANY_GCS_CSH_METADATA",
    "build_desikan_killiany_gcs_csh_cargs",
    "build_desikan_killiany_gcs_csh_outputs",
    "build_desikan_killiany_gcs_csh_params",
    "build_desikan_killiany_gcs_csh_execute",
    "build_desikan_killiany_gcs_csh_validate",
    "build_desikan_killiany_gcs_csh",
]