# This file was auto generated by Styx.
# Do not edit this file directly.

import dataclasses
import pathlib
import typing

from styxdefs import Execution, InputPathType, Metadata, Runner, StyxValidationError, OutputPathType, get_global_runner

MAKE_UPRIGHT_METADATA = Metadata(
    id="make_upright",
    name="make_upright",
    package="freesurfer",
)

MakeUpright = typing.TypedDict(
    "MakeUpright",
    {
        "@type": typing.NotRequired[typing.Literal["freesurfer/make_upright"]],
        "input_image": InputPathType,
        "output_image": str,
        "transformation_map": InputPathType,
    },
)

@dataclasses.dataclass
class MakeUprightOutputs:
    """Output paths produced by the tool."""
    root: OutputPathType
    registered_image: OutputPathType
    """Registered upright MRI image"""

def make_upright_params(
    input_image: InputPathType,
    output_image: str,
    transformation_map: InputPathType,
) -> MakeUpright:
    """
    Build parameters.

    Args:
        input_image: Input MRI image file in .mgz format
        output_image: Output MRI image file in .mgz format
        transformation_map: Transformation map file in .lta format

    Returns:
        Parameter dictionary.
    """
    params: MakeUpright = {
        "@type": "freesurfer/make_upright",
        "input_image": input_image,
        "output_image": output_image,
        "transformation_map": transformation_map,
    }
    return params

def make_upright_validate(params: typing.Any) -> None:
    """Validate untrusted parameters. Raises StyxValidationError if `params` is not a valid MakeUpright."""
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("input_image", None) is None:
        raise StyxValidationError("`input_image` must not be None")
    if not isinstance(params["input_image"], (pathlib.Path, str)):
        raise StyxValidationError(f'`input_image` has the wrong type: Received `{type(params["input_image"])}` expected `InputPathType`')
    if params.get("output_image", None) is None:
        raise StyxValidationError("`output_image` must not be None")
    if not isinstance(params["output_image"], str):
        raise StyxValidationError(f'`output_image` has the wrong type: Received `{type(params["output_image"])}` expected `str`')
    if params.get("transformation_map", None) is None:
        raise StyxValidationError("`transformation_map` must not be None")
    if not isinstance(params["transformation_map"], (pathlib.Path, str)):
        raise StyxValidationError(f'`transformation_map` has the wrong type: Received `{type(params["transformation_map"])}` expected `InputPathType`')

def make_upright_cargs(params: MakeUpright, execution: Execution) -> list[str]:
    """Build command-line arguments from parameters."""
    cargs: list[str] = []
    cargs.append("make_upright")
    cargs.append(execution.input_file(params["input_image"]))
    cargs.append(params["output_image"])
    cargs.append(execution.input_file(params["transformation_map"]))
    return cargs

def make_upright_outputs(params: MakeUpright, execution: Execution) -> MakeUprightOutputs:
    """Build the MakeUprightOutputs object for this tool."""
    root_v: OutputPathType = execution.output_file(".")
    registered_image_v: OutputPathType = execution.output_file(params["output_image"])
    return MakeUprightOutputs(
        root=root_v,
        registered_image=registered_image_v,
    )

def make_upright_execute(params: MakeUpright, runner: Runner | None = None) -> MakeUprightOutputs:
    """
    make_upright

    Registers MRI input to the left/right reversed version using mri_robust_register and making use of the half-way space, resulting in an upright, forward facing head position

    Author: FreeSurfer Developers

    URL: https://github.com/freesurfer/freesurfer

    Args:
        params: The parameters.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    make_upright_validate(params)
    runner = runner if runner is not None else get_global_runner()
    execution = runner.start_execution(MAKE_UPRIGHT_METADATA)
    execution.params(params)
    args = make_upright_cargs(params, execution)
    out = make_upright_outputs(params, execution)
    execution.run(args)
    return out

def make_upright(
    input_image: InputPathType,
    output_image: str,
    transformation_map: InputPathType,
    runner: Runner | None = None,
) -> MakeUprightOutputs:
    """
    make_upright

    Registers MRI input to the left/right reversed version using mri_robust_register and making use of the half-way space, resulting in an upright, forward facing head position

    Author: FreeSurfer Developers

    URL: https://github.com/freesurfer/freesurfer

    Args:
        input_image: Input MRI image file in .mgz format
        output_image: Output MRI image file in .mgz format
        transformation_map: Transformation map file in .lta format
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    params = make_upright_params(
        input_image=input_image,
        output_image=output_image,
        transformation_map=transformation_map,
    )
    return make_upright_execute(params, runner)

__all__ = [
    "MakeUpright",
    "MakeUprightOutputs",
    "MAKE_UPRIGHT_METADATA",
    "make_upright_cargs",
    "make_upright_outputs",
    "make_upright_params",
    "make_upright_execute",
    "make_upright_validate",
    "make_upright",
]