# This file was auto generated by Styx.
# Do not edit this file directly.

import dataclasses
import pathlib
import typing

from styxdefs import Execution, InputPathType, Metadata, Runner, StyxValidationError, OutputPathType, get_global_runner

MRI_COMPUTE_OVERLAP_METADATA = Metadata(
    id="mri_compute_overlap",
    name="mri_compute_overlap",
    package="freesurfer",
)

MriComputeOverlap = typing.TypedDict(
    "MriComputeOverlap",
    {
        "@type": typing.NotRequired[typing.Literal["freesurfer/mri_compute_overlap"]],
        "volumes": list[InputPathType],
        "label_numbers": typing.NotRequired[list[str]],
        "all_labels": typing.NotRequired[bool],
        "show_label": typing.NotRequired[bool],
        "total_overlap": typing.NotRequired[bool],
        "no_summary": typing.NotRequired[bool],
        "mask": typing.NotRequired[InputPathType],
        "output_file": typing.NotRequired[str],
        "quiet_mode": typing.NotRequired[bool],
        "translate_label": typing.NotRequired[list[float]],
        "help": typing.NotRequired[bool],
    },
)

@dataclasses.dataclass
class MriComputeOverlapOutputs:
    """Output paths produced by the tool."""
    root: OutputPathType

def mri_compute_overlap_params(
    volumes: list[InputPathType],
    label_numbers: list[str] | None = None,
    all_labels: bool = False,
    show_label: bool = False,
    total_overlap: bool = False,
    no_summary: bool = False,
    mask: InputPathType | None = None,
    output_file: str | None = None,
    quiet_mode: bool = False,
    translate_label: list[float] | None = None,
    help: bool = False,
) -> MriComputeOverlap:
    """
    Build parameters.

    Args:
        volumes: Input volume files for which overlap measures are computed.
        label_numbers: List of specific label numbers for which to compute overlap\
            measures. If not specified, all labels are considered if -a is\
            provided.
        all_labels: Compute overlap for all labels.
        show_label: Show label name for segmentation.
        total_overlap: Compute the total overlap, which is the number of voxels\
            that are the same among all labels.
        no_summary: Do not compute total label summary.
        mask: Limit the domain of the calculation to the nonzero voxels in\
            specified volume.
        output_file: Filename to write results to.
        quiet_mode: Do not display results on standard display. If -l is specified,\
            this flag is automatically set.
        translate_label: Translate label l1 to label l2.
        help: Print help.

    Returns:
        Parameter dictionary.
    """
    params: MriComputeOverlap = {
        "@type": "freesurfer/mri_compute_overlap",
        "volumes": volumes,
        "all_labels": all_labels,
        "show_label": show_label,
        "total_overlap": total_overlap,
        "no_summary": no_summary,
        "quiet_mode": quiet_mode,
        "help": help,
    }
    if label_numbers is not None:
        params["label_numbers"] = label_numbers
    if mask is not None:
        params["mask"] = mask
    if output_file is not None:
        params["output_file"] = output_file
    if translate_label is not None:
        params["translate_label"] = translate_label
    return params

def mri_compute_overlap_validate(params: typing.Any) -> None:
    """Validate untrusted parameters. Raises StyxValidationError if `params` is not a valid MriComputeOverlap."""
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("volumes", None) is None:
        raise StyxValidationError("`volumes` must not be None")
    if not isinstance(params["volumes"], list):
        raise StyxValidationError(f'`volumes` has the wrong type: Received `{type(params["volumes"])}` expected `list[InputPathType]`')
    for e in params["volumes"]:
        if not isinstance(e, (pathlib.Path, str)):
            raise StyxValidationError(f'`volumes` has the wrong type: Received `{type(e)}` expected `list[InputPathType]`')
    if params.get("label_numbers", None) is not None:
        if not isinstance(params["label_numbers"], list):
            raise StyxValidationError(f'`label_numbers` has the wrong type: Received `{type(params["label_numbers"])}` expected `list[str]`')
        for e_2 in params["label_numbers"]:
            if not isinstance(e_2, str):
                raise StyxValidationError(f'`label_numbers` has the wrong type: Received `{type(e_2)}` expected `list[str]`')
    if params.get("all_labels", None) is not None:
        if not isinstance(params["all_labels"], bool):
            raise StyxValidationError(f'`all_labels` has the wrong type: Received `{type(params["all_labels"])}` expected `bool`')
    if params.get("show_label", None) is not None:
        if not isinstance(params["show_label"], bool):
            raise StyxValidationError(f'`show_label` has the wrong type: Received `{type(params["show_label"])}` expected `bool`')
    if params.get("total_overlap", None) is not None:
        if not isinstance(params["total_overlap"], bool):
            raise StyxValidationError(f'`total_overlap` has the wrong type: Received `{type(params["total_overlap"])}` expected `bool`')
    if params.get("no_summary", None) is not None:
        if not isinstance(params["no_summary"], bool):
            raise StyxValidationError(f'`no_summary` has the wrong type: Received `{type(params["no_summary"])}` expected `bool`')
    if params.get("mask", None) is not None:
        if not isinstance(params["mask"], (pathlib.Path, str)):
            raise StyxValidationError(f'`mask` has the wrong type: Received `{type(params["mask"])}` expected `InputPathType`')
    if params.get("output_file", None) is not None:
        if not isinstance(params["output_file"], str):
            raise StyxValidationError(f'`output_file` has the wrong type: Received `{type(params["output_file"])}` expected `str`')
    if params.get("quiet_mode", None) is not None:
        if not isinstance(params["quiet_mode"], bool):
            raise StyxValidationError(f'`quiet_mode` has the wrong type: Received `{type(params["quiet_mode"])}` expected `bool`')
    if params.get("translate_label", None) is not None:
        if not isinstance(params["translate_label"], list):
            raise StyxValidationError(f'`translate_label` has the wrong type: Received `{type(params["translate_label"])}` expected `list[float]`')
        if len(params["translate_label"]) > 2:
            raise StyxValidationError("Parameter `translate_label` must contain at most 2 elements")
        for e_3 in params["translate_label"]:
            if not isinstance(e_3, (float, int)):
                raise StyxValidationError(f'`translate_label` has the wrong type: Received `{type(e_3)}` expected `list[float]`')
    if params.get("help", None) is not None:
        if not isinstance(params["help"], bool):
            raise StyxValidationError(f'`help` has the wrong type: Received `{type(params["help"])}` expected `bool`')

def mri_compute_overlap_cargs(params: MriComputeOverlap, execution: Execution) -> list[str]:
    """Build command-line arguments from parameters."""
    cargs: list[str] = []
    cargs.append("mri_compute_overlap")
    for item0 in params["volumes"]:
        cargs.append(execution.input_file(item0))
    v_0 = params.get("label_numbers")
    if v_0 is not None:
        for item1 in v_0:
            cargs.append(item1)
    if params.get("all_labels"):
        cargs.append("-a")
    if params.get("show_label"):
        cargs.append("-s")
    if params.get("total_overlap"):
        cargs.append("-total")
    if params.get("no_summary"):
        cargs.append("-nosummary")
    v_1 = params.get("mask")
    if v_1 is not None:
        cargs.append("-mask")
        cargs.append(execution.input_file(v_1))
    v_2 = params.get("output_file")
    if v_2 is not None:
        cargs.append("-l")
        cargs.append(v_2)
    if params.get("quiet_mode"):
        cargs.append("-q")
    v_3 = params.get("translate_label")
    if v_3 is not None:
        cargs.append("-t")
        for item2 in v_3:
            cargs.append(str(item2))
    if params.get("help"):
        cargs.append("-h")
    return cargs

def mri_compute_overlap_outputs(params: MriComputeOverlap, execution: Execution) -> MriComputeOverlapOutputs:
    """Build the MriComputeOverlapOutputs object for this tool."""
    root_v: OutputPathType = execution.output_file(".")
    return MriComputeOverlapOutputs(
        root=root_v,
    )

def mri_compute_overlap_execute(params: MriComputeOverlap, runner: Runner | None = None) -> MriComputeOverlapOutputs:
    """
    mri_compute_overlap

    Computes three different types of overlap measures for labels in input volumes.

    Author: FreeSurfer Developers

    URL: https://github.com/freesurfer/freesurfer

    Args:
        params: The parameters.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    mri_compute_overlap_validate(params)
    runner = runner if runner is not None else get_global_runner()
    execution = runner.start_execution(MRI_COMPUTE_OVERLAP_METADATA)
    execution.params(params)
    args = mri_compute_overlap_cargs(params, execution)
    out = mri_compute_overlap_outputs(params, execution)
    execution.run(args)
    return out

def mri_compute_overlap(
    volumes: list[InputPathType],
    label_numbers: list[str] | None = None,
    all_labels: bool = False,
    show_label: bool = False,
    total_overlap: bool = False,
    no_summary: bool = False,
    mask: InputPathType | None = None,
    output_file: str | None = None,
    quiet_mode: bool = False,
    translate_label: list[float] | None = None,
    help: bool = False,
    runner: Runner | None = None,
) -> MriComputeOverlapOutputs:
    """
    mri_compute_overlap

    Computes three different types of overlap measures for labels in input volumes.

    Author: FreeSurfer Developers

    URL: https://github.com/freesurfer/freesurfer

    Args:
        volumes: Input volume files for which overlap measures are computed.
        label_numbers: List of specific label numbers for which to compute overlap\
            measures. If not specified, all labels are considered if -a is\
            provided.
        all_labels: Compute overlap for all labels.
        show_label: Show label name for segmentation.
        total_overlap: Compute the total overlap, which is the number of voxels\
            that are the same among all labels.
        no_summary: Do not compute total label summary.
        mask: Limit the domain of the calculation to the nonzero voxels in\
            specified volume.
        output_file: Filename to write results to.
        quiet_mode: Do not display results on standard display. If -l is specified,\
            this flag is automatically set.
        translate_label: Translate label l1 to label l2.
        help: Print help.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    params = mri_compute_overlap_params(
        volumes=volumes,
        label_numbers=label_numbers,
        all_labels=all_labels,
        show_label=show_label,
        total_overlap=total_overlap,
        no_summary=no_summary,
        mask=mask,
        output_file=output_file,
        quiet_mode=quiet_mode,
        translate_label=translate_label,
        help=help,
    )
    return mri_compute_overlap_execute(params, runner)

__all__ = [
    "MriComputeOverlap",
    "MriComputeOverlapOutputs",
    "MRI_COMPUTE_OVERLAP_METADATA",
    "mri_compute_overlap_cargs",
    "mri_compute_overlap_outputs",
    "mri_compute_overlap_params",
    "mri_compute_overlap_execute",
    "mri_compute_overlap_validate",
    "mri_compute_overlap",
]