# This file was auto generated by Styx.
# Do not edit this file directly.

import dataclasses
import pathlib
import typing

from styxdefs import Execution, InputPathType, Metadata, Runner, StyxValidationError, OutputPathType, get_global_runner

MRI_HISTO_EQ_METADATA = Metadata(
    id="mri_histo_eq",
    name="mri_histo_eq",
    package="freesurfer",
)

MriHistoEq = typing.TypedDict(
    "MriHistoEq",
    {
        "@type": typing.NotRequired[typing.Literal["freesurfer/mri_histo_eq"]],
        "input_volume_1": InputPathType,
        "input_volume_2": InputPathType,
    },
)

@dataclasses.dataclass
class MriHistoEqOutputs:
    """Output paths produced by the tool."""
    root: OutputPathType

def mri_histo_eq_params(
    input_volume_1: InputPathType,
    input_volume_2: InputPathType,
) -> MriHistoEq:
    """
    Build parameters.

    Args:
        input_volume_1: Input volume 1
        input_volume_2: Input volume 2

    Returns:
        Parameter dictionary.
    """
    params: MriHistoEq = {
        "@type": "freesurfer/mri_histo_eq",
        "input_volume_1": input_volume_1,
        "input_volume_2": input_volume_2,
    }
    return params

def mri_histo_eq_validate(params: typing.Any) -> None:
    """Validate untrusted parameters. Raises StyxValidationError if `params` is not a valid MriHistoEq."""
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("input_volume_1", None) is None:
        raise StyxValidationError("`input_volume_1` must not be None")
    if not isinstance(params["input_volume_1"], (pathlib.Path, str)):
        raise StyxValidationError(f'`input_volume_1` has the wrong type: Received `{type(params["input_volume_1"])}` expected `InputPathType`')
    if params.get("input_volume_2", None) is None:
        raise StyxValidationError("`input_volume_2` must not be None")
    if not isinstance(params["input_volume_2"], (pathlib.Path, str)):
        raise StyxValidationError(f'`input_volume_2` has the wrong type: Received `{type(params["input_volume_2"])}` expected `InputPathType`')

def mri_histo_eq_cargs(params: MriHistoEq, execution: Execution) -> list[str]:
    """Build command-line arguments from parameters."""
    cargs: list[str] = []
    cargs.append("mri_histo_eq")
    cargs.append(execution.input_file(params["input_volume_1"]))
    cargs.append(execution.input_file(params["input_volume_2"]))
    return cargs

def mri_histo_eq_outputs(params: MriHistoEq, execution: Execution) -> MriHistoEqOutputs:
    """Build the MriHistoEqOutputs object for this tool."""
    root_v: OutputPathType = execution.output_file(".")
    return MriHistoEqOutputs(
        root=root_v,
    )

def mri_histo_eq_execute(params: MriHistoEq, runner: Runner | None = None) -> MriHistoEqOutputs:
    """
    mri_histo_eq

    MRI histogram equalization tool from Freesurfer

    Author: FreeSurfer Developers

    URL: https://github.com/freesurfer/freesurfer

    Args:
        params: The parameters.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    mri_histo_eq_validate(params)
    runner = runner if runner is not None else get_global_runner()
    execution = runner.start_execution(MRI_HISTO_EQ_METADATA)
    execution.params(params)
    args = mri_histo_eq_cargs(params, execution)
    out = mri_histo_eq_outputs(params, execution)
    execution.run(args)
    return out

def mri_histo_eq(
    input_volume_1: InputPathType,
    input_volume_2: InputPathType,
    runner: Runner | None = None,
) -> MriHistoEqOutputs:
    """
    mri_histo_eq

    MRI histogram equalization tool from Freesurfer

    Author: FreeSurfer Developers

    URL: https://github.com/freesurfer/freesurfer

    Args:
        input_volume_1: Input volume 1
        input_volume_2: Input volume 2
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    params = mri_histo_eq_params(
        input_volume_1=input_volume_1,
        input_volume_2=input_volume_2,
    )
    return mri_histo_eq_execute(params, runner)

__all__ = [
    "MriHistoEq",
    "MriHistoEqOutputs",
    "MRI_HISTO_EQ_METADATA",
    "mri_histo_eq_cargs",
    "mri_histo_eq_outputs",
    "mri_histo_eq_params",
    "mri_histo_eq_execute",
    "mri_histo_eq_validate",
    "mri_histo_eq",
]