# This file was auto generated by Styx.
# Do not edit this file directly.

import dataclasses
import pathlib
import typing

from styxdefs import Execution, InputPathType, Metadata, Runner, StyxValidationError, OutputPathType, get_global_runner

MRI_RELABEL_NONWM_HYPOS_METADATA = Metadata(
    id="mri_relabel_nonwm_hypos",
    name="mri_relabel_nonwm_hypos",
    package="freesurfer",
)

MriRelabelNonwmHypos = typing.TypedDict(
    "MriRelabelNonwmHypos",
    {
        "@type": typing.NotRequired[typing.Literal["freesurfer/mri_relabel_nonwm_hypos"]],
        "inputseg": InputPathType,
        "outputseg": str,
        "segments": typing.NotRequired[list[str]],
        "seg_default": typing.NotRequired[bool],
        "debug": typing.NotRequired[bool],
        "checkopts": typing.NotRequired[bool],
    },
)

@dataclasses.dataclass
class MriRelabelNonwmHyposOutputs:
    """Output paths produced by the tool."""
    root: OutputPathType
    out_segmentation: OutputPathType
    """Output segmentation with non-WM hypointensities relabeled."""

def mri_relabel_nonwm_hypos_params(
    inputseg: InputPathType,
    outputseg: str,
    segments: list[str] | None = None,
    seg_default: bool = False,
    debug: bool = False,
    checkopts: bool = False,
) -> MriRelabelNonwmHypos:
    """
    Build parameters.

    Args:
        inputseg: Input segmentation file with non-wm-hypos labeled as 80, 81, or\
            82.
        outputseg: Output segmentation file with non-wm-hypos relabeled.
        segments: Label hypos adjacent to specified segment as a new segment (can\
            be used multiple times).
        seg_default: Use the default relabeling scheme.
        debug: Turn on debugging.
        checkopts: Don't run anything, just check options and exit.

    Returns:
        Parameter dictionary.
    """
    params: MriRelabelNonwmHypos = {
        "@type": "freesurfer/mri_relabel_nonwm_hypos",
        "inputseg": inputseg,
        "outputseg": outputseg,
        "seg_default": seg_default,
        "debug": debug,
        "checkopts": checkopts,
    }
    if segments is not None:
        params["segments"] = segments
    return params

def mri_relabel_nonwm_hypos_validate(params: typing.Any) -> None:
    """Validate untrusted parameters. Raises StyxValidationError if `params` is not a valid MriRelabelNonwmHypos."""
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("inputseg", None) is None:
        raise StyxValidationError("`inputseg` must not be None")
    if not isinstance(params["inputseg"], (pathlib.Path, str)):
        raise StyxValidationError(f'`inputseg` has the wrong type: Received `{type(params["inputseg"])}` expected `InputPathType`')
    if params.get("outputseg", None) is None:
        raise StyxValidationError("`outputseg` must not be None")
    if not isinstance(params["outputseg"], str):
        raise StyxValidationError(f'`outputseg` has the wrong type: Received `{type(params["outputseg"])}` expected `str`')
    if params.get("segments", None) is not None:
        if not isinstance(params["segments"], list):
            raise StyxValidationError(f'`segments` has the wrong type: Received `{type(params["segments"])}` expected `list[str]`')
        for e in params["segments"]:
            if not isinstance(e, str):
                raise StyxValidationError(f'`segments` has the wrong type: Received `{type(e)}` expected `list[str]`')
    if params.get("seg_default", None) is not None:
        if not isinstance(params["seg_default"], bool):
            raise StyxValidationError(f'`seg_default` has the wrong type: Received `{type(params["seg_default"])}` expected `bool`')
    if params.get("debug", None) is not None:
        if not isinstance(params["debug"], bool):
            raise StyxValidationError(f'`debug` has the wrong type: Received `{type(params["debug"])}` expected `bool`')
    if params.get("checkopts", None) is not None:
        if not isinstance(params["checkopts"], bool):
            raise StyxValidationError(f'`checkopts` has the wrong type: Received `{type(params["checkopts"])}` expected `bool`')

def mri_relabel_nonwm_hypos_cargs(params: MriRelabelNonwmHypos, execution: Execution) -> list[str]:
    """Build command-line arguments from parameters."""
    cargs: list[str] = []
    cargs.append("mri_relabel_nonwm_hypos")
    cargs.append("-i")
    cargs.append(execution.input_file(params["inputseg"]))
    cargs.append("-o")
    cargs.append(params["outputseg"])
    v_0 = params.get("segments")
    if v_0 is not None:
        cargs.append("--seg")
        for item0 in v_0:
            cargs.append(item0)
    if params.get("seg_default"):
        cargs.append("--seg-default")
    if params.get("debug"):
        cargs.append("--debug")
    if params.get("checkopts"):
        cargs.append("--checkopts")
    return cargs

def mri_relabel_nonwm_hypos_outputs(params: MriRelabelNonwmHypos, execution: Execution) -> MriRelabelNonwmHyposOutputs:
    """Build the MriRelabelNonwmHyposOutputs object for this tool."""
    root_v: OutputPathType = execution.output_file(".")
    out_segmentation_v: OutputPathType = execution.output_file(params["outputseg"])
    return MriRelabelNonwmHyposOutputs(
        root=root_v,
        out_segmentation=out_segmentation_v,
    )

def mri_relabel_nonwm_hypos_execute(params: MriRelabelNonwmHypos, runner: Runner | None = None) -> MriRelabelNonwmHyposOutputs:
    """
    mri_relabel_nonwm_hypos

    Relabels non-WM hypointensities based on proximity to a nearby label.

    Author: FreeSurfer Developers

    URL: https://github.com/freesurfer/freesurfer

    Args:
        params: The parameters.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    mri_relabel_nonwm_hypos_validate(params)
    runner = runner if runner is not None else get_global_runner()
    execution = runner.start_execution(MRI_RELABEL_NONWM_HYPOS_METADATA)
    execution.params(params)
    args = mri_relabel_nonwm_hypos_cargs(params, execution)
    out = mri_relabel_nonwm_hypos_outputs(params, execution)
    execution.run(args)
    return out

def mri_relabel_nonwm_hypos(
    inputseg: InputPathType,
    outputseg: str,
    segments: list[str] | None = None,
    seg_default: bool = False,
    debug: bool = False,
    checkopts: bool = False,
    runner: Runner | None = None,
) -> MriRelabelNonwmHyposOutputs:
    """
    mri_relabel_nonwm_hypos

    Relabels non-WM hypointensities based on proximity to a nearby label.

    Author: FreeSurfer Developers

    URL: https://github.com/freesurfer/freesurfer

    Args:
        inputseg: Input segmentation file with non-wm-hypos labeled as 80, 81, or\
            82.
        outputseg: Output segmentation file with non-wm-hypos relabeled.
        segments: Label hypos adjacent to specified segment as a new segment (can\
            be used multiple times).
        seg_default: Use the default relabeling scheme.
        debug: Turn on debugging.
        checkopts: Don't run anything, just check options and exit.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    params = mri_relabel_nonwm_hypos_params(
        inputseg=inputseg,
        outputseg=outputseg,
        segments=segments,
        seg_default=seg_default,
        debug=debug,
        checkopts=checkopts,
    )
    return mri_relabel_nonwm_hypos_execute(params, runner)

__all__ = [
    "MriRelabelNonwmHypos",
    "MriRelabelNonwmHyposOutputs",
    "MRI_RELABEL_NONWM_HYPOS_METADATA",
    "mri_relabel_nonwm_hypos_cargs",
    "mri_relabel_nonwm_hypos_outputs",
    "mri_relabel_nonwm_hypos_params",
    "mri_relabel_nonwm_hypos_execute",
    "mri_relabel_nonwm_hypos_validate",
    "mri_relabel_nonwm_hypos",
]