# This file was auto generated by Styx.
# Do not edit this file directly.

import dataclasses
import pathlib
import typing

from styxdefs import Execution, InputPathType, Metadata, Runner, StyxValidationError, OutputPathType, get_global_runner

MRI_CA_REGISTER_METADATA = Metadata(
    id="mri_ca_register",
    name="mri_ca_register",
    package="freesurfer",
)

MriCaRegister = typing.TypedDict(
    "MriCaRegister",
    {
        "@type": typing.NotRequired[typing.Literal["freesurfer/mri_ca_register"]],
        "input_volume": InputPathType,
        "template": InputPathType,
        "output_volume": str,
        "tolerance": typing.NotRequired[float],
        "mask": typing.NotRequired[InputPathType],
        "transform_lta": typing.NotRequired[InputPathType],
        "level": typing.NotRequired[float],
        "read_intensity": typing.NotRequired[bool],
        "align": typing.NotRequired[bool],
        "invert_save_file": typing.NotRequired[str],
        "distance": typing.NotRequired[float],
        "regularize": typing.NotRequired[float],
        "regularize_mean": typing.NotRequired[float],
        "scale_smoothness": typing.NotRequired[float],
        "nobright": typing.NotRequired[bool],
        "renormalize_map": typing.NotRequired[bool],
        "renormalize": typing.NotRequired[InputPathType],
        "read_lta": typing.NotRequired[bool],
        "smoothness": typing.NotRequired[float],
        "samples": typing.NotRequired[float],
        "nsmall": typing.NotRequired[float],
        "fixed": typing.NotRequired[bool],
        "optimal": typing.NotRequired[bool],
        "noneg": typing.NotRequired[bool],
        "wm": typing.NotRequired[bool],
        "min_avgs": typing.NotRequired[float],
        "transform_limit": typing.NotRequired[float],
        "relabel": typing.NotRequired[float],
        "relabel_avgs": typing.NotRequired[float],
        "reset_avgs": typing.NotRequired[float],
        "vf_file": typing.NotRequired[str],
        "diag_file": typing.NotRequired[str],
        "tr": typing.NotRequired[float],
        "te": typing.NotRequired[float],
        "example": typing.NotRequired[str],
        "bigventricles": typing.NotRequired[bool],
        "uncompress": typing.NotRequired[bool],
        "second_pass_renorm": typing.NotRequired[bool],
        "threads": typing.NotRequired[float],
    },
)

@dataclasses.dataclass
class MriCaRegisterOutputs:
    """Output paths produced by the tool."""
    root: OutputPathType
    output_file: OutputPathType
    """Multidimensional transform in m3d format"""

def mri_ca_register_params(
    input_volume: InputPathType,
    template: InputPathType,
    output_volume: str,
    tolerance: float | None = None,
    mask: InputPathType | None = None,
    transform_lta: InputPathType | None = None,
    level: float | None = None,
    read_intensity: bool = False,
    align: bool = False,
    invert_save_file: str | None = None,
    distance: float | None = None,
    regularize: float | None = None,
    regularize_mean: float | None = None,
    scale_smoothness: float | None = None,
    nobright: bool = False,
    renormalize_map: bool = False,
    renormalize: InputPathType | None = None,
    read_lta: bool = False,
    smoothness: float | None = None,
    samples: float | None = None,
    nsmall: float | None = None,
    fixed: bool = False,
    optimal: bool = False,
    noneg: bool = False,
    wm: bool = False,
    min_avgs: float | None = None,
    transform_limit: float | None = None,
    relabel: float | None = None,
    relabel_avgs: float | None = None,
    reset_avgs: float | None = None,
    vf_file: str | None = None,
    diag_file: str | None = None,
    tr: float | None = None,
    te: float | None = None,
    example: str | None = None,
    bigventricles: bool = False,
    uncompress: bool = False,
    second_pass_renorm: bool = False,
    threads: float | None = None,
) -> MriCaRegister:
    """
    Build parameters.

    Args:
        input_volume: Input volume
        template: Template in GCA format
        output_volume: Output volume in M3D format
        tolerance: Defines convergence of registration
        mask: Specifies volume to use as a mask
        transform_lta: Transform in LTA format
        level: Defines how many surrounding voxels will be used in interpolations,\
            default is 6
        read_intensity: Allows reading of multiple intensity normalization
        align: Enable alignment
        invert_save_file: Invert and save as GCAM file
        distance: Distance for registration
        regularize: Regularization parameter
        regularize_mean: Mean regularization
        scale_smoothness: Smoothness scaling factor
        nobright: Disable brightness adjustment
        renormalize_map: Renormalize using map
        renormalize: Renormalize with intensity file
        read_lta: Use LTA file for registration
        smoothness: Smoothness parameter
        samples: Sample points for registration
        nsmall: Number of small features
        fixed: Fixed mode for registration
        optimal: Optimal registration settings
        noneg: Disallow negative values
        wm: White matter flag
        min_avgs: Minimum number of averages
        transform_limit: Transform limit
        relabel: Relabel options
        relabel_avgs: Relabel averages
        reset_avgs: Reset averages
        vf_file: VF file name
        diag_file: Diagnostic file name
        tr: TR parameter
        te: TE parameter
        example: Example file
        bigventricles: Handle big ventricles
        uncompress: Uncompress files
        second_pass_renorm: Second pass renormalization
        threads: Number of threads

    Returns:
        Parameter dictionary.
    """
    params: MriCaRegister = {
        "@type": "freesurfer/mri_ca_register",
        "input_volume": input_volume,
        "template": template,
        "output_volume": output_volume,
        "read_intensity": read_intensity,
        "align": align,
        "nobright": nobright,
        "renormalize_map": renormalize_map,
        "read_lta": read_lta,
        "fixed": fixed,
        "optimal": optimal,
        "noneg": noneg,
        "wm": wm,
        "bigventricles": bigventricles,
        "uncompress": uncompress,
        "second_pass_renorm": second_pass_renorm,
    }
    if tolerance is not None:
        params["tolerance"] = tolerance
    if mask is not None:
        params["mask"] = mask
    if transform_lta is not None:
        params["transform_lta"] = transform_lta
    if level is not None:
        params["level"] = level
    if invert_save_file is not None:
        params["invert_save_file"] = invert_save_file
    if distance is not None:
        params["distance"] = distance
    if regularize is not None:
        params["regularize"] = regularize
    if regularize_mean is not None:
        params["regularize_mean"] = regularize_mean
    if scale_smoothness is not None:
        params["scale_smoothness"] = scale_smoothness
    if renormalize is not None:
        params["renormalize"] = renormalize
    if smoothness is not None:
        params["smoothness"] = smoothness
    if samples is not None:
        params["samples"] = samples
    if nsmall is not None:
        params["nsmall"] = nsmall
    if min_avgs is not None:
        params["min_avgs"] = min_avgs
    if transform_limit is not None:
        params["transform_limit"] = transform_limit
    if relabel is not None:
        params["relabel"] = relabel
    if relabel_avgs is not None:
        params["relabel_avgs"] = relabel_avgs
    if reset_avgs is not None:
        params["reset_avgs"] = reset_avgs
    if vf_file is not None:
        params["vf_file"] = vf_file
    if diag_file is not None:
        params["diag_file"] = diag_file
    if tr is not None:
        params["tr"] = tr
    if te is not None:
        params["te"] = te
    if example is not None:
        params["example"] = example
    if threads is not None:
        params["threads"] = threads
    return params

def mri_ca_register_validate(params: typing.Any) -> None:
    """Validate untrusted parameters. Raises StyxValidationError if `params` is not a valid MriCaRegister."""
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("input_volume", None) is None:
        raise StyxValidationError("`input_volume` must not be None")
    if not isinstance(params["input_volume"], (pathlib.Path, str)):
        raise StyxValidationError(f'`input_volume` has the wrong type: Received `{type(params["input_volume"])}` expected `InputPathType`')
    if params.get("template", None) is None:
        raise StyxValidationError("`template` must not be None")
    if not isinstance(params["template"], (pathlib.Path, str)):
        raise StyxValidationError(f'`template` has the wrong type: Received `{type(params["template"])}` expected `InputPathType`')
    if params.get("output_volume", None) is None:
        raise StyxValidationError("`output_volume` must not be None")
    if not isinstance(params["output_volume"], str):
        raise StyxValidationError(f'`output_volume` has the wrong type: Received `{type(params["output_volume"])}` expected `str`')
    if params.get("tolerance", None) is not None:
        if not isinstance(params["tolerance"], (float, int)):
            raise StyxValidationError(f'`tolerance` has the wrong type: Received `{type(params["tolerance"])}` expected `float`')
    if params.get("mask", None) is not None:
        if not isinstance(params["mask"], (pathlib.Path, str)):
            raise StyxValidationError(f'`mask` has the wrong type: Received `{type(params["mask"])}` expected `InputPathType`')
    if params.get("transform_lta", None) is not None:
        if not isinstance(params["transform_lta"], (pathlib.Path, str)):
            raise StyxValidationError(f'`transform_lta` has the wrong type: Received `{type(params["transform_lta"])}` expected `InputPathType`')
    if params.get("level", None) is not None:
        if not isinstance(params["level"], (float, int)):
            raise StyxValidationError(f'`level` has the wrong type: Received `{type(params["level"])}` expected `float`')
    if params.get("read_intensity", None) is not None:
        if not isinstance(params["read_intensity"], bool):
            raise StyxValidationError(f'`read_intensity` has the wrong type: Received `{type(params["read_intensity"])}` expected `bool`')
    if params.get("align", None) is not None:
        if not isinstance(params["align"], bool):
            raise StyxValidationError(f'`align` has the wrong type: Received `{type(params["align"])}` expected `bool`')
    if params.get("invert_save_file", None) is not None:
        if not isinstance(params["invert_save_file"], str):
            raise StyxValidationError(f'`invert_save_file` has the wrong type: Received `{type(params["invert_save_file"])}` expected `str`')
    if params.get("distance", None) is not None:
        if not isinstance(params["distance"], (float, int)):
            raise StyxValidationError(f'`distance` has the wrong type: Received `{type(params["distance"])}` expected `float`')
    if params.get("regularize", None) is not None:
        if not isinstance(params["regularize"], (float, int)):
            raise StyxValidationError(f'`regularize` has the wrong type: Received `{type(params["regularize"])}` expected `float`')
    if params.get("regularize_mean", None) is not None:
        if not isinstance(params["regularize_mean"], (float, int)):
            raise StyxValidationError(f'`regularize_mean` has the wrong type: Received `{type(params["regularize_mean"])}` expected `float`')
    if params.get("scale_smoothness", None) is not None:
        if not isinstance(params["scale_smoothness"], (float, int)):
            raise StyxValidationError(f'`scale_smoothness` has the wrong type: Received `{type(params["scale_smoothness"])}` expected `float`')
    if params.get("nobright", None) is not None:
        if not isinstance(params["nobright"], bool):
            raise StyxValidationError(f'`nobright` has the wrong type: Received `{type(params["nobright"])}` expected `bool`')
    if params.get("renormalize_map", None) is not None:
        if not isinstance(params["renormalize_map"], bool):
            raise StyxValidationError(f'`renormalize_map` has the wrong type: Received `{type(params["renormalize_map"])}` expected `bool`')
    if params.get("renormalize", None) is not None:
        if not isinstance(params["renormalize"], (pathlib.Path, str)):
            raise StyxValidationError(f'`renormalize` has the wrong type: Received `{type(params["renormalize"])}` expected `InputPathType`')
    if params.get("read_lta", None) is not None:
        if not isinstance(params["read_lta"], bool):
            raise StyxValidationError(f'`read_lta` has the wrong type: Received `{type(params["read_lta"])}` expected `bool`')
    if params.get("smoothness", None) is not None:
        if not isinstance(params["smoothness"], (float, int)):
            raise StyxValidationError(f'`smoothness` has the wrong type: Received `{type(params["smoothness"])}` expected `float`')
    if params.get("samples", None) is not None:
        if not isinstance(params["samples"], (float, int)):
            raise StyxValidationError(f'`samples` has the wrong type: Received `{type(params["samples"])}` expected `float`')
    if params.get("nsmall", None) is not None:
        if not isinstance(params["nsmall"], (float, int)):
            raise StyxValidationError(f'`nsmall` has the wrong type: Received `{type(params["nsmall"])}` expected `float`')
    if params.get("fixed", None) is not None:
        if not isinstance(params["fixed"], bool):
            raise StyxValidationError(f'`fixed` has the wrong type: Received `{type(params["fixed"])}` expected `bool`')
    if params.get("optimal", None) is not None:
        if not isinstance(params["optimal"], bool):
            raise StyxValidationError(f'`optimal` has the wrong type: Received `{type(params["optimal"])}` expected `bool`')
    if params.get("noneg", None) is not None:
        if not isinstance(params["noneg"], bool):
            raise StyxValidationError(f'`noneg` has the wrong type: Received `{type(params["noneg"])}` expected `bool`')
    if params.get("wm", None) is not None:
        if not isinstance(params["wm"], bool):
            raise StyxValidationError(f'`wm` has the wrong type: Received `{type(params["wm"])}` expected `bool`')
    if params.get("min_avgs", None) is not None:
        if not isinstance(params["min_avgs"], (float, int)):
            raise StyxValidationError(f'`min_avgs` has the wrong type: Received `{type(params["min_avgs"])}` expected `float`')
    if params.get("transform_limit", None) is not None:
        if not isinstance(params["transform_limit"], (float, int)):
            raise StyxValidationError(f'`transform_limit` has the wrong type: Received `{type(params["transform_limit"])}` expected `float`')
    if params.get("relabel", None) is not None:
        if not isinstance(params["relabel"], (float, int)):
            raise StyxValidationError(f'`relabel` has the wrong type: Received `{type(params["relabel"])}` expected `float`')
    if params.get("relabel_avgs", None) is not None:
        if not isinstance(params["relabel_avgs"], (float, int)):
            raise StyxValidationError(f'`relabel_avgs` has the wrong type: Received `{type(params["relabel_avgs"])}` expected `float`')
    if params.get("reset_avgs", None) is not None:
        if not isinstance(params["reset_avgs"], (float, int)):
            raise StyxValidationError(f'`reset_avgs` has the wrong type: Received `{type(params["reset_avgs"])}` expected `float`')
    if params.get("vf_file", None) is not None:
        if not isinstance(params["vf_file"], str):
            raise StyxValidationError(f'`vf_file` has the wrong type: Received `{type(params["vf_file"])}` expected `str`')
    if params.get("diag_file", None) is not None:
        if not isinstance(params["diag_file"], str):
            raise StyxValidationError(f'`diag_file` has the wrong type: Received `{type(params["diag_file"])}` expected `str`')
    if params.get("tr", None) is not None:
        if not isinstance(params["tr"], (float, int)):
            raise StyxValidationError(f'`tr` has the wrong type: Received `{type(params["tr"])}` expected `float`')
    if params.get("te", None) is not None:
        if not isinstance(params["te"], (float, int)):
            raise StyxValidationError(f'`te` has the wrong type: Received `{type(params["te"])}` expected `float`')
    if params.get("example", None) is not None:
        if not isinstance(params["example"], str):
            raise StyxValidationError(f'`example` has the wrong type: Received `{type(params["example"])}` expected `str`')
    if params.get("bigventricles", None) is not None:
        if not isinstance(params["bigventricles"], bool):
            raise StyxValidationError(f'`bigventricles` has the wrong type: Received `{type(params["bigventricles"])}` expected `bool`')
    if params.get("uncompress", None) is not None:
        if not isinstance(params["uncompress"], bool):
            raise StyxValidationError(f'`uncompress` has the wrong type: Received `{type(params["uncompress"])}` expected `bool`')
    if params.get("second_pass_renorm", None) is not None:
        if not isinstance(params["second_pass_renorm"], bool):
            raise StyxValidationError(f'`second_pass_renorm` has the wrong type: Received `{type(params["second_pass_renorm"])}` expected `bool`')
    if params.get("threads", None) is not None:
        if not isinstance(params["threads"], (float, int)):
            raise StyxValidationError(f'`threads` has the wrong type: Received `{type(params["threads"])}` expected `float`')

def mri_ca_register_cargs(params: MriCaRegister, execution: Execution) -> list[str]:
    """Build command-line arguments from parameters."""
    cargs: list[str] = []
    cargs.append("mri_ca_register")
    cargs.append(execution.input_file(params["input_volume"]))
    cargs.append(execution.input_file(params["template"]))
    cargs.append(params["output_volume"])
    v_0 = params.get("tolerance")
    if v_0 is not None:
        cargs.append("-tol")
        cargs.append(str(v_0))
    v_1 = params.get("mask")
    if v_1 is not None:
        cargs.append("-mask")
        cargs.append(execution.input_file(v_1))
    v_2 = params.get("transform_lta")
    if v_2 is not None:
        cargs.append("-T")
        cargs.append(execution.input_file(v_2))
    v_3 = params.get("level")
    if v_3 is not None:
        cargs.append("-level")
        cargs.append(str(v_3))
    if params.get("read_intensity"):
        cargs.append("-ri")
    if params.get("align"):
        cargs.append("-align")
    v_4 = params.get("invert_save_file")
    if v_4 is not None:
        cargs.append("-invert-and-save")
        cargs.append(v_4)
    v_5 = params.get("distance")
    if v_5 is not None:
        cargs.append("-dist")
        cargs.append(str(v_5))
    v_6 = params.get("regularize")
    if v_6 is not None:
        cargs.append("-regularize")
        cargs.append(str(v_6))
    v_7 = params.get("regularize_mean")
    if v_7 is not None:
        cargs.append("-regularize-mean")
        cargs.append(str(v_7))
    v_8 = params.get("scale_smoothness")
    if v_8 is not None:
        cargs.append("-scale_smoothness")
        cargs.append(str(v_8))
    if params.get("nobright"):
        cargs.append("-nobright")
    if params.get("renormalize_map"):
        cargs.append("-renormalize_map")
    v_9 = params.get("renormalize")
    if v_9 is not None:
        cargs.append("-renormalize")
        cargs.append(execution.input_file(v_9))
    if params.get("read_lta"):
        cargs.append("-read_lta")
    v_10 = params.get("smoothness")
    if v_10 is not None:
        cargs.append("-smoothness")
        cargs.append(str(v_10))
    v_11 = params.get("samples")
    if v_11 is not None:
        cargs.append("-samples")
        cargs.append(str(v_11))
    v_12 = params.get("nsmall")
    if v_12 is not None:
        cargs.append("-nsmall")
        cargs.append(str(v_12))
    if params.get("fixed"):
        cargs.append("-fixed")
    if params.get("optimal"):
        cargs.append("-optimal")
    if params.get("noneg"):
        cargs.append("-noneg")
    if params.get("wm"):
        cargs.append("-wm")
    v_13 = params.get("min_avgs")
    if v_13 is not None:
        cargs.append("-min_avgs")
        cargs.append(str(v_13))
    v_14 = params.get("transform_limit")
    if v_14 is not None:
        cargs.append("-tl")
        cargs.append(str(v_14))
    v_15 = params.get("relabel")
    if v_15 is not None:
        cargs.append("-relabel")
        cargs.append(str(v_15))
    v_16 = params.get("relabel_avgs")
    if v_16 is not None:
        cargs.append("-relabel_avgs")
        cargs.append(str(v_16))
    v_17 = params.get("reset_avgs")
    if v_17 is not None:
        cargs.append("-reset_avgs")
        cargs.append(str(v_17))
    v_18 = params.get("vf_file")
    if v_18 is not None:
        cargs.append("-vf")
        cargs.append(v_18)
    v_19 = params.get("diag_file")
    if v_19 is not None:
        cargs.append("-diag")
        cargs.append(v_19)
    v_20 = params.get("tr")
    if v_20 is not None:
        cargs.append("-tr")
        cargs.append(str(v_20))
    v_21 = params.get("te")
    if v_21 is not None:
        cargs.append("-te")
        cargs.append(str(v_21))
    v_22 = params.get("example")
    if v_22 is not None:
        cargs.append("-example")
        cargs.append(v_22)
    if params.get("bigventricles"):
        cargs.append("-<no>bigventricles")
    if params.get("uncompress"):
        cargs.append("-uncompress")
    if params.get("second_pass_renorm"):
        cargs.append("-secondpassrenorm")
    v_23 = params.get("threads")
    if v_23 is not None:
        cargs.append("-threads")
        cargs.append(str(v_23))
    return cargs

def mri_ca_register_outputs(params: MriCaRegister, execution: Execution) -> MriCaRegisterOutputs:
    """Build the MriCaRegisterOutputs object for this tool."""
    root_v: OutputPathType = execution.output_file(".")
    output_file_v: OutputPathType = execution.output_file(f'{params["output_volume"]}.m3d')
    return MriCaRegisterOutputs(
        root=root_v,
        output_file=output_file_v,
    )

def mri_ca_register_execute(params: MriCaRegister, runner: Runner | None = None) -> MriCaRegisterOutputs:
    """
    mri_ca_register

    Generates a multi-dimensional talairach transform from a gca file and talairach.lta file

    Author: FreeSurfer Developers

    URL: https://github.com/freesurfer/freesurfer

    Args:
        params: The parameters.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    mri_ca_register_validate(params)
    runner = runner if runner is not None else get_global_runner()
    execution = runner.start_execution(MRI_CA_REGISTER_METADATA)
    execution.params(params)
    args = mri_ca_register_cargs(params, execution)
    out = mri_ca_register_outputs(params, execution)
    execution.run(args)
    return out

def mri_ca_register(
    input_volume: InputPathType,
    template: InputPathType,
    output_volume: str,
    tolerance: float | None = None,
    mask: InputPathType | None = None,
    transform_lta: InputPathType | None = None,
    level: float | None = None,
    read_intensity: bool = False,
    align: bool = False,
    invert_save_file: str | None = None,
    distance: float | None = None,
    regularize: float | None = None,
    regularize_mean: float | None = None,
    scale_smoothness: float | None = None,
    nobright: bool = False,
    renormalize_map: bool = False,
    renormalize: InputPathType | None = None,
    read_lta: bool = False,
    smoothness: float | None = None,
    samples: float | None = None,
    nsmall: float | None = None,
    fixed: bool = False,
    optimal: bool = False,
    noneg: bool = False,
    wm: bool = False,
    min_avgs: float | None = None,
    transform_limit: float | None = None,
    relabel: float | None = None,
    relabel_avgs: float | None = None,
    reset_avgs: float | None = None,
    vf_file: str | None = None,
    diag_file: str | None = None,
    tr: float | None = None,
    te: float | None = None,
    example: str | None = None,
    bigventricles: bool = False,
    uncompress: bool = False,
    second_pass_renorm: bool = False,
    threads: float | None = None,
    runner: Runner | None = None,
) -> MriCaRegisterOutputs:
    """
    mri_ca_register

    Generates a multi-dimensional talairach transform from a gca file and talairach.lta file

    Author: FreeSurfer Developers

    URL: https://github.com/freesurfer/freesurfer

    Args:
        input_volume: Input volume
        template: Template in GCA format
        output_volume: Output volume in M3D format
        tolerance: Defines convergence of registration
        mask: Specifies volume to use as a mask
        transform_lta: Transform in LTA format
        level: Defines how many surrounding voxels will be used in interpolations,\
            default is 6
        read_intensity: Allows reading of multiple intensity normalization
        align: Enable alignment
        invert_save_file: Invert and save as GCAM file
        distance: Distance for registration
        regularize: Regularization parameter
        regularize_mean: Mean regularization
        scale_smoothness: Smoothness scaling factor
        nobright: Disable brightness adjustment
        renormalize_map: Renormalize using map
        renormalize: Renormalize with intensity file
        read_lta: Use LTA file for registration
        smoothness: Smoothness parameter
        samples: Sample points for registration
        nsmall: Number of small features
        fixed: Fixed mode for registration
        optimal: Optimal registration settings
        noneg: Disallow negative values
        wm: White matter flag
        min_avgs: Minimum number of averages
        transform_limit: Transform limit
        relabel: Relabel options
        relabel_avgs: Relabel averages
        reset_avgs: Reset averages
        vf_file: VF file name
        diag_file: Diagnostic file name
        tr: TR parameter
        te: TE parameter
        example: Example file
        bigventricles: Handle big ventricles
        uncompress: Uncompress files
        second_pass_renorm: Second pass renormalization
        threads: Number of threads
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    params = mri_ca_register_params(
        input_volume=input_volume,
        template=template,
        output_volume=output_volume,
        tolerance=tolerance,
        mask=mask,
        transform_lta=transform_lta,
        level=level,
        read_intensity=read_intensity,
        align=align,
        invert_save_file=invert_save_file,
        distance=distance,
        regularize=regularize,
        regularize_mean=regularize_mean,
        scale_smoothness=scale_smoothness,
        nobright=nobright,
        renormalize_map=renormalize_map,
        renormalize=renormalize,
        read_lta=read_lta,
        smoothness=smoothness,
        samples=samples,
        nsmall=nsmall,
        fixed=fixed,
        optimal=optimal,
        noneg=noneg,
        wm=wm,
        min_avgs=min_avgs,
        transform_limit=transform_limit,
        relabel=relabel,
        relabel_avgs=relabel_avgs,
        reset_avgs=reset_avgs,
        vf_file=vf_file,
        diag_file=diag_file,
        tr=tr,
        te=te,
        example=example,
        bigventricles=bigventricles,
        uncompress=uncompress,
        second_pass_renorm=second_pass_renorm,
        threads=threads,
    )
    return mri_ca_register_execute(params, runner)

__all__ = [
    "MriCaRegister",
    "MriCaRegisterOutputs",
    "MRI_CA_REGISTER_METADATA",
    "mri_ca_register_cargs",
    "mri_ca_register_outputs",
    "mri_ca_register_params",
    "mri_ca_register_execute",
    "mri_ca_register_validate",
    "mri_ca_register",
]