# This file was auto generated by Styx.
# Do not edit this file directly.

import dataclasses
import pathlib
import typing

from styxdefs import Execution, InputPathType, Metadata, Runner, StyxValidationError, OutputPathType, get_global_runner

MRIS_REMOVE_NEGATIVE_VERTICES_METADATA = Metadata(
    id="mris_remove_negative_vertices",
    name="mris_remove_negative_vertices",
    package="freesurfer",
)

MrisRemoveNegativeVertices = typing.TypedDict(
    "MrisRemoveNegativeVertices",
    {
        "@type": typing.NotRequired[typing.Literal["freesurfer/mris_remove_negative_vertices"]],
        "surface_file": InputPathType,
        "patch_file": InputPathType,
        "output_patch": str,
    },
)

@dataclasses.dataclass
class MrisRemoveNegativeVerticesOutputs:
    """Output paths produced by the tool."""
    root: OutputPathType
    output_patch_file: OutputPathType
    """The resulting output patch file"""

def mris_remove_negative_vertices_params(
    surface_file: InputPathType,
    patch_file: InputPathType,
    output_patch: str,
) -> MrisRemoveNegativeVertices:
    """
    Build parameters.

    Args:
        surface_file: Input surface file
        patch_file: Patch file name
        output_patch: Output patch file

    Returns:
        Parameter dictionary.
    """
    params: MrisRemoveNegativeVertices = {
        "@type": "freesurfer/mris_remove_negative_vertices",
        "surface_file": surface_file,
        "patch_file": patch_file,
        "output_patch": output_patch,
    }
    return params

def mris_remove_negative_vertices_validate(params: typing.Any) -> None:
    """Validate untrusted parameters. Raises StyxValidationError if `params` is not a valid MrisRemoveNegativeVertices."""
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("surface_file", None) is None:
        raise StyxValidationError("`surface_file` must not be None")
    if not isinstance(params["surface_file"], (pathlib.Path, str)):
        raise StyxValidationError(f'`surface_file` has the wrong type: Received `{type(params["surface_file"])}` expected `InputPathType`')
    if params.get("patch_file", None) is None:
        raise StyxValidationError("`patch_file` must not be None")
    if not isinstance(params["patch_file"], (pathlib.Path, str)):
        raise StyxValidationError(f'`patch_file` has the wrong type: Received `{type(params["patch_file"])}` expected `InputPathType`')
    if params.get("output_patch", None) is None:
        raise StyxValidationError("`output_patch` must not be None")
    if not isinstance(params["output_patch"], str):
        raise StyxValidationError(f'`output_patch` has the wrong type: Received `{type(params["output_patch"])}` expected `str`')

def mris_remove_negative_vertices_cargs(params: MrisRemoveNegativeVertices, execution: Execution) -> list[str]:
    """Build command-line arguments from parameters."""
    cargs: list[str] = []
    cargs.append("mris_remove_negative_vertices")
    cargs.append(execution.input_file(params["surface_file"]))
    cargs.append(execution.input_file(params["patch_file"]))
    cargs.append(params["output_patch"])
    return cargs

def mris_remove_negative_vertices_outputs(params: MrisRemoveNegativeVertices, execution: Execution) -> MrisRemoveNegativeVerticesOutputs:
    """Build the MrisRemoveNegativeVerticesOutputs object for this tool."""
    root_v: OutputPathType = execution.output_file(".")
    output_patch_file_v: OutputPathType = execution.output_file(params["output_patch"])
    return MrisRemoveNegativeVerticesOutputs(
        root=root_v,
        output_patch_file=output_patch_file_v,
    )

def mris_remove_negative_vertices_execute(params: MrisRemoveNegativeVertices, runner: Runner | None = None) -> MrisRemoveNegativeVerticesOutputs:
    """
    mris_remove_negative_vertices

    This program adds a template into an average surface.

    Author: FreeSurfer Developers

    URL: https://github.com/freesurfer/freesurfer

    Args:
        params: The parameters.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    mris_remove_negative_vertices_validate(params)
    runner = runner if runner is not None else get_global_runner()
    execution = runner.start_execution(MRIS_REMOVE_NEGATIVE_VERTICES_METADATA)
    execution.params(params)
    args = mris_remove_negative_vertices_cargs(params, execution)
    out = mris_remove_negative_vertices_outputs(params, execution)
    execution.run(args)
    return out

def mris_remove_negative_vertices(
    surface_file: InputPathType,
    patch_file: InputPathType,
    output_patch: str,
    runner: Runner | None = None,
) -> MrisRemoveNegativeVerticesOutputs:
    """
    mris_remove_negative_vertices

    This program adds a template into an average surface.

    Author: FreeSurfer Developers

    URL: https://github.com/freesurfer/freesurfer

    Args:
        surface_file: Input surface file
        patch_file: Patch file name
        output_patch: Output patch file
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    params = mris_remove_negative_vertices_params(
        surface_file=surface_file,
        patch_file=patch_file,
        output_patch=output_patch,
    )
    return mris_remove_negative_vertices_execute(params, runner)

__all__ = [
    "MrisRemoveNegativeVertices",
    "MrisRemoveNegativeVerticesOutputs",
    "MRIS_REMOVE_NEGATIVE_VERTICES_METADATA",
    "mris_remove_negative_vertices_cargs",
    "mris_remove_negative_vertices_outputs",
    "mris_remove_negative_vertices_params",
    "mris_remove_negative_vertices_execute",
    "mris_remove_negative_vertices_validate",
    "mris_remove_negative_vertices",
]