[project]
name = "niwrap_freesurfer"
version = "1.0.0"
description = "FreeSurfer is a software package for the analysis and visualization of neuroimaging data from cross-sectional and longitudinal studies, developed by the Laboratory for Computational Neuroimaging at the Martinos Center for Biomedical Imaging."
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "Bruce Fischl" }, { name = "Anders M. Dale" }, { name = "Martin I. Sereno" }]
requires-python = ">=3.10"
dependencies = [
  "styxdefs>=0.7.0,<0.8.0",
]

[tool.setuptools]
packages = ["freesurfer"]
package-dir = { "freesurfer" = "." }

[tool.setuptools.package-data]
"freesurfer" = ["py.typed"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
