# This file was auto generated by Styx.
# Do not edit this file directly.

import dataclasses
import pathlib
import typing

from styxdefs import Execution, InputPathType, Metadata, Runner, StyxValidationError, OutputPathType, get_global_runner

TKSURFER_METADATA = Metadata(
    id="tksurfer",
    name="tksurfer",
    package="freesurfer",
)

Tksurfer = typing.TypedDict(
    "Tksurfer",
    {
        "@type": typing.NotRequired[typing.Literal["freesurfer/tksurfer"]],
        "subject_id": str,
        "hemisphere": str,
        "surface_name": str,
        "options": typing.NotRequired[str],
    },
)

@dataclasses.dataclass
class TksurferOutputs:
    """Output paths produced by the tool."""
    root: OutputPathType

def tksurfer_params(
    subject_id: str,
    hemisphere: str,
    surface_name: str,
    options: str | None = None,
) -> Tksurfer:
    """
    Build parameters.

    Args:
        subject_id: Subject identifier
        hemisphere: Cortical hemisphere (e.g., lh or rh)
        surface_name: Surface name (e.g., inflated, sphere, white)
        options: Optional flags and parameters

    Returns:
        Parameter dictionary.
    """
    params: Tksurfer = {
        "@type": "freesurfer/tksurfer",
        "subject_id": subject_id,
        "hemisphere": hemisphere,
        "surface_name": surface_name,
    }
    if options is not None:
        params["options"] = options
    return params

def tksurfer_validate(params: typing.Any) -> None:
    """Validate untrusted parameters. Raises StyxValidationError if `params` is not a valid Tksurfer."""
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("subject_id", None) is None:
        raise StyxValidationError("`subject_id` must not be None")
    if not isinstance(params["subject_id"], str):
        raise StyxValidationError(f'`subject_id` has the wrong type: Received `{type(params["subject_id"])}` expected `str`')
    if params.get("hemisphere", None) is None:
        raise StyxValidationError("`hemisphere` must not be None")
    if not isinstance(params["hemisphere"], str):
        raise StyxValidationError(f'`hemisphere` has the wrong type: Received `{type(params["hemisphere"])}` expected `str`')
    if params.get("surface_name", None) is None:
        raise StyxValidationError("`surface_name` must not be None")
    if not isinstance(params["surface_name"], str):
        raise StyxValidationError(f'`surface_name` has the wrong type: Received `{type(params["surface_name"])}` expected `str`')
    if params.get("options", None) is not None:
        if not isinstance(params["options"], str):
            raise StyxValidationError(f'`options` has the wrong type: Received `{type(params["options"])}` expected `str`')

def tksurfer_cargs(params: Tksurfer, execution: Execution) -> list[str]:
    """Build command-line arguments from parameters."""
    cargs: list[str] = []
    cargs.append("tksurfer")
    cargs.append(params["subject_id"])
    cargs.append(params["hemisphere"])
    cargs.append(params["surface_name"])
    v_0 = params.get("options")
    if v_0 is not None:
        cargs.append(v_0)
    return cargs

def tksurfer_outputs(params: Tksurfer, execution: Execution) -> TksurferOutputs:
    """Build the TksurferOutputs object for this tool."""
    root_v: OutputPathType = execution.output_file(".")
    return TksurferOutputs(
        root=root_v,
    )

def tksurfer_execute(params: Tksurfer, runner: Runner | None = None) -> TksurferOutputs:
    """
    tksurfer

    3D visualization tool for cortical surface models (part of FreeSurfer)

    Author: FreeSurfer Developers

    URL: https://github.com/freesurfer/freesurfer

    Args:
        params: The parameters.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    tksurfer_validate(params)
    runner = runner if runner is not None else get_global_runner()
    execution = runner.start_execution(TKSURFER_METADATA)
    execution.params(params)
    args = tksurfer_cargs(params, execution)
    out = tksurfer_outputs(params, execution)
    execution.run(args)
    return out

def tksurfer(
    subject_id: str,
    hemisphere: str,
    surface_name: str,
    options: str | None = None,
    runner: Runner | None = None,
) -> TksurferOutputs:
    """
    tksurfer

    3D visualization tool for cortical surface models (part of FreeSurfer)

    Author: FreeSurfer Developers

    URL: https://github.com/freesurfer/freesurfer

    Args:
        subject_id: Subject identifier
        hemisphere: Cortical hemisphere (e.g., lh or rh)
        surface_name: Surface name (e.g., inflated, sphere, white)
        options: Optional flags and parameters
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    params = tksurfer_params(
        subject_id=subject_id,
        hemisphere=hemisphere,
        surface_name=surface_name,
        options=options,
    )
    return tksurfer_execute(params, runner)

__all__ = [
    "Tksurfer",
    "TksurferOutputs",
    "TKSURFER_METADATA",
    "tksurfer_cargs",
    "tksurfer_outputs",
    "tksurfer_params",
    "tksurfer_execute",
    "tksurfer_validate",
    "tksurfer",
]