# This file was auto generated by Styx.
# Do not edit this file directly.

import dataclasses
import pathlib
import typing

from styxdefs import Execution, InputPathType, Metadata, Runner, StyxValidationError, OutputPathType, get_global_runner

ANATOMICAL_AVERAGE_METADATA = Metadata(
    id="AnatomicalAverage",
    name="AnatomicalAverage",
    package="fsl",
)

AnatomicalAverage = typing.TypedDict(
    "AnatomicalAverage",
    {
        "@type": typing.NotRequired[typing.Literal["fsl/AnatomicalAverage"]],
        "output_basename": str,
        "input_images": list[InputPathType],
        "standard_image": typing.NotRequired[InputPathType],
        "standard_brain_mask": typing.NotRequired[InputPathType],
        "no_crop_flag": typing.NotRequired[bool],
        "work_dir": typing.NotRequired[str],
        "brainsize": typing.NotRequired[float],
        "noclean_flag": typing.NotRequired[bool],
        "verbose_flag": typing.NotRequired[bool],
    },
)

@dataclasses.dataclass
class AnatomicalAverageOutputs:
    """Output paths produced by the tool."""
    root: OutputPathType
    avg_output: OutputPathType
    """Averaged anatomical image"""

def anatomical_average_params(
    output_basename: str,
    input_images: list[InputPathType],
    standard_image: InputPathType | None = None,
    standard_brain_mask: InputPathType | None = None,
    no_crop_flag: bool = False,
    work_dir: str | None = None,
    brainsize: float | None = None,
    noclean_flag: bool = False,
    verbose_flag: bool = False,
) -> AnatomicalAverage:
    """
    Build parameters.

    Args:
        output_basename: Output basename
        input_images: List of input images
        standard_image: Standard image (default is MNI152_T1_2mm)
        standard_brain_mask: Standard brain mask (default is\
            MNI152_T1_2mm_brain_mask_dil)
        no_crop_flag: Do not crop images
        work_dir: Local, temporary working directory (to be cleaned up - i.e.\
            deleted)
        brainsize: Specify brainsize in mm for internal ROI (via robustfov)
        noclean_flag: Do not run the cleanup
        verbose_flag: Verbose output

    Returns:
        Parameter dictionary.
    """
    params: AnatomicalAverage = {
        "@type": "fsl/AnatomicalAverage",
        "output_basename": output_basename,
        "input_images": input_images,
        "no_crop_flag": no_crop_flag,
        "noclean_flag": noclean_flag,
        "verbose_flag": verbose_flag,
    }
    if standard_image is not None:
        params["standard_image"] = standard_image
    if standard_brain_mask is not None:
        params["standard_brain_mask"] = standard_brain_mask
    if work_dir is not None:
        params["work_dir"] = work_dir
    if brainsize is not None:
        params["brainsize"] = brainsize
    return params

def anatomical_average_validate(params: typing.Any) -> None:
    """Validate untrusted parameters. Raises StyxValidationError if `params` is not a valid AnatomicalAverage."""
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("output_basename", None) is None:
        raise StyxValidationError("`output_basename` must not be None")
    if not isinstance(params["output_basename"], str):
        raise StyxValidationError(f'`output_basename` has the wrong type: Received `{type(params["output_basename"])}` expected `str`')
    if params.get("input_images", None) is None:
        raise StyxValidationError("`input_images` must not be None")
    if not isinstance(params["input_images"], list):
        raise StyxValidationError(f'`input_images` has the wrong type: Received `{type(params["input_images"])}` expected `list[InputPathType]`')
    for e in params["input_images"]:
        if not isinstance(e, (pathlib.Path, str)):
            raise StyxValidationError(f'`input_images` has the wrong type: Received `{type(e)}` expected `list[InputPathType]`')
    if params.get("standard_image", None) is not None:
        if not isinstance(params["standard_image"], (pathlib.Path, str)):
            raise StyxValidationError(f'`standard_image` has the wrong type: Received `{type(params["standard_image"])}` expected `InputPathType`')
    if params.get("standard_brain_mask", None) is not None:
        if not isinstance(params["standard_brain_mask"], (pathlib.Path, str)):
            raise StyxValidationError(f'`standard_brain_mask` has the wrong type: Received `{type(params["standard_brain_mask"])}` expected `InputPathType`')
    if params.get("no_crop_flag", None) is not None:
        if not isinstance(params["no_crop_flag"], bool):
            raise StyxValidationError(f'`no_crop_flag` has the wrong type: Received `{type(params["no_crop_flag"])}` expected `bool`')
    if params.get("work_dir", None) is not None:
        if not isinstance(params["work_dir"], str):
            raise StyxValidationError(f'`work_dir` has the wrong type: Received `{type(params["work_dir"])}` expected `str`')
    if params.get("brainsize", None) is not None:
        if not isinstance(params["brainsize"], (float, int)):
            raise StyxValidationError(f'`brainsize` has the wrong type: Received `{type(params["brainsize"])}` expected `float`')
    if params.get("noclean_flag", None) is not None:
        if not isinstance(params["noclean_flag"], bool):
            raise StyxValidationError(f'`noclean_flag` has the wrong type: Received `{type(params["noclean_flag"])}` expected `bool`')
    if params.get("verbose_flag", None) is not None:
        if not isinstance(params["verbose_flag"], bool):
            raise StyxValidationError(f'`verbose_flag` has the wrong type: Received `{type(params["verbose_flag"])}` expected `bool`')

def anatomical_average_cargs(params: AnatomicalAverage, execution: Execution) -> list[str]:
    """Build command-line arguments from parameters."""
    cargs: list[str] = []
    cargs.append("AnatomicalAverage")
    cargs.append("-o")
    cargs.append(params["output_basename"])
    for item0 in params["input_images"]:
        cargs.append(execution.input_file(item0))
    v_0 = params.get("standard_image")
    if v_0 is not None:
        cargs.append("-s")
        cargs.append(execution.input_file(v_0))
    v_1 = params.get("standard_brain_mask")
    if v_1 is not None:
        cargs.append("-m")
        cargs.append(execution.input_file(v_1))
    if params.get("no_crop_flag"):
        cargs.append("-n")
    v_2 = params.get("work_dir")
    if v_2 is not None:
        cargs.append("-w")
        cargs.append(v_2)
    v_3 = params.get("brainsize")
    if v_3 is not None:
        cargs.append("-b")
        cargs.append(str(v_3))
    if params.get("noclean_flag"):
        cargs.append("--noclean")
    if params.get("verbose_flag"):
        cargs.append("-v")
    return cargs

def anatomical_average_outputs(params: AnatomicalAverage, execution: Execution) -> AnatomicalAverageOutputs:
    """Build the AnatomicalAverageOutputs object for this tool."""
    root_v: OutputPathType = execution.output_file(".")
    avg_output_v: OutputPathType = execution.output_file(f'{params["output_basename"]}_avg.nii.gz')
    return AnatomicalAverageOutputs(
        root=root_v,
        avg_output=avg_output_v,
    )

def anatomical_average_execute(params: AnatomicalAverage, runner: Runner | None = None) -> AnatomicalAverageOutputs:
    """
    AnatomicalAverage

    Tool to create an anatomical average of input brain images

    Author: FMRIB Analysis Group, University of Oxford

    URL: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki

    Args:
        params: The parameters.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    anatomical_average_validate(params)
    runner = runner if runner is not None else get_global_runner()
    execution = runner.start_execution(ANATOMICAL_AVERAGE_METADATA)
    execution.params(params)
    args = anatomical_average_cargs(params, execution)
    out = anatomical_average_outputs(params, execution)
    execution.run(args)
    return out

def anatomical_average(
    output_basename: str,
    input_images: list[InputPathType],
    standard_image: InputPathType | None = None,
    standard_brain_mask: InputPathType | None = None,
    no_crop_flag: bool = False,
    work_dir: str | None = None,
    brainsize: float | None = None,
    noclean_flag: bool = False,
    verbose_flag: bool = False,
    runner: Runner | None = None,
) -> AnatomicalAverageOutputs:
    """
    AnatomicalAverage

    Tool to create an anatomical average of input brain images

    Author: FMRIB Analysis Group, University of Oxford

    URL: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki

    Args:
        output_basename: Output basename
        input_images: List of input images
        standard_image: Standard image (default is MNI152_T1_2mm)
        standard_brain_mask: Standard brain mask (default is\
            MNI152_T1_2mm_brain_mask_dil)
        no_crop_flag: Do not crop images
        work_dir: Local, temporary working directory (to be cleaned up - i.e.\
            deleted)
        brainsize: Specify brainsize in mm for internal ROI (via robustfov)
        noclean_flag: Do not run the cleanup
        verbose_flag: Verbose output
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    params = anatomical_average_params(
        output_basename=output_basename,
        input_images=input_images,
        standard_image=standard_image,
        standard_brain_mask=standard_brain_mask,
        no_crop_flag=no_crop_flag,
        work_dir=work_dir,
        brainsize=brainsize,
        noclean_flag=noclean_flag,
        verbose_flag=verbose_flag,
    )
    return anatomical_average_execute(params, runner)

__all__ = [
    "AnatomicalAverage",
    "AnatomicalAverageOutputs",
    "ANATOMICAL_AVERAGE_METADATA",
    "anatomical_average_cargs",
    "anatomical_average_outputs",
    "anatomical_average_params",
    "anatomical_average_execute",
    "anatomical_average_validate",
    "anatomical_average",
]