# This file was auto generated by Styx.
# Do not edit this file directly.

import dataclasses
import pathlib
import typing

from styxdefs import Execution, InputPathType, Metadata, Runner, StyxValidationError, OutputPathType, get_global_runner

FSLSWAPDIM_EXE_METADATA = Metadata(
    id="fslswapdim_exe",
    name="fslswapdim_exe",
    package="fsl",
)

FslswapdimExe = typing.TypedDict(
    "FslswapdimExe",
    {
        "@type": typing.NotRequired[typing.Literal["fsl/fslswapdim_exe"]],
        "input_file": InputPathType,
        "axis_a": str,
        "axis_b": str,
        "axis_c": str,
        "output_file": typing.NotRequired[str],
        "checkLR_flag": typing.NotRequired[bool],
    },
)

@dataclasses.dataclass
class FslswapdimExeOutputs:
    """Output paths produced by the tool."""
    root: OutputPathType
    outfile: OutputPathType | None
    """Output image file with swapped dimensions"""

def fslswapdim_exe_params(
    input_file: InputPathType,
    axis_a: str,
    axis_b: str,
    axis_c: str,
    output_file: str | None = None,
    checkLR_flag: bool = False,
) -> FslswapdimExe:
    """
    Build parameters.

    Args:
        input_file: Input image file (e.g., input.nii.gz)
        axis_a: New x-axis in terms of old axes (-x, x, y, -y, z, -z)
        axis_b: New y-axis in terms of old axes (-x, x, y, -y, z, -z)
        axis_c: New z-axis in terms of old axes (-x, x, y, -y, z, -z)
        output_file: Output image file (optional, cannot be used with --checkLR\
            flag)
        checkLR_flag: Option to check if the specified arguments lead to a\
            Left-Right swap or not, cannot be used with an output name

    Returns:
        Parameter dictionary.
    """
    params: FslswapdimExe = {
        "@type": "fsl/fslswapdim_exe",
        "input_file": input_file,
        "axis_a": axis_a,
        "axis_b": axis_b,
        "axis_c": axis_c,
        "checkLR_flag": checkLR_flag,
    }
    if output_file is not None:
        params["output_file"] = output_file
    return params

def fslswapdim_exe_validate(params: typing.Any) -> None:
    """Validate untrusted parameters. Raises StyxValidationError if `params` is not a valid FslswapdimExe."""
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("input_file", None) is None:
        raise StyxValidationError("`input_file` must not be None")
    if not isinstance(params["input_file"], (pathlib.Path, str)):
        raise StyxValidationError(f'`input_file` has the wrong type: Received `{type(params["input_file"])}` expected `InputPathType`')
    if params.get("axis_a", None) is None:
        raise StyxValidationError("`axis_a` must not be None")
    if not isinstance(params["axis_a"], str):
        raise StyxValidationError(f'`axis_a` has the wrong type: Received `{type(params["axis_a"])}` expected `str`')
    if params.get("axis_b", None) is None:
        raise StyxValidationError("`axis_b` must not be None")
    if not isinstance(params["axis_b"], str):
        raise StyxValidationError(f'`axis_b` has the wrong type: Received `{type(params["axis_b"])}` expected `str`')
    if params.get("axis_c", None) is None:
        raise StyxValidationError("`axis_c` must not be None")
    if not isinstance(params["axis_c"], str):
        raise StyxValidationError(f'`axis_c` has the wrong type: Received `{type(params["axis_c"])}` expected `str`')
    if params.get("output_file", None) is not None:
        if not isinstance(params["output_file"], str):
            raise StyxValidationError(f'`output_file` has the wrong type: Received `{type(params["output_file"])}` expected `str`')
    if params.get("checkLR_flag", None) is not None:
        if not isinstance(params["checkLR_flag"], bool):
            raise StyxValidationError(f'`checkLR_flag` has the wrong type: Received `{type(params["checkLR_flag"])}` expected `bool`')

def fslswapdim_exe_cargs(params: FslswapdimExe, execution: Execution) -> list[str]:
    """Build command-line arguments from parameters."""
    cargs: list[str] = []
    cargs.append("fslswapdim_exe")
    cargs.append(execution.input_file(params["input_file"]))
    cargs.append(params["axis_a"])
    cargs.append(params["axis_b"])
    cargs.append(params["axis_c"])
    v_0 = params.get("output_file")
    if v_0 is not None:
        cargs.append(v_0)
    if params.get("checkLR_flag"):
        cargs.append("--checkLR")
    return cargs

def fslswapdim_exe_outputs(params: FslswapdimExe, execution: Execution) -> FslswapdimExeOutputs:
    """Build the FslswapdimExeOutputs object for this tool."""
    outfile_v: OutputPathType | None = None
    root_v: OutputPathType = execution.output_file(".")
    __v0 = params.get("output_file")
    if __v0 is not None:
        outfile_v = execution.output_file((__v0 if __v0 is not None else ""))
    return FslswapdimExeOutputs(
        root=root_v,
        outfile=outfile_v,
    )

def fslswapdim_exe_execute(params: FslswapdimExe, runner: Runner | None = None) -> FslswapdimExeOutputs:
    """
    fslswapdim_exe

    Tool to swap the x, y, z axes dimensions of an image

    Author: FMRIB Analysis Group, University of Oxford

    URL: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki

    Args:
        params: The parameters.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    fslswapdim_exe_validate(params)
    runner = runner if runner is not None else get_global_runner()
    execution = runner.start_execution(FSLSWAPDIM_EXE_METADATA)
    execution.params(params)
    args = fslswapdim_exe_cargs(params, execution)
    out = fslswapdim_exe_outputs(params, execution)
    execution.run(args)
    return out

def fslswapdim_exe(
    input_file: InputPathType,
    axis_a: str,
    axis_b: str,
    axis_c: str,
    output_file: str | None = None,
    checkLR_flag: bool = False,
    runner: Runner | None = None,
) -> FslswapdimExeOutputs:
    """
    fslswapdim_exe

    Tool to swap the x, y, z axes dimensions of an image

    Author: FMRIB Analysis Group, University of Oxford

    URL: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki

    Args:
        input_file: Input image file (e.g., input.nii.gz)
        axis_a: New x-axis in terms of old axes (-x, x, y, -y, z, -z)
        axis_b: New y-axis in terms of old axes (-x, x, y, -y, z, -z)
        axis_c: New z-axis in terms of old axes (-x, x, y, -y, z, -z)
        output_file: Output image file (optional, cannot be used with --checkLR\
            flag)
        checkLR_flag: Option to check if the specified arguments lead to a\
            Left-Right swap or not, cannot be used with an output name
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    params = fslswapdim_exe_params(
        input_file=input_file,
        axis_a=axis_a,
        axis_b=axis_b,
        axis_c=axis_c,
        output_file=output_file,
        checkLR_flag=checkLR_flag,
    )
    return fslswapdim_exe_execute(params, runner)

__all__ = [
    "FslswapdimExe",
    "FslswapdimExeOutputs",
    "FSLSWAPDIM_EXE_METADATA",
    "fslswapdim_exe_cargs",
    "fslswapdim_exe_outputs",
    "fslswapdim_exe_params",
    "fslswapdim_exe_execute",
    "fslswapdim_exe_validate",
    "fslswapdim_exe",
]