# This file was auto generated by Styx.
# Do not edit this file directly.

import dataclasses
import pathlib
import typing

from styxdefs import Execution, InputPathType, Metadata, Runner, StyxValidationError, OutputPathType, get_global_runner

FSLVBM_3_PROC_METADATA = Metadata(
    id="fslvbm_3_proc",
    name="fslvbm_3_proc",
    package="fsl",
)

Fslvbm3Proc = typing.TypedDict(
    "Fslvbm3Proc",
    {
        "@type": typing.NotRequired[typing.Literal["fsl/fslvbm_3_proc"]],
        "arch": typing.NotRequired[str],
        "coprocessor": typing.NotRequired[str],
        "coprocessor_multi": typing.NotRequired[str],
        "coprocessor_class": typing.NotRequired[str],
        "coprocessor_class_strict": typing.NotRequired[bool],
        "coprocessor_toolkit": typing.NotRequired[str],
        "not_requeueable": typing.NotRequired[bool],
        "jobhold": typing.NotRequired[str],
        "array_hold": typing.NotRequired[str],
        "logdir": typing.NotRequired[str],
        "mailoptions": typing.NotRequired[str],
        "mailto": typing.NotRequired[str],
        "name": typing.NotRequired[str],
        "priority": typing.NotRequired[str],
        "queue": typing.NotRequired[str],
        "resource": typing.NotRequired[str],
        "delete_job": typing.NotRequired[str],
        "memory_gb": typing.NotRequired[float],
        "parallel_env_threads": typing.NotRequired[str],
        "array_task": typing.NotRequired[str],
        "array_native": typing.NotRequired[str],
        "number_jobscripts": typing.NotRequired[float],
        "keep_jobscript": typing.NotRequired[bool],
        "coprocessor_name": typing.NotRequired[str],
        "has_queues": typing.NotRequired[bool],
        "project": typing.NotRequired[str],
        "submit_scheduler": typing.NotRequired[bool],
        "runtime_limit": typing.NotRequired[float],
        "show_config": typing.NotRequired[bool],
        "verbose": typing.NotRequired[bool],
        "version": typing.NotRequired[bool],
        "config_file": typing.NotRequired[InputPathType],
    },
)

@dataclasses.dataclass
class Fslvbm3ProcOutputs:
    """Output paths produced by the tool."""
    root: OutputPathType
    output_directory: OutputPathType
    """Output data directory"""

def fslvbm_3_proc_params(
    arch: str | None = None,
    coprocessor: str | None = None,
    coprocessor_multi: str | None = None,
    coprocessor_class: str | None = None,
    coprocessor_class_strict: bool = False,
    coprocessor_toolkit: str | None = None,
    not_requeueable: bool = False,
    jobhold: str | None = None,
    array_hold: str | None = None,
    logdir: str | None = None,
    mailoptions: str | None = None,
    mailto: str | None = None,
    name: str | None = None,
    priority: str | None = None,
    queue: str | None = None,
    resource: str | None = None,
    delete_job: str | None = None,
    memory_gb: float | None = None,
    parallel_env_threads: str | None = None,
    array_task: str | None = None,
    array_native: str | None = None,
    number_jobscripts: float | None = None,
    keep_jobscript: bool = False,
    coprocessor_name: str | None = None,
    has_queues: bool = False,
    project: str | None = None,
    submit_scheduler: bool = False,
    runtime_limit: float | None = None,
    show_config: bool = False,
    verbose: bool = False,
    version: bool = False,
    config_file: InputPathType | None = None,
) -> Fslvbm3Proc:
    """
    Build parameters.

    Args:
        arch: Specify architecture
        coprocessor: Specify coprocessor
        coprocessor_multi: Specify multiple coprocessors
        coprocessor_class: Specify coprocessor class
        coprocessor_class_strict: Use strict class matching for coprocessor
        coprocessor_toolkit: Specify coprocessor toolkit
        not_requeueable: Do not requeue the job
        jobhold: Job to hold
        array_hold: Array hold
        logdir: Specify log directory
        mailoptions: Specify mail options
        mailto: Specify mail recipient
        name: Job name
        priority: Job priority
        queue: Queue to submit to
        resource: Resource identifier
        delete_job: Delete specified job
        memory_gb: Memory (GB)
        parallel_env_threads: Parallel environment and threads
        array_task: Array task file
        array_native: Array native specification
        number_jobscripts: Keep number of job scripts
        keep_jobscript: Keep job script
        coprocessor_name: Specify coprocessor name
        has_queues: Specify queues
        project: Specify project name
        submit_scheduler: Submit to Scheduler
        runtime_limit: Specify runtime limit in minutes
        show_config: Show configuration
        verbose: Verbose output
        version: Version information
        config_file: Specify configuration file

    Returns:
        Parameter dictionary.
    """
    params: Fslvbm3Proc = {
        "@type": "fsl/fslvbm_3_proc",
        "coprocessor_class_strict": coprocessor_class_strict,
        "not_requeueable": not_requeueable,
        "keep_jobscript": keep_jobscript,
        "has_queues": has_queues,
        "submit_scheduler": submit_scheduler,
        "show_config": show_config,
        "verbose": verbose,
        "version": version,
    }
    if arch is not None:
        params["arch"] = arch
    if coprocessor is not None:
        params["coprocessor"] = coprocessor
    if coprocessor_multi is not None:
        params["coprocessor_multi"] = coprocessor_multi
    if coprocessor_class is not None:
        params["coprocessor_class"] = coprocessor_class
    if coprocessor_toolkit is not None:
        params["coprocessor_toolkit"] = coprocessor_toolkit
    if jobhold is not None:
        params["jobhold"] = jobhold
    if array_hold is not None:
        params["array_hold"] = array_hold
    if logdir is not None:
        params["logdir"] = logdir
    if mailoptions is not None:
        params["mailoptions"] = mailoptions
    if mailto is not None:
        params["mailto"] = mailto
    if name is not None:
        params["name"] = name
    if priority is not None:
        params["priority"] = priority
    if queue is not None:
        params["queue"] = queue
    if resource is not None:
        params["resource"] = resource
    if delete_job is not None:
        params["delete_job"] = delete_job
    if memory_gb is not None:
        params["memory_gb"] = memory_gb
    if parallel_env_threads is not None:
        params["parallel_env_threads"] = parallel_env_threads
    if array_task is not None:
        params["array_task"] = array_task
    if array_native is not None:
        params["array_native"] = array_native
    if number_jobscripts is not None:
        params["number_jobscripts"] = number_jobscripts
    if coprocessor_name is not None:
        params["coprocessor_name"] = coprocessor_name
    if project is not None:
        params["project"] = project
    if runtime_limit is not None:
        params["runtime_limit"] = runtime_limit
    if config_file is not None:
        params["config_file"] = config_file
    return params

def fslvbm_3_proc_validate(params: typing.Any) -> None:
    """Validate untrusted parameters. Raises StyxValidationError if `params` is not a valid Fslvbm3Proc."""
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("arch", None) is not None:
        if not isinstance(params["arch"], str):
            raise StyxValidationError(f'`arch` has the wrong type: Received `{type(params["arch"])}` expected `str`')
    if params.get("coprocessor", None) is not None:
        if not isinstance(params["coprocessor"], str):
            raise StyxValidationError(f'`coprocessor` has the wrong type: Received `{type(params["coprocessor"])}` expected `str`')
    if params.get("coprocessor_multi", None) is not None:
        if not isinstance(params["coprocessor_multi"], str):
            raise StyxValidationError(f'`coprocessor_multi` has the wrong type: Received `{type(params["coprocessor_multi"])}` expected `str`')
    if params.get("coprocessor_class", None) is not None:
        if not isinstance(params["coprocessor_class"], str):
            raise StyxValidationError(f'`coprocessor_class` has the wrong type: Received `{type(params["coprocessor_class"])}` expected `str`')
    if params.get("coprocessor_class_strict", None) is not None:
        if not isinstance(params["coprocessor_class_strict"], bool):
            raise StyxValidationError(f'`coprocessor_class_strict` has the wrong type: Received `{type(params["coprocessor_class_strict"])}` expected `bool`')
    if params.get("coprocessor_toolkit", None) is not None:
        if not isinstance(params["coprocessor_toolkit"], str):
            raise StyxValidationError(f'`coprocessor_toolkit` has the wrong type: Received `{type(params["coprocessor_toolkit"])}` expected `str`')
    if params.get("not_requeueable", None) is not None:
        if not isinstance(params["not_requeueable"], bool):
            raise StyxValidationError(f'`not_requeueable` has the wrong type: Received `{type(params["not_requeueable"])}` expected `bool`')
    if params.get("jobhold", None) is not None:
        if not isinstance(params["jobhold"], str):
            raise StyxValidationError(f'`jobhold` has the wrong type: Received `{type(params["jobhold"])}` expected `str`')
    if params.get("array_hold", None) is not None:
        if not isinstance(params["array_hold"], str):
            raise StyxValidationError(f'`array_hold` has the wrong type: Received `{type(params["array_hold"])}` expected `str`')
    if params.get("logdir", None) is not None:
        if not isinstance(params["logdir"], str):
            raise StyxValidationError(f'`logdir` has the wrong type: Received `{type(params["logdir"])}` expected `str`')
    if params.get("mailoptions", None) is not None:
        if not isinstance(params["mailoptions"], str):
            raise StyxValidationError(f'`mailoptions` has the wrong type: Received `{type(params["mailoptions"])}` expected `str`')
    if params.get("mailto", None) is not None:
        if not isinstance(params["mailto"], str):
            raise StyxValidationError(f'`mailto` has the wrong type: Received `{type(params["mailto"])}` expected `str`')
    if params.get("name", None) is not None:
        if not isinstance(params["name"], str):
            raise StyxValidationError(f'`name` has the wrong type: Received `{type(params["name"])}` expected `str`')
    if params.get("priority", None) is not None:
        if not isinstance(params["priority"], str):
            raise StyxValidationError(f'`priority` has the wrong type: Received `{type(params["priority"])}` expected `str`')
    if params.get("queue", None) is not None:
        if not isinstance(params["queue"], str):
            raise StyxValidationError(f'`queue` has the wrong type: Received `{type(params["queue"])}` expected `str`')
    if params.get("resource", None) is not None:
        if not isinstance(params["resource"], str):
            raise StyxValidationError(f'`resource` has the wrong type: Received `{type(params["resource"])}` expected `str`')
    if params.get("delete_job", None) is not None:
        if not isinstance(params["delete_job"], str):
            raise StyxValidationError(f'`delete_job` has the wrong type: Received `{type(params["delete_job"])}` expected `str`')
    if params.get("memory_gb", None) is not None:
        if not isinstance(params["memory_gb"], (float, int)):
            raise StyxValidationError(f'`memory_gb` has the wrong type: Received `{type(params["memory_gb"])}` expected `float`')
    if params.get("parallel_env_threads", None) is not None:
        if not isinstance(params["parallel_env_threads"], str):
            raise StyxValidationError(f'`parallel_env_threads` has the wrong type: Received `{type(params["parallel_env_threads"])}` expected `str`')
    if params.get("array_task", None) is not None:
        if not isinstance(params["array_task"], str):
            raise StyxValidationError(f'`array_task` has the wrong type: Received `{type(params["array_task"])}` expected `str`')
    if params.get("array_native", None) is not None:
        if not isinstance(params["array_native"], str):
            raise StyxValidationError(f'`array_native` has the wrong type: Received `{type(params["array_native"])}` expected `str`')
    if params.get("number_jobscripts", None) is not None:
        if not isinstance(params["number_jobscripts"], (float, int)):
            raise StyxValidationError(f'`number_jobscripts` has the wrong type: Received `{type(params["number_jobscripts"])}` expected `float`')
    if params.get("keep_jobscript", None) is not None:
        if not isinstance(params["keep_jobscript"], bool):
            raise StyxValidationError(f'`keep_jobscript` has the wrong type: Received `{type(params["keep_jobscript"])}` expected `bool`')
    if params.get("coprocessor_name", None) is not None:
        if not isinstance(params["coprocessor_name"], str):
            raise StyxValidationError(f'`coprocessor_name` has the wrong type: Received `{type(params["coprocessor_name"])}` expected `str`')
    if params.get("has_queues", None) is not None:
        if not isinstance(params["has_queues"], bool):
            raise StyxValidationError(f'`has_queues` has the wrong type: Received `{type(params["has_queues"])}` expected `bool`')
    if params.get("project", None) is not None:
        if not isinstance(params["project"], str):
            raise StyxValidationError(f'`project` has the wrong type: Received `{type(params["project"])}` expected `str`')
    if params.get("submit_scheduler", None) is not None:
        if not isinstance(params["submit_scheduler"], bool):
            raise StyxValidationError(f'`submit_scheduler` has the wrong type: Received `{type(params["submit_scheduler"])}` expected `bool`')
    if params.get("runtime_limit", None) is not None:
        if not isinstance(params["runtime_limit"], (float, int)):
            raise StyxValidationError(f'`runtime_limit` has the wrong type: Received `{type(params["runtime_limit"])}` expected `float`')
    if params.get("show_config", None) is not None:
        if not isinstance(params["show_config"], bool):
            raise StyxValidationError(f'`show_config` has the wrong type: Received `{type(params["show_config"])}` expected `bool`')
    if params.get("verbose", None) is not None:
        if not isinstance(params["verbose"], bool):
            raise StyxValidationError(f'`verbose` has the wrong type: Received `{type(params["verbose"])}` expected `bool`')
    if params.get("version", None) is not None:
        if not isinstance(params["version"], bool):
            raise StyxValidationError(f'`version` has the wrong type: Received `{type(params["version"])}` expected `bool`')
    if params.get("config_file", None) is not None:
        if not isinstance(params["config_file"], (pathlib.Path, str)):
            raise StyxValidationError(f'`config_file` has the wrong type: Received `{type(params["config_file"])}` expected `InputPathType`')

def fslvbm_3_proc_cargs(params: Fslvbm3Proc, execution: Execution) -> list[str]:
    """Build command-line arguments from parameters."""
    cargs: list[str] = []
    cargs.append("fslvbm_3_proc")
    v_0 = params.get("arch")
    if v_0 is not None:
        cargs.append("-a")
        cargs.append(v_0)
    v_1 = params.get("coprocessor")
    if v_1 is not None:
        cargs.append("-c")
        cargs.append(v_1)
    v_2 = params.get("coprocessor_multi")
    if v_2 is not None:
        cargs.append("--coprocessor_multi")
        cargs.append(v_2)
    v_3 = params.get("coprocessor_class")
    if v_3 is not None:
        cargs.append("--coprocessor_class")
        cargs.append(v_3)
    if params.get("coprocessor_class_strict"):
        cargs.append("--coprocessor_class_strict")
    v_4 = params.get("coprocessor_toolkit")
    if v_4 is not None:
        cargs.append("--coprocessor_toolkit")
        cargs.append(v_4)
    if params.get("not_requeueable"):
        cargs.append("-F")
    v_5 = params.get("jobhold")
    if v_5 is not None:
        cargs.append("-j")
        cargs.append(v_5)
    v_6 = params.get("array_hold")
    if v_6 is not None:
        cargs.append("--array_hold")
        cargs.append(v_6)
    v_7 = params.get("logdir")
    if v_7 is not None:
        cargs.append("-l")
        cargs.append(v_7)
    v_8 = params.get("mailoptions")
    if v_8 is not None:
        cargs.append("-m")
        cargs.append(v_8)
    v_9 = params.get("mailto")
    if v_9 is not None:
        cargs.append("-M")
        cargs.append(v_9)
    v_10 = params.get("name")
    if v_10 is not None:
        cargs.append("-N")
        cargs.append(v_10)
    v_11 = params.get("priority")
    if v_11 is not None:
        cargs.append("-p")
        cargs.append(v_11)
    v_12 = params.get("queue")
    if v_12 is not None:
        cargs.append("-q")
        cargs.append(v_12)
    v_13 = params.get("resource")
    if v_13 is not None:
        cargs.append("-r")
        cargs.append(v_13)
    v_14 = params.get("delete_job")
    if v_14 is not None:
        cargs.append("--delete_job")
        cargs.append(v_14)
    v_15 = params.get("memory_gb")
    if v_15 is not None:
        cargs.append("-R")
        cargs.append(str(v_15))
    v_16 = params.get("parallel_env_threads")
    if v_16 is not None:
        cargs.append("-s")
        cargs.append(v_16)
    v_17 = params.get("array_task")
    if v_17 is not None:
        cargs.append("-t")
        cargs.append(v_17)
    v_18 = params.get("array_native")
    if v_18 is not None:
        cargs.append("--array_native")
        cargs.append(v_18)
    v_19 = params.get("number_jobscripts")
    if v_19 is not None:
        cargs.append("-x")
        cargs.append(str(v_19))
    if params.get("keep_jobscript"):
        cargs.append("--keep_jobscript")
    v_20 = params.get("coprocessor_name")
    if v_20 is not None:
        cargs.append("--has_coprocessor")
        cargs.append(v_20)
    if params.get("has_queues"):
        cargs.append("--has_queues")
    v_21 = params.get("project")
    if v_21 is not None:
        cargs.append("--project")
        cargs.append(v_21)
    if params.get("submit_scheduler"):
        cargs.append("-S")
    v_22 = params.get("runtime_limit")
    if v_22 is not None:
        cargs.append("-T")
        cargs.append(str(v_22))
    if params.get("show_config"):
        cargs.append("--show_config")
    if params.get("verbose"):
        cargs.append("-v")
    if params.get("version"):
        cargs.append("-V")
    v_23 = params.get("config_file")
    if v_23 is not None:
        cargs.append("-z")
        cargs.append(execution.input_file(v_23))
    return cargs

def fslvbm_3_proc_outputs(params: Fslvbm3Proc, execution: Execution) -> Fslvbm3ProcOutputs:
    """Build the Fslvbm3ProcOutputs object for this tool."""
    root_v: OutputPathType = execution.output_file(".")
    output_directory_v: OutputPathType = execution.output_file("fslvbm3a")
    return Fslvbm3ProcOutputs(
        root=root_v,
        output_directory=output_directory_v,
    )

def fslvbm_3_proc_execute(params: Fslvbm3Proc, runner: Runner | None = None) -> Fslvbm3ProcOutputs:
    """
    fslvbm_3_proc

    Pipeline for voxel-based morphometry analysis using FSL tools

    Author: FMRIB Analysis Group, University of Oxford

    URL: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki

    Args:
        params: The parameters.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    fslvbm_3_proc_validate(params)
    runner = runner if runner is not None else get_global_runner()
    execution = runner.start_execution(FSLVBM_3_PROC_METADATA)
    execution.params(params)
    args = fslvbm_3_proc_cargs(params, execution)
    out = fslvbm_3_proc_outputs(params, execution)
    execution.run(args)
    return out

def fslvbm_3_proc(
    arch: str | None = None,
    coprocessor: str | None = None,
    coprocessor_multi: str | None = None,
    coprocessor_class: str | None = None,
    coprocessor_class_strict: bool = False,
    coprocessor_toolkit: str | None = None,
    not_requeueable: bool = False,
    jobhold: str | None = None,
    array_hold: str | None = None,
    logdir: str | None = None,
    mailoptions: str | None = None,
    mailto: str | None = None,
    name: str | None = None,
    priority: str | None = None,
    queue: str | None = None,
    resource: str | None = None,
    delete_job: str | None = None,
    memory_gb: float | None = None,
    parallel_env_threads: str | None = None,
    array_task: str | None = None,
    array_native: str | None = None,
    number_jobscripts: float | None = None,
    keep_jobscript: bool = False,
    coprocessor_name: str | None = None,
    has_queues: bool = False,
    project: str | None = None,
    submit_scheduler: bool = False,
    runtime_limit: float | None = None,
    show_config: bool = False,
    verbose: bool = False,
    version: bool = False,
    config_file: InputPathType | None = None,
    runner: Runner | None = None,
) -> Fslvbm3ProcOutputs:
    """
    fslvbm_3_proc

    Pipeline for voxel-based morphometry analysis using FSL tools

    Author: FMRIB Analysis Group, University of Oxford

    URL: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki

    Args:
        arch: Specify architecture
        coprocessor: Specify coprocessor
        coprocessor_multi: Specify multiple coprocessors
        coprocessor_class: Specify coprocessor class
        coprocessor_class_strict: Use strict class matching for coprocessor
        coprocessor_toolkit: Specify coprocessor toolkit
        not_requeueable: Do not requeue the job
        jobhold: Job to hold
        array_hold: Array hold
        logdir: Specify log directory
        mailoptions: Specify mail options
        mailto: Specify mail recipient
        name: Job name
        priority: Job priority
        queue: Queue to submit to
        resource: Resource identifier
        delete_job: Delete specified job
        memory_gb: Memory (GB)
        parallel_env_threads: Parallel environment and threads
        array_task: Array task file
        array_native: Array native specification
        number_jobscripts: Keep number of job scripts
        keep_jobscript: Keep job script
        coprocessor_name: Specify coprocessor name
        has_queues: Specify queues
        project: Specify project name
        submit_scheduler: Submit to Scheduler
        runtime_limit: Specify runtime limit in minutes
        show_config: Show configuration
        verbose: Verbose output
        version: Version information
        config_file: Specify configuration file
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    params = fslvbm_3_proc_params(
        arch=arch,
        coprocessor=coprocessor,
        coprocessor_multi=coprocessor_multi,
        coprocessor_class=coprocessor_class,
        coprocessor_class_strict=coprocessor_class_strict,
        coprocessor_toolkit=coprocessor_toolkit,
        not_requeueable=not_requeueable,
        jobhold=jobhold,
        array_hold=array_hold,
        logdir=logdir,
        mailoptions=mailoptions,
        mailto=mailto,
        name=name,
        priority=priority,
        queue=queue,
        resource=resource,
        delete_job=delete_job,
        memory_gb=memory_gb,
        parallel_env_threads=parallel_env_threads,
        array_task=array_task,
        array_native=array_native,
        number_jobscripts=number_jobscripts,
        keep_jobscript=keep_jobscript,
        coprocessor_name=coprocessor_name,
        has_queues=has_queues,
        project=project,
        submit_scheduler=submit_scheduler,
        runtime_limit=runtime_limit,
        show_config=show_config,
        verbose=verbose,
        version=version,
        config_file=config_file,
    )
    return fslvbm_3_proc_execute(params, runner)

__all__ = [
    "Fslvbm3Proc",
    "Fslvbm3ProcOutputs",
    "FSLVBM_3_PROC_METADATA",
    "fslvbm_3_proc_cargs",
    "fslvbm_3_proc_outputs",
    "fslvbm_3_proc_params",
    "fslvbm_3_proc_execute",
    "fslvbm_3_proc_validate",
    "fslvbm_3_proc",
]