# This file was auto generated by Styx.
# Do not edit this file directly.

import typing
import pathlib
from styxdefs import *

POSSUM_INTERPMOT_PY_METADATA = Metadata(
    id="3f3adbac7b7f47ce490bce211d17a46626672b68.boutiques",
    name="possum_interpmot.py",
    package="fsl",
    container_image_tag="brainlife/fsl:6.0.4-patched2",
)


_PossumInterpmotPyParamsDictNoTag = typing.TypedDict('_PossumInterpmotPyParamsDictNoTag', {
    "motion_type": int,
    "tr": float,
    "tr_slice": float,
    "nslices": int,
    "nvols": int,
    "custom_motion_file": InputPathType,
    "output_file": str,
})
PossumInterpmotPyParamsDictTagged = typing.TypedDict('PossumInterpmotPyParamsDictTagged', {
    "@type": typing.Literal["fsl/possum_interpmot.py"],
    "motion_type": int,
    "tr": float,
    "tr_slice": float,
    "nslices": int,
    "nvols": int,
    "custom_motion_file": InputPathType,
    "output_file": str,
})
PossumInterpmotPyParamsDict = _PossumInterpmotPyParamsDictNoTag | PossumInterpmotPyParamsDictTagged


class PossumInterpmotPyOutputs(typing.NamedTuple):
    """
    Output object returned when calling `PossumInterpmotPyParamsDict(...)`.
    """
    root: OutputPathType
    """Output root folder. This is the root folder for all outputs."""
    outfile: OutputPathType
    """Interpolated motion output file"""


def possum_interpmot_py_params(
    motion_type: int,
    tr: float,
    tr_slice: float,
    nslices: int,
    nvols: int,
    custom_motion_file: InputPathType,
    output_file: str,
) -> PossumInterpmotPyParamsDictTagged:
    """
    Build parameters.
    
    Args:
        motion_type: Type of motion: 0 for continuous, 1 for between slices, 2\
            for between volumes.
        tr: Repetition time in seconds.
        tr_slice: Slice repetition time in seconds.
        nslices: Number of slices.
        nvols: Number of volumes.
        custom_motion_file: Custom motion file.
        output_file: Output file.
    Returns:
        Parameter dictionary
    """
    params = {
        "@type": "fsl/possum_interpmot.py",
        "motion_type": motion_type,
        "tr": tr,
        "tr_slice": tr_slice,
        "nslices": nslices,
        "nvols": nvols,
        "custom_motion_file": custom_motion_file,
        "output_file": output_file,
    }
    return params


def possum_interpmot_py_validate(
    params: typing.Any,
) -> None:
    """
    Validate parameters. Throws an error if `params` is not a valid
    `PossumInterpmotPyParamsDict` object.
    
    Args:
        params: The parameters object to validate.
    """
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("motion_type", None) is None:
        raise StyxValidationError("`motion_type` must not be None")
    if not isinstance(params["motion_type"], int):
        raise StyxValidationError(f'`motion_type` has the wrong type: Received `{type(params.get("motion_type", None))}` expected `int`')
    if not (0 <= params["motion_type"] <= 2):
        raise StyxValidationError("Parameter `motion_type` must be between 0 and 2 (inclusive)")
    if params.get("tr", None) is None:
        raise StyxValidationError("`tr` must not be None")
    if not isinstance(params["tr"], (float, int)):
        raise StyxValidationError(f'`tr` has the wrong type: Received `{type(params.get("tr", None))}` expected `float`')
    if params.get("tr_slice", None) is None:
        raise StyxValidationError("`tr_slice` must not be None")
    if not isinstance(params["tr_slice"], (float, int)):
        raise StyxValidationError(f'`tr_slice` has the wrong type: Received `{type(params.get("tr_slice", None))}` expected `float`')
    if params.get("nslices", None) is None:
        raise StyxValidationError("`nslices` must not be None")
    if not isinstance(params["nslices"], int):
        raise StyxValidationError(f'`nslices` has the wrong type: Received `{type(params.get("nslices", None))}` expected `int`')
    if params.get("nvols", None) is None:
        raise StyxValidationError("`nvols` must not be None")
    if not isinstance(params["nvols"], int):
        raise StyxValidationError(f'`nvols` has the wrong type: Received `{type(params.get("nvols", None))}` expected `int`')
    if params.get("custom_motion_file", None) is None:
        raise StyxValidationError("`custom_motion_file` must not be None")
    if not isinstance(params["custom_motion_file"], (pathlib.Path, str)):
        raise StyxValidationError(f'`custom_motion_file` has the wrong type: Received `{type(params.get("custom_motion_file", None))}` expected `InputPathType`')
    if params.get("output_file", None) is None:
        raise StyxValidationError("`output_file` must not be None")
    if not isinstance(params["output_file"], str):
        raise StyxValidationError(f'`output_file` has the wrong type: Received `{type(params.get("output_file", None))}` expected `str`')


def possum_interpmot_py_cargs(
    params: PossumInterpmotPyParamsDict,
    execution: Execution,
) -> list[str]:
    """
    Build command-line arguments from parameters.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Command-line arguments.
    """
    cargs = []
    cargs.append("possum_interpmot.py")
    cargs.append(str(params.get("motion_type", None)))
    cargs.append(str(params.get("tr", None)))
    cargs.append(str(params.get("tr_slice", None)))
    cargs.append(str(params.get("nslices", None)))
    cargs.append(str(params.get("nvols", None)))
    cargs.append(execution.input_file(params.get("custom_motion_file", None)))
    cargs.append(params.get("output_file", None))
    return cargs


def possum_interpmot_py_outputs(
    params: PossumInterpmotPyParamsDict,
    execution: Execution,
) -> PossumInterpmotPyOutputs:
    """
    Build outputs object containing output file paths and possibly stdout/stderr.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Outputs object.
    """
    ret = PossumInterpmotPyOutputs(
        root=execution.output_file("."),
        outfile=execution.output_file(params.get("output_file", None)),
    )
    return ret


def possum_interpmot_py_execute(
    params: PossumInterpmotPyParamsDict,
    runner: Runner | None = None,
) -> PossumInterpmotPyOutputs:
    """
    possum_interpmot.py
    
    Position Interpolation for Movers and Shakers.
    
    Author: FMRIB Analysis Group, University of Oxford
    
    URL: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki
    
    Args:
        params: The parameters.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `PossumInterpmotPyOutputs`).
    """
    possum_interpmot_py_validate(params)
    runner = runner or get_global_runner()
    execution = runner.start_execution(POSSUM_INTERPMOT_PY_METADATA)
    params = execution.params(params)
    cargs = possum_interpmot_py_cargs(params, execution)
    ret = possum_interpmot_py_outputs(params, execution)
    execution.run(cargs)
    return ret


def possum_interpmot_py(
    motion_type: int,
    tr: float,
    tr_slice: float,
    nslices: int,
    nvols: int,
    custom_motion_file: InputPathType,
    output_file: str,
    runner: Runner | None = None,
) -> PossumInterpmotPyOutputs:
    """
    possum_interpmot.py
    
    Position Interpolation for Movers and Shakers.
    
    Author: FMRIB Analysis Group, University of Oxford
    
    URL: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki
    
    Args:
        motion_type: Type of motion: 0 for continuous, 1 for between slices, 2\
            for between volumes.
        tr: Repetition time in seconds.
        tr_slice: Slice repetition time in seconds.
        nslices: Number of slices.
        nvols: Number of volumes.
        custom_motion_file: Custom motion file.
        output_file: Output file.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `PossumInterpmotPyOutputs`).
    """
    params = possum_interpmot_py_params(
        motion_type=motion_type,
        tr=tr,
        tr_slice=tr_slice,
        nslices=nslices,
        nvols=nvols,
        custom_motion_file=custom_motion_file,
        output_file=output_file,
    )
    return possum_interpmot_py_execute(params, runner)


__all__ = [
    "POSSUM_INTERPMOT_PY_METADATA",
    "PossumInterpmotPyOutputs",
    "PossumInterpmotPyParamsDict",
    "PossumInterpmotPyParamsDictTagged",
    "possum_interpmot_py",
    "possum_interpmot_py_execute",
    "possum_interpmot_py_params",
]
