# This file was auto generated by Styx.
# Do not edit this file directly.

import typing
import pathlib
from styxdefs import *

SLICESMASK_METADATA = Metadata(
    id="a68d0c940cf7925c94a73dce46a552c162fb9ed1.boutiques",
    name="slicesmask",
    package="fsl",
    container_image_tag="brainlife/fsl:6.0.4-patched2",
)


_SlicesmaskParamsDictNoTag = typing.TypedDict('_SlicesmaskParamsDictNoTag', {
    "image": InputPathType,
    "mask": InputPathType,
    "output": str,
})
SlicesmaskParamsDictTagged = typing.TypedDict('SlicesmaskParamsDictTagged', {
    "@type": typing.Literal["fsl/slicesmask"],
    "image": InputPathType,
    "mask": InputPathType,
    "output": str,
})
SlicesmaskParamsDict = _SlicesmaskParamsDictNoTag | SlicesmaskParamsDictTagged


class SlicesmaskOutputs(typing.NamedTuple):
    """
    Output object returned when calling `SlicesmaskParamsDict(...)`.
    """
    root: OutputPathType
    """Output root folder. This is the root folder for all outputs."""
    masked_output: OutputPathType
    """The output file resulting from applying the mask"""


def slicesmask_params(
    image: InputPathType,
    mask: InputPathType,
    output: str,
) -> SlicesmaskParamsDictTagged:
    """
    Build parameters.
    
    Args:
        image: Input image file.
        mask: Mask file.
        output: Output file.
    Returns:
        Parameter dictionary
    """
    params = {
        "@type": "fsl/slicesmask",
        "image": image,
        "mask": mask,
        "output": output,
    }
    return params


def slicesmask_validate(
    params: typing.Any,
) -> None:
    """
    Validate parameters. Throws an error if `params` is not a valid
    `SlicesmaskParamsDict` object.
    
    Args:
        params: The parameters object to validate.
    """
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("image", None) is None:
        raise StyxValidationError("`image` must not be None")
    if not isinstance(params["image"], (pathlib.Path, str)):
        raise StyxValidationError(f'`image` has the wrong type: Received `{type(params.get("image", None))}` expected `InputPathType`')
    if params.get("mask", None) is None:
        raise StyxValidationError("`mask` must not be None")
    if not isinstance(params["mask"], (pathlib.Path, str)):
        raise StyxValidationError(f'`mask` has the wrong type: Received `{type(params.get("mask", None))}` expected `InputPathType`')
    if params.get("output", None) is None:
        raise StyxValidationError("`output` must not be None")
    if not isinstance(params["output"], str):
        raise StyxValidationError(f'`output` has the wrong type: Received `{type(params.get("output", None))}` expected `str`')


def slicesmask_cargs(
    params: SlicesmaskParamsDict,
    execution: Execution,
) -> list[str]:
    """
    Build command-line arguments from parameters.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Command-line arguments.
    """
    cargs = []
    cargs.append("slicesmask")
    cargs.append(execution.input_file(params.get("image", None)))
    cargs.append(execution.input_file(params.get("mask", None)))
    cargs.append(params.get("output", None))
    return cargs


def slicesmask_outputs(
    params: SlicesmaskParamsDict,
    execution: Execution,
) -> SlicesmaskOutputs:
    """
    Build outputs object containing output file paths and possibly stdout/stderr.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Outputs object.
    """
    ret = SlicesmaskOutputs(
        root=execution.output_file("."),
        masked_output=execution.output_file(params.get("output", None)),
    )
    return ret


def slicesmask_execute(
    params: SlicesmaskParamsDict,
    runner: Runner | None = None,
) -> SlicesmaskOutputs:
    """
    slicesmask
    
    Tool for masking slices from an image using a mask.
    
    Author: FMRIB Analysis Group, University of Oxford
    
    URL: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki
    
    Args:
        params: The parameters.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `SlicesmaskOutputs`).
    """
    slicesmask_validate(params)
    runner = runner or get_global_runner()
    execution = runner.start_execution(SLICESMASK_METADATA)
    params = execution.params(params)
    cargs = slicesmask_cargs(params, execution)
    ret = slicesmask_outputs(params, execution)
    execution.run(cargs)
    return ret


def slicesmask(
    image: InputPathType,
    mask: InputPathType,
    output: str,
    runner: Runner | None = None,
) -> SlicesmaskOutputs:
    """
    slicesmask
    
    Tool for masking slices from an image using a mask.
    
    Author: FMRIB Analysis Group, University of Oxford
    
    URL: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki
    
    Args:
        image: Input image file.
        mask: Mask file.
        output: Output file.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `SlicesmaskOutputs`).
    """
    params = slicesmask_params(
        image=image,
        mask=mask,
        output=output,
    )
    return slicesmask_execute(params, runner)


__all__ = [
    "SLICESMASK_METADATA",
    "SlicesmaskOutputs",
    "SlicesmaskParamsDict",
    "SlicesmaskParamsDictTagged",
    "slicesmask",
    "slicesmask_execute",
    "slicesmask_params",
]
