[project]
name = "niwrap-freesurfer"
version = "0.1.0"
description = "Freesurfer python wrappers"
license = "LGPL-2.1"
authors = [{ name = "Child Mind Institute", email = "cmi-dair@childmind.org" }]
requires-python = ">=3.10"
dependencies = [
    "styxdefs>=0.5.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
source = ["src/"]

[tool.uv]
package = true